import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { Bell, ChevronLeft, ClipboardList, FileText, Gauge, Home, LogOut, MapPin, ShieldAlert, Truck, UserRound, Wrench, X, Camera, CircleAlert, Navigation, CheckCircle2, Clock3 } from 'lucide-react'
import { Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import type { User } from '../../types/tfms'
import { driverExecutionService } from '../../features/driverExecution/service'
import { deleteAttachment } from '../../services/attachments'
import { browserLocationProvider } from '../../features/driverExecution/location'
import type { DriverExceptionType, DriverProfile, DriverTrip, DriverTripEvent, DriverTripException, DriverTripReceipt, GeoLocation, ReceiptType } from '../../features/driverExecution/types'
import { TRIP_TYPE_LABELS } from '../../features/trips/types'

const executionLabels: Record<string,string> = {
  assigned: 'رحلة مخصصة', to_pickup: 'في الطريق للتحميل', arrived_pickup: 'وصلت للتحميل', pickup_confirmed: 'تم الاستلام',
  in_transit: 'قيد النقل', arrived_delivery: 'وصلت للتسليم', delivered: 'تم التسليم', completed: 'الرحلة مكتملة',
}
const executionSteps = ['assigned','to_pickup','arrived_pickup','pickup_confirmed','in_transit','arrived_delivery','delivered','completed']
const exceptionLabels: Record<string,string> = {
  BREAKDOWN:'عطل مركبة', EMERGENCY:'حالة طارئة', PICKUP_PROBLEM:'مشكلة تحميل', DELIVERY_PROBLEM:'مشكلة تسليم', LOCATION_NOT_FOUND:'الموقع غير موجود',
  LOCATION_CLOSED:'الموقع مغلق', CARGO_NOT_READY:'الحمولة غير جاهزة', QUANTITY_MISMATCH:'اختلاف كمية', ADDRESS_PROBLEM:'مشكلة عنوان', CUSTOMER_NOT_AVAILABLE:'العميل غير متاح',
  CUSTOMER_REFUSED_DELIVERY:'رفض العميل للاستلام', DOCUMENT_PROBLEM:'مشكلة مستند', CARGO_DAMAGE:'تلف حمولة', ROAD_PROBLEM:'مشكلة طريق', GPS_PROBLEM:'مشكلة GPS', OTHER:'أخرى',
}
const problemCategories = [
  { value:'PICKUP_PROBLEM', label:'مشكلة في التحميل', reasons:['الموقع لا يمكن العثور عليه','الموقع مغلق','الحمولة غير جاهزة','اختلاف الكمية','مشكلة مستند','أخرى'] },
  { value:'DELIVERY_PROBLEM', label:'مشكلة في التسليم', reasons:['الموقع لا يمكن العثور عليه','الموقع مغلق','العميل غير متاح','العميل يرفض التسليم','اختلاف الكمية','مشكلة مستند','العنوان غير صحيح','مشكلة في الحمولة','أخرى'] },
  { value:'ROAD_PROBLEM', label:'مشكلة طريق', reasons:['طريق مغلق','ازدحام','تحويلة','الدخول غير ممكن','أخرى'] },
]
const breakdownReasons = ['المحرك','الإطار','الكهرباء','البطارية','الفرامل','التبريد','ناقل الحركة','أخرى']
const emergencyReasons = ['حادث','إصابة','تلف حمولة','مشكلة أمنية','محاولة سرقة','خطر بالطريق','أخرى']

export function DriverPortal({ user, onLogout }: { user: User; onLogout: () => void }) {
  const nav = useNavigate()
  const location = useLocation()
  const [profile,setProfile]=useState<DriverProfile|null>(null)
  const [trips,setTrips]=useState<DriverTrip[]>([])
  const [notifications,setNotifications]=useState<Record<string,unknown>[]>([])
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')

  const refresh = async () => {
    setLoading(true); setError('')
    try {
      const nextProfile=await driverExecutionService.getProfile(user.id)
      const [nextTrips,nextNotifications]=await Promise.all([driverExecutionService.listMyTrips(nextProfile.driverId),driverExecutionService.listNotifications(user.id)])
      setProfile(nextProfile); setTrips(nextTrips); setNotifications(nextNotifications)
    } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تحميل بيانات السائق.') }
    finally { setLoading(false) }
  }
  useEffect(()=>{void refresh()},[user.id])

  if (loading && !profile) return <DriverLoading />
  if (!profile) return <DriverError message={error || 'تعذر تهيئة حساب السائق.'} onLogout={onLogout} onRetry={()=>void refresh()} />

  const unread=notifications.filter(x=>x.read_at==null).length
  return <div className="min-h-screen bg-slate-950 text-slate-900" dir="rtl">
    <div className="mx-auto min-h-screen max-w-xl bg-slate-50 shadow-2xl md:border-x md:border-slate-200">
      <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur">
        <div className="flex items-center justify-between gap-3">
          <button type="button" onClick={()=>nav('/driver')} className="flex min-w-0 items-center gap-3 text-right" aria-label="الرئيسية">
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-950 text-white"><Truck size={20}/></span>
            <span className="min-w-0"><strong className="block truncate text-base">KEMEX</strong><small className="block truncate text-xs text-slate-500">تشغيل السائق</small></span>
          </button>
          <div className="flex items-center gap-1">
            <button type="button" onClick={()=>nav('/driver/notifications')} className="relative grid h-10 w-10 place-items-center rounded-xl text-slate-600 hover:bg-slate-100" aria-label="التنبيهات"><Bell size={19}/>{unread>0&&<span className="absolute right-1 top-1 min-w-4 rounded-full bg-red-600 px-1 text-[10px] font-bold text-white">{unread>9?'9+':unread}</span>}</button>
            <button type="button" onClick={onLogout} className="grid h-10 w-10 place-items-center rounded-xl text-slate-600 hover:bg-slate-100" aria-label="تسجيل الخروج"><LogOut size={18}/></button>
          </div>
        </div>
      </header>

      <main className="px-3 pb-24 pt-4 sm:px-4">
        {error&&<div className="mb-4 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</div>}
        <Routes>
          <Route path="/driver" element={<DriverHome profile={profile} trips={trips} onNavigate={nav} onRefresh={refresh}/>}/>
          <Route path="/driver/trips" element={<DriverTrips trips={trips} onNavigate={nav}/>}/>
          <Route path="/driver/trips/:id" element={<DriverTripDetail profile={profile} trips={trips} onRefresh={refresh}/>}/>
          <Route path="/driver/history" element={<DriverHistory trips={trips} onNavigate={nav}/>}/>
          <Route path="/driver/notifications" element={<DriverNotifications notifications={notifications} onRefresh={refresh}/>}/>
          <Route path="/driver/profile" element={<DriverProfilePage profile={profile}/>}/>
          <Route path="*" element={<Navigate to="/driver" replace/>}/>
        </Routes>
      </main>
      <DriverBottomNav pathname={location.pathname} onNavigate={nav} />
    </div>
  </div>
}

function DriverLoading(){return <div className="grid min-h-screen place-items-center bg-slate-950 p-5 text-center text-white" dir="rtl"><div><div className="mx-auto mb-4 h-10 w-10 animate-spin rounded-full border-4 border-white/20 border-t-white"/><strong>جارٍ تحميل حساب السائق...</strong></div></div>}
function DriverError({message,onLogout,onRetry}:{message:string;onLogout:()=>void;onRetry:()=>void}){return <div className="grid min-h-screen place-items-center bg-slate-950 p-5 text-center" dir="rtl"><div className="max-w-sm rounded-3xl bg-white p-6"><CircleAlert className="mx-auto mb-3 text-red-600"/><h1 className="text-lg font-bold">تعذر فتح مساحة السائق</h1><p className="mt-2 text-sm text-slate-500">{message}</p><div className="mt-5 grid gap-2"><button className="min-h-12 rounded-2xl bg-slate-950 px-4 font-bold text-white" onClick={onRetry}>إعادة المحاولة</button><button className="min-h-12 rounded-2xl border border-slate-200 px-4 font-bold" onClick={onLogout}>تسجيل الخروج</button></div></div></div>}

function DriverHome({profile,trips,onNavigate,onRefresh}:{profile:DriverProfile;trips:DriverTrip[];onNavigate:(to:string)=>void;onRefresh:()=>Promise<void>}){
  const current=[...trips].filter(t=>String(t.execution_status)!=='completed').sort((a,b)=>executionSteps.indexOf(String(b.execution_status))-executionSteps.indexOf(String(a.execution_status)) || String(a.scheduled_start??'').localeCompare(String(b.scheduled_start??'')))[0] ?? null
  const upcoming=trips.filter(t=>['assigned','to_pickup'].includes(String(t.execution_status)) && t.id!==current?.id).slice(0,4)
  const completed=trips.filter(t=>t.execution_status==='completed').length
  return <div className="space-y-4">
    <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-300">مرحبًا</p><h1 className="mt-1 text-xl font-black">{profile.name}</h1><p className="mt-1 text-xs text-slate-400">{profile.code}</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><UserRound size={23}/></span></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>onNavigate('/driver/trips')} className="rounded-2xl bg-white px-4 py-3 text-right text-sm font-black text-slate-950">رحلاتي</button><button onClick={()=>onNavigate('/driver/history')} className="rounded-2xl bg-white/10 px-4 py-3 text-right text-sm font-bold text-white">السجل ({completed})</button></div></section>
    {current?<CurrentTripCard trip={current} onOpen={()=>onNavigate(`/driver/trips/${current.id}`)}/>:<section className="rounded-3xl border border-dashed border-slate-300 bg-white p-6 text-center"><Gauge className="mx-auto text-slate-400"/><h2 className="mt-3 text-lg font-black">لا توجد رحلة قيد التنفيذ</h2><p className="mt-1 text-sm text-slate-500">ستظهر الرحلات المخصصة لك هنا فور إرسالها.</p></section>}
    <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-black">الرحلات المخصصة القادمة</h2><p className="text-xs text-slate-500">تظهر لك رحلاتك فقط</p></div><button onClick={()=>void onRefresh()} className="rounded-xl px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100">تحديث</button></div>{upcoming.length?<div className="space-y-2">{upcoming.map(t=><MiniTrip key={t.id} trip={t} onClick={()=>onNavigate(`/driver/trips/${t.id}`)}/>)}</div>:<p className="py-5 text-center text-sm text-slate-500">لا توجد رحلات مخصصة قادمة.</p>}</section>
  </div>
}

function CurrentTripCard({trip,onOpen}:{trip:DriverTrip;onOpen:()=>void}){const status=String(trip.execution_status||'assigned');return <button onClick={onOpen} className="w-full rounded-3xl border border-slate-200 bg-white p-4 text-right shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">الرحلة الحالية</p><h2 className="mt-1 text-2xl font-black tracking-tight">{trip.trip_number}</h2></div><StatusPill status={status}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Info label="التحميل" value={trip.from_location||'موقع التحميل'} /><Info label="التسليم" value={trip.to_location||'موقع التسليم'} /></div><div className="mt-4 rounded-2xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-sm font-bold"><Clock3 size={16}/>{executionLabels[status]||status}</div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-slate-950 transition-all" style={{width:`${Math.max(8,(executionSteps.indexOf(status)+1)/executionSteps.length*100)}%`}}/></div></div></button>}
function MiniTrip({trip,onClick}:{trip:DriverTrip;onClick:()=>void}){return <button onClick={onClick} className="w-full rounded-2xl border border-slate-200 p-3 text-right hover:border-slate-300"><div className="flex items-center justify-between gap-3"><strong>{trip.trip_number}</strong><StatusPill status={String(trip.execution_status||'assigned')}/></div><div className="mt-2 flex gap-2 text-xs text-slate-500"><span>{trip.from_location||'التحميل'}</span><span>←</span><span>{trip.to_location||'التسليم'}</span></div></button>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-3"><small className="block text-[11px] text-slate-500">{label}</small><span className="mt-1 block truncate font-bold">{value}</span></div>}

function DriverTrips({trips,onNavigate}:{trips:DriverTrip[];onNavigate:(to:string)=>void}){return <div className="space-y-3"><PageIntro title="رحلاتي" subtitle="كل الرحلات المخصصة لحسابك فقط." icon={<ClipboardList/>}/>{trips.length?<div className="space-y-2">{trips.map(t=><MiniTripCard key={t.id} trip={t} onClick={()=>onNavigate(`/driver/trips/${t.id}`)}/>)}</div>:<Empty title="لا توجد رحلات" text="ستظهر التخصيصات الجديدة تلقائيًا هنا."/>}</div>}
function DriverHistory({trips,onNavigate}:{trips:DriverTrip[];onNavigate:(to:string)=>void}){const rows=trips.filter(t=>t.execution_status==='completed');return <div className="space-y-3"><PageIntro title="سجل الرحلات" subtitle="الرحلات التي أغلقتها بالفعل مع المستندات والأحداث." icon={<Clock3/>}/>{rows.length?<div className="space-y-2">{rows.map(t=><MiniTripCard key={t.id} trip={t} onClick={()=>onNavigate(`/driver/trips/${t.id}`)}/>)}</div>:<Empty title="لا يوجد سجل مكتمل" text="ستظهر الرحلات المكتملة هنا."/>}</div>}
function MiniTripCard({trip,onClick}:{trip:DriverTrip;onClick:()=>void}){return <button onClick={onClick} className="w-full rounded-3xl bg-white p-4 text-right shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between gap-3"><div><strong className="text-lg">{trip.trip_number}</strong><p className="mt-1 text-xs text-slate-500">{TRIP_TYPE_LABELS[trip.trip_type]}</p></div><StatusPill status={String(trip.execution_status||'assigned')}/></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Info label="التحميل" value={trip.from_location||'غير محدد'}/><Info label="التسليم" value={trip.to_location||'غير محدد'}/></div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>{formatDate(trip.scheduled_start)}</span><span className="font-bold text-slate-700">التفاصيل <ChevronLeft size={14} className="inline"/></span></div></button>}

function DriverTripDetail({profile,trips,onRefresh}:{profile:DriverProfile;trips:DriverTrip[];onRefresh:()=>Promise<void>}){
  const {id=''}=useParams(); const nav=useNavigate(); const [trip,setTrip]=useState<DriverTrip|null>(trips.find(x=>x.id===id)??null); const [events,setEvents]=useState<DriverTripEvent[]>([]); const [receipts,setReceipts]=useState<DriverTripReceipt[]>([]); const [exceptions,setExceptions]=useState<DriverTripException[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [modal,setModal]=useState<'problem'|'breakdown'|'emergency'|null>(null); const [geoMessage,setGeoMessage]=useState('')
  const load=async()=>{setError('');try{const t=await driverExecutionService.getTrip(id);setTrip(t);const [e,r,x]=await Promise.all([driverExecutionService.listEvents(id),driverExecutionService.listReceipts(id),driverExecutionService.listExceptions(id)]);setEvents(e);setReceipts(r);setExceptions(x)}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الرحلة.')}}
  useEffect(()=>{void load()},[id])
  if(!trip)return <Empty title="الرحلة غير موجودة" text="لا توجد رحلة بهذا المرجع في رحلاتك." action={<button className="rounded-2xl bg-slate-950 px-4 py-3 font-bold text-white" onClick={()=>nav('/driver/trips')}>العودة للرحلات</button>}/>
  const status=String(trip.execution_status||'assigned'); const receiptFor=(type:ReceiptType)=>receipts.find(r=>r.receipt_type===type); const primary=primaryAction(status)
  async function act(next:string,receiptType?:ReceiptType){setBusy(true);setError('');setGeoMessage('');try{if(['arrived_pickup','pickup_confirmed','arrived_delivery','delivered'].includes(next)){const location=await getLocation();if(next==='pickup_confirmed'&&!receiptFor('PICKUP_RECEIPT')) throw new Error('ارفع إيصال الاستلام أولًا.');if(next==='delivered'&&!receiptFor('DELIVERY_RECEIPT')) throw new Error('ارفع إيصال التسليم أولًا.');await driverExecutionService.transition(id,next,location,receiptType?receiptFor(receiptType)?.id:undefined)}else{await driverExecutionService.transition(id,next)}await load();await onRefresh()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ الإجراء.');if(e instanceof Error&&e.message.includes('الموقع'))setGeoMessage(e.message)}finally{setBusy(false)}}
  async function upload(type:ReceiptType,file:File){setBusy(true);setError('');try{let location:GeoLocation|undefined;try{location=await getLocation()}catch{location=undefined}await driverExecutionService.uploadReceipt(id,type,file,location);await load()}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الإيصال.')}finally{setBusy(false)}}
  async function report(input:{exceptionType:DriverExceptionType;category?:string;reason?:string;notes?:string;files?:File[]}){setBusy(true);setError('');const uploaded:{id:string;storagePath:string}[]=[];try{if(input.exceptionType==='BREAKDOWN'&&!input.notes?.trim())throw new Error('وصف العطل مطلوب.');let location:GeoLocation|undefined;try{location=await getLocation()}catch{location=undefined}for(const file of input.files??[]){const attachment=await driverExecutionService.uploadExceptionEvidence(id,file);uploaded.push({id:attachment.id,storagePath:attachment.storagePath})}await driverExecutionService.reportException(id,{...input,location,attachmentIds:uploaded.map(x=>x.id)});setModal(null);await load();await onRefresh()}catch(e){await Promise.all(uploaded.map(x=>deleteAttachment(x.id,x.storagePath).catch(()=>undefined)));setError(e instanceof Error?e.message:'تعذر تسجيل المشكلة.')}finally{setBusy(false)}}
  async function resolveException(){setBusy(true);setError('');try{await driverExecutionService.clearException(id,'استئناف الرحلة بعد معالجة الاستثناء.');await load();await onRefresh()}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث حالة الاستثناء.')}finally{setBusy(false)}}
  async function getLocation(){try{return await browserLocationProvider.getCurrentLocation()}catch(e){throw e}}
  return <div className="space-y-4"><button className="flex items-center gap-1 text-sm font-bold text-slate-600" onClick={()=>nav('/driver/trips')}><ChevronLeft size={18}/>رحلاتي</button>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</div>}{geoMessage&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-800"><MapPin size={16} className="inline ml-1"/>{geoMessage}</div>}
    <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-400">رقم الرحلة</p><h1 className="mt-1 text-3xl font-black">{trip.trip_number}</h1><p className="mt-2 text-sm text-slate-300">{TRIP_TYPE_LABELS[trip.trip_type]} · {trip.reference_number||'بدون مرجع'}</p></div><StatusPill status={status} dark/></div><div className="mt-4 rounded-2xl bg-white/10 p-3 text-sm"><strong>{executionLabels[status]||status}</strong><p className="mt-1 text-xs text-slate-300">{trip.priority==='critical'?'أولوية حرجة':trip.priority==='high'?'أولوية عالية':'الأولوية التشغيلية عادية'}</p></div></section>
    <TripFacts trip={trip} profile={profile}/>
    <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><SectionTitle title="الحالة الحالية" icon={<Gauge/>}/><Progress status={status}/><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Info label="التحميل" value={trip.from_location||'غير محدد'}/><Info label="التسليم" value={trip.to_location||'غير محدد'}/></div></section>
    {trip.exception_status&&<ExceptionBanner status={trip.exception_status} busy={busy} onResolve={()=>void resolveException()} />}
    {primary&&<section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-bold text-slate-500">الإجراء المطلوب الآن</p><div className="mt-2 text-lg font-black">{primary.label}</div><p className="mt-1 text-sm text-slate-500">{primary.hint}</p><button className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 text-base font-black text-white disabled:opacity-50" disabled={busy} onClick={()=>void act(primary.next,primary.receiptType)}>{primary.icon}{busy?'جارٍ التنفيذ...':primary.button}</button>{(status==='arrived_pickup'||status==='arrived_delivery')&&<p className="mt-2 text-center text-xs text-slate-500">سيتم التحقق من الموقع وتسجيل الإحداثيات والمسافة تلقائيًا.</p>}</section>}
    {(status==='arrived_pickup'||status==='arrived_delivery')&&<ReceiptCard type={status==='arrived_pickup'?'PICKUP_RECEIPT':'DELIVERY_RECEIPT'} receipt={status==='arrived_pickup'?receiptFor('PICKUP_RECEIPT'):receiptFor('DELIVERY_RECEIPT')} busy={busy} onUpload={upload}/>} 
    {['assigned','to_pickup','arrived_pickup','pickup_confirmed','in_transit','arrived_delivery','delivered'].includes(status)&&<ExceptionActions busy={busy} onProblem={()=>setModal('problem')} onBreakdown={()=>setModal('breakdown')} onEmergency={()=>setModal('emergency')} />}
    <TripDocs trip={trip} receipts={receipts}/><TripTimeline events={events} exceptions={exceptions}/>
    {modal==='problem'&&<ProblemModal busy={busy} onClose={()=>!busy&&setModal(null)} onSubmit={report}/>} {modal==='breakdown'&&<BreakdownModal busy={busy} onClose={()=>!busy&&setModal(null)} onSubmit={report}/>} {modal==='emergency'&&<EmergencyModal busy={busy} onClose={()=>!busy&&setModal(null)} onSubmit={report}/>} 
  </div>
}

function TripFacts({trip,profile}:{trip:DriverTrip;profile:DriverProfile}){return <div className="space-y-3"><section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><SectionTitle title="البيانات التشغيلية" icon={<FileText/>}/><div className="grid grid-cols-2 gap-2 text-sm"><Info label="رقم الرحلة" value={trip.trip_number}/><Info label="رقم المرجع" value={trip.reference_number||'غير محدد'}/><Info label="النوع" value={TRIP_TYPE_LABELS[trip.trip_type]}/><Info label="الأولوية" value={trip.priority==='critical'?'حرجة':trip.priority==='high'?'عالية':trip.priority==='low'?'منخفضة':'عادية'}/><Info label="السيارة" value={[trip.truck_asset_code,trip.truck_asset_name,trip.truck_plate_number].filter(Boolean).join(' · ')||trip.truck_asset_id}/><Info label="المقطورة" value={[trip.trailer_asset_code,trip.trailer_asset_name,trip.trailer_plate_number].filter(Boolean).join(' · ')||trip.trailer_asset_id||'بدون'}/><Info label="السائق" value={profile.name}/><Info label="موعد التحميل" value={formatDate(trip.scheduled_start)}/><Info label="موعد التسليم" value={formatDate(trip.scheduled_end||trip.scheduled_start)}/></div></section><section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><SectionTitle title="الحمولة" icon={<Truck/>}/><div className="grid grid-cols-2 gap-2 text-sm"><Info label="الوصف" value={trip.cargo_description||'غير محدد'}/><Info label="الكمية" value={trip.cargo_quantity!=null?`${trip.cargo_quantity} ${trip.cargo_unit||''}`:'غير محددة'}/><Info label="الوزن" value={trip.weight_kg!=null?`${trip.weight_kg} كجم`:'غير محدد'}/></div></section><section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><SectionTitle title="التعليمات التشغيلية" icon={<FileText/>}/><p className="text-sm leading-7 text-slate-700">{trip.operational_instructions||'لا توجد تعليمات تشغيلية إضافية.'}</p></section><section className="grid gap-3 sm:grid-cols-2"><DriverLocationCard title="موقع التحميل" name={trip.from_location} latitude={trip.pickup_latitude} longitude={trip.pickup_longitude} instructions={trip.pickup_instructions}/><DriverLocationCard title="موقع التسليم" name={trip.to_location} latitude={trip.delivery_latitude} longitude={trip.delivery_longitude} instructions={trip.delivery_instructions}/></section></div>}

function DriverLocationCard({title,name,latitude,longitude,instructions}:{title:string;name:string|null;latitude:number|null;longitude:number|null;instructions:string|null}){const ready=latitude!=null&&longitude!=null;const mapsUrl=ready?`https://www.google.com/maps/dir/?api=1&destination=${latitude},${longitude}`:'#';return <div className="rounded-3xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs font-bold text-slate-500">{title}</p><p className="mt-2 text-sm leading-6 font-bold">{name||'غير محدد'}</p><p className="mt-1 text-xs text-slate-500">{ready?`${latitude.toFixed(6)}, ${longitude.toFixed(6)}`:'الموقع غير مهيأ'}</p>{instructions&&<p className="mt-2 text-xs leading-5 text-slate-500">{instructions}</p>}{ready&&<a href={mapsUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 text-sm font-black text-white"><Navigation size={17}/> التوجه إلى الموقع</a>}</div>}
function Progress({status}:{status:string}){const index=executionSteps.indexOf(status);return <div className="space-y-2">{executionSteps.map((step,i)=><div key={step} className="flex items-center gap-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-black ${i<=index?'bg-slate-950 text-white':'bg-slate-100 text-slate-400'}`}>{i<index?<CheckCircle2 size={15}/>:i+1}</span><span className={i===index?'font-black':'text-slate-600'}>{executionLabels[step]}</span></div>)}</div>}
function StatusPill({status,dark=false}:{status:string;dark?:boolean}){const exception=status==='BREAKDOWN'||status==='EMERGENCY';return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-black ${exception?'bg-red-100 text-red-700':dark?'bg-white/15 text-white':'bg-slate-100 text-slate-700'}`}>{executionLabels[status]||exceptionLabels[status]||status}</span>}
function ExceptionBanner({status,busy,onResolve}:{status:string;busy:boolean;onResolve:()=>void}){return <section className="rounded-3xl border border-red-200 bg-red-50 p-4"><div className="flex items-center gap-2 font-black text-red-800"><ShieldAlert size={18}/>{exceptionLabels[status]||status}</div><p className="mt-1 text-sm text-red-700">تم تسجيل الاستثناء على الرحلة. السجل محفوظ ويمكن متابعة الرحلة دون فقدان تاريخ الحدث.</p><button type="button" disabled={busy} onClick={onResolve} className="mt-3 min-h-11 rounded-2xl border border-red-200 bg-white px-4 text-sm font-black text-red-800">تمت معالجة المشكلة — استئناف الرحلة</button></section>}
function ReceiptCard({type,receipt,busy,onUpload}:{type:ReceiptType;receipt?:DriverTripReceipt;busy:boolean;onUpload:(type:ReceiptType,file:File)=>Promise<void>}){const input=useRef<HTMLInputElement|null>(null);const isPickup=type==='PICKUP_RECEIPT';return <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><h3 className="font-black">{isPickup?'إيصال الاستلام':'إيصال التسليم'}</h3><p className="mt-1 text-xs text-slate-500">{receipt?'تم رفع الإيصال ويمكن تأكيد الخطوة.':'التقط صورة واضحة للإيصال قبل التأكيد.'}</p></div><FileText size={20} className="text-slate-400"/></div>{receipt?<div className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800"><CheckCircle2 size={16} className="inline ml-1"/>الإيصال مرفوع: {receipt.file_name||'مرفق'}{receipt.preview_url&&receipt.content_type?.startsWith('image/')&&<img src={receipt.preview_url} alt={isPickup?'معاينة إيصال الاستلام':'معاينة إيصال التسليم'} className="mt-3 max-h-72 w-full rounded-2xl object-contain bg-white ring-1 ring-emerald-100"/>}{receipt.storage_path&&receipt.content_type==='application/pdf'&&<a href={receipt.preview_url||'#'} target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded-xl bg-white px-3 py-2 text-xs font-black text-emerald-800 ring-1 ring-emerald-200">فتح المستند</a>}</div>:<><input ref={input} hidden type="file" accept="image/*,.pdf" capture="environment" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void onUpload(type,f);e.currentTarget.value=''}}/><button onClick={()=>input.current?.click()} disabled={busy} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-300 text-sm font-black"><Camera size={20}/>{isPickup?'تصوير إيصال الاستلام':'تصوير إيصال التسليم'}</button></>}</section>}
function TripDocs({trip,receipts}:{trip:DriverTrip;receipts:DriverTripReceipt[]}){return <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><SectionTitle title="مستندات الرحلة" icon={<FileText/>}/><div className="space-y-2 text-sm">{receipts.map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><span>{r.receipt_type==='PICKUP_RECEIPT'?'إيصال الاستلام':'إيصال التسليم'}</span><strong>{r.file_name||'مرفق'}</strong></div>)}{!receipts.length&&<p className="text-slate-500">لا توجد إيصالات مرفوعة بعد.</p>}<div className="mt-3 rounded-2xl bg-slate-50 p-3 text-xs text-slate-600">رقم المرجع: <strong>{trip.reference_number||'—'}</strong></div></div></section>}
function TripTimeline({events,exceptions}:{events:DriverTripEvent[];exceptions:DriverTripException[]}){const all=[...events.map(e=>({at:e.occurred_at,title:executionLabels[e.event_type.toLowerCase()]||eventLabel(e.event_type),detail:e.notes||'',kind:'event'})),...exceptions.map(x=>({at:x.occurred_at,title:exceptionLabels[x.exception_type]||x.exception_type,detail:x.reason||x.notes||'',kind:'exception'}))].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime());return <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><SectionTitle title="الخط الزمني" icon={<Clock3/>}/>{all.length?<div className="space-y-4">{all.map((x,i)=><div key={`${x.kind}-${x.at}-${i}`} className="relative flex gap-3"><span className={`mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-full ${x.kind==='exception'?'bg-red-100 text-red-700':'bg-slate-100 text-slate-700'}`}>{x.kind==='exception'?<CircleAlert size={15}/>:<CheckCircle2 size={15}/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{x.title}</strong><time className="text-[11px] text-slate-400">{formatDateTime(x.at)}</time></div>{x.detail&&<p className="mt-1 text-xs leading-5 text-slate-500">{x.detail}</p>}</div></div>)}</div>:<p className="text-sm text-slate-500">سيظهر سجل التنفيذ هنا مع كل خطوة أو استثناء.</p>}</section>}
function eventLabel(type:string){const map:Record<string,string>={TO_PICKUP:'التوجه للتحميل',PICKUP_ARRIVAL:'الوصول للتحميل',PICKUP_CONFIRMED:'تم تأكيد الاستلام',IN_TRANSIT:'بدء النقل',DELIVERY_ARRIVAL:'الوصول للتسليم',DELIVERED:'تم تأكيد التسليم',COMPLETED:'اكتمال الرحلة',PROBLEM_RESOLVED:'حل المشكلة',MANUAL_GEOFENCE_OVERRIDE:'تجاوز جغرافي معتمد'};return map[type]||type}

function ExceptionActions({busy,onProblem,onBreakdown,onEmergency}:{busy:boolean;onProblem:()=>void;onBreakdown:()=>void;onEmergency:()=>void}){return <section className="grid grid-cols-3 gap-2"><button disabled={busy} onClick={onProblem} className="min-h-12 rounded-2xl border border-slate-200 bg-white text-xs font-black"><CircleAlert size={17} className="mx-auto mb-1"/>تبليغ عن مشكلة</button><button disabled={busy} onClick={onBreakdown} className="min-h-12 rounded-2xl border border-amber-200 bg-amber-50 text-xs font-black text-amber-900"><Wrench size={17} className="mx-auto mb-1"/>تبليغ عن عطل</button><button disabled={busy} onClick={onEmergency} className="min-h-12 rounded-2xl bg-red-600 text-xs font-black text-white"><ShieldAlert size={17} className="mx-auto mb-1"/>حالة طارئة</button></section>}
function primaryAction(status:string){const map:Record<string,{next:string;label:string;button:string;hint:string;icon:ReactNode;receiptType?:ReceiptType}>={
  assigned:{next:'to_pickup',label:'التوجه إلى التحميل',button:'ابدأ التوجه إلى التحميل',hint:'سيتم تسجيل انتقال الرحلة إلى مرحلة التوجه للتحميل.',icon:<Navigation size={20}/>},
  to_pickup:{next:'arrived_pickup',label:'تحقق من الوصول للتحميل',button:'وصلت إلى موقع التحميل',hint:'سيتم التحقق من GPS ونطاق الموقع قبل تسجيل الوصول.',icon:<MapPin size={20}/>},
  arrived_pickup:{next:'pickup_confirmed',label:'رفع الإيصال ثم التأكيد',button:'تأكيد الاستلام',hint:'يتطلب إيصال الاستلام وموقعًا صالحًا داخل النطاق.',icon:<CheckCircle2 size={20}/>,receiptType:'PICKUP_RECEIPT'},
  pickup_confirmed:{next:'in_transit',label:'بدء الرحلة',button:'بدء النقل',hint:'تم توثيق الاستلام. ابدأ الرحلة لتسجيل حالة قيد النقل.',icon:<Navigation size={20}/>},
  in_transit:{next:'arrived_delivery',label:'تحقق من الوصول للتسليم',button:'وصلت إلى موقع التسليم',hint:'سيتم التحقق من GPS ونطاق موقع التسليم.',icon:<MapPin size={20}/>},
  arrived_delivery:{next:'delivered',label:'رفع الإيصال ثم التأكيد',button:'تأكيد التسليم',hint:'يتطلب إيصال التسليم وموقعًا صالحًا داخل النطاق.',icon:<CheckCircle2 size={20}/>,receiptType:'DELIVERY_RECEIPT'},
  delivered:{next:'completed',label:'إغلاق الرحلة',button:'الرحلة مكتملة',hint:'يتم حفظ وقت الإنهاء ضمن الخط الزمني التشغيلي.',icon:<CheckCircle2 size={20}/>},
};return map[status]}

function PageIntro({title,subtitle,icon}:{title:string;subtitle:string;icon:ReactNode}){return <div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-950 text-white">{icon}</span><div><h1 className="text-2xl font-black">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div></div>}
function SectionTitle({title,icon}:{title:string;icon:ReactNode}){return <div className="mb-3 flex items-center gap-2"><span className="text-slate-400">{icon}</span><h2 className="font-black">{title}</h2></div>}
function Empty({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-7 text-center"><p className="font-black">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p>{action&&<div className="mt-4">{action}</div>}</div>}

function ProblemModal({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(x:{exceptionType:DriverExceptionType;category?:string;reason?:string;notes?:string;files?:File[]})=>Promise<void>}){const [cat,setCat]=useState(problemCategories[0].value);const current=problemCategories.find(x=>x.value===cat)||problemCategories[0];const [reason,setReason]=useState(current.reasons[0]);const [notes,setNotes]=useState('');const [files,setFiles]=useState<File[]>([]);return <Modal title="الإبلاغ عن مشكلة" busy={busy} onClose={onClose} onSubmit={()=>void onSubmit({exceptionType:cat as DriverExceptionType,reason,notes,files})}><label className="field"><span>نوع المشكلة</span><select value={cat} onChange={e=>{setCat(e.target.value);setReason(problemCategories.find(x=>x.value===e.target.value)?.reasons[0]||'')}}>{problemCategories.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label className="field"><span>السبب</span><select value={reason} onChange={e=>setReason(e.target.value)}>{current.reasons.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>ملاحظة</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="اكتب التفاصيل المهمة للعمليات..."/></label><label className="field"><span>صورة / مستند اختياري</span><input type="file" multiple accept="image/*,.pdf" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,4))}/></label></Modal>}
function BreakdownModal({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(x:{exceptionType:DriverExceptionType;category?:string;reason?:string;notes?:string;files?:File[]})=>Promise<void>}){const [reason,setReason]=useState(breakdownReasons[0]);const [notes,setNotes]=useState('');const [files,setFiles]=useState<File[]>([]);return <Modal title="تبليغ عن عطل" busy={busy} onClose={onClose} onSubmit={()=>void onSubmit({exceptionType:'BREAKDOWN',reason,notes,files})}><label className="field"><span>نوع العطل</span><select value={reason} onChange={e=>setReason(e.target.value)}>{breakdownReasons.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>وصف المشكلة *</span><textarea required rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="صف العطل وما يلزم للمتابعة..."/></label><label className="field"><span>صور العطل (اختياري)</span><input type="file" multiple accept="image/*,.pdf" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,4))}/></label></Modal>}
function EmergencyModal({busy,onClose,onSubmit}:{busy:boolean;onClose:()=>void;onSubmit:(x:{exceptionType:DriverExceptionType;category?:string;reason?:string;notes?:string;files?:File[]})=>Promise<void>}){const [reason,setReason]=useState(emergencyReasons[0]);const [notes,setNotes]=useState('');const [files,setFiles]=useState<File[]>([]);return <Modal title="🚨 حالة طارئة" busy={busy} onClose={onClose} onSubmit={()=>void onSubmit({exceptionType:'EMERGENCY',reason,notes,files})}><div className="rounded-2xl bg-red-50 p-3 text-sm font-semibold text-red-800">سيصل تنبيه عالي الأولوية إلى مستخدمي العمليات المصرح لهم.</div><label className="field"><span>نوع الحالة</span><select value={reason} onChange={e=>setReason(e.target.value)}>{emergencyReasons.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>ملاحظات</span><textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ما الذي حدث؟"/></label><label className="field"><span>صور / مستندات (اختياري)</span><input type="file" multiple accept="image/*,.pdf" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,4))}/></label></Modal>}
function Modal({title,busy,onClose,onSubmit,children}:{title:string;busy:boolean;onClose:()=>void;onSubmit:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/50 p-3 sm:place-items-center"><div className="w-full max-w-xl rounded-3xl bg-white p-4 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-black">{title}</h2><button onClick={onClose} disabled={busy} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100"><X size={18}/></button></div><div className="mt-4 space-y-3">{children}</div><div className="mt-4 grid grid-cols-2 gap-2"><button className="min-h-12 rounded-2xl border border-slate-200 font-bold" onClick={onClose} disabled={busy}>إلغاء</button><button className="min-h-12 rounded-2xl bg-slate-950 font-bold text-white" onClick={onSubmit} disabled={busy}>{busy?'جارٍ التسجيل...':'تسجيل البلاغ'}</button></div></div></div>}

function DriverNotifications({notifications,onRefresh}:{notifications:Record<string,unknown>[];onRefresh:()=>Promise<void>}){const [busy,setBusy]=useState('');return <div className="space-y-3"><PageIntro title="التنبيهات" subtitle="رسائل التشغيل الموجهة إلى حساب السائق." icon={<Bell/>}/>{notifications.length?<div className="space-y-2">{notifications.map(n=>{const id=String(n.id);return <button key={id} className={`w-full rounded-3xl p-4 text-right shadow-sm ring-1 ring-slate-200 ${n.read_at==null?'bg-white':'bg-slate-50'}`} onClick={async()=>{if(n.read_at==null){setBusy(id);try{await driverExecutionService.markNotificationRead(id);await onRefresh()}finally{setBusy('')}}}} disabled={busy===id}><div className="flex items-center justify-between gap-2"><strong>{String(n.title||'تنبيه')}</strong>{n.read_at==null&&<span className="rounded-full bg-red-100 px-2 py-1 text-[10px] font-black text-red-700">جديد</span>}</div><p className="mt-1 text-sm text-slate-600">{String(n.body||'')}</p><time className="mt-2 block text-[11px] text-slate-400">{formatDateTime(String(n.created_at||''))}</time></button>})}</div>:<Empty title="لا توجد تنبيهات" text="لا توجد رسائل تشغيلية جديدة حاليًا."/>}</div>}
function DriverProfilePage({profile}:{profile:DriverProfile}){return <div className="space-y-3"><PageIntro title="ملفي" subtitle="بيانات حساب التشغيل المرتبطة بملف السائق." icon={<UserRound/>}/><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-3"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-slate-950 text-white"><UserRound/></span><div><h2 className="text-xl font-black">{profile.name}</h2><p className="text-sm text-slate-500">{profile.code}</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><Info label="رقم السائق" value={profile.driverId}/><Info label="الهاتف" value={profile.phone||'غير محدد'}/></div></section></div>}
function DriverBottomNav({pathname,onNavigate}:{pathname:string;onNavigate:(to:string)=>void}){const tabs=[{label:'الرئيسية',path:'/driver',icon:<Home/>},{label:'رحلاتي',path:'/driver/trips',icon:<ClipboardList/>},{label:'السجل',path:'/driver/history',icon:<Clock3/>},{label:'ملفي',path:'/driver/profile',icon:<UserRound/>}];return <nav className="fixed bottom-0 left-1/2 z-30 grid w-full max-w-xl -translate-x-1/2 grid-cols-4 border-t border-slate-200 bg-white/95 backdrop-blur md:border-x">{tabs.map(x=><button key={x.path} onClick={()=>onNavigate(x.path)} className={`min-h-16 text-[11px] font-bold ${pathname===x.path?'text-slate-950':'text-slate-400'}`}><span className="mx-auto mb-1 grid w-fit place-items-center">{x.icon}</span>{x.label}</button>)}</nav>}

function formatDate(value:string|null|undefined){if(!value)return 'غير محدد';try{return new Intl.DateTimeFormat('ar-EG-u-nu-latn',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return String(value)}}
function formatDateTime(value:string){return formatDate(value)}
