export type TripType = 'cargo'|'equipment'|'internal'|'return'
export type TripStatus = 'draft'|'assigned'|'dispatched'|'in_transit'|'delivered'|'received'|'invoiced'|'paid'|'cancelled'
export type RateType = 'per_trip'|'per_ton'|'per_km'|'per_m3'|'fixed_monthly'
export type PermitType = 'delivery'|'receipt'
export type PermitCondition = 'سليم'|'تالف'|'ناقص'
export type TripCostCategory = 'fuel'|'driver_allowance'|'tolls'|'loading'|'unloading'|'maintenance'|'permit_fees'|'overnight'|'other'
export type Trip = { id:string; trip_number:string; trip_type:TripType; truck_asset_id:string; trailer_asset_id:string|null; driver_id:string; contract_id:string|null; from_project_id:string|null; to_project_id:string|null; from_location:string|null; to_location:string|null; cargo_description:string; cargo_quantity:number|null; cargo_unit:string|null; scheduled_start:string|null; scheduled_end:string|null; actual_start:string|null; actual_end:string|null; status:TripStatus; distance_km:number|null; fuel_consumed_liters:number|null; rate_type:RateType|null; rate_amount:number|null; total_charge:number; is_billable:boolean; billed_to_client_id:string|null; invoice_id:string|null; notes:string|null; created_at:string; updated_at:string }
export type TripInsert = Omit<Trip,'id'|'trip_number'|'actual_start'|'actual_end'|'total_charge'|'created_at'|'updated_at'> & {id?:string;trip_number?:string;total_charge?:number}
export type TripUpdate = Partial<TripInsert>
export type TripPermit = {id:string;trip_id:string;permit_type:PermitType;permit_number:string;issued_at:string;issued_by_user_id:string|null;signed_at:string|null;signed_by_name:string|null;signed_by_role:string|null;signature_url:string|null;attachment_urls:string[];receipt_condition:PermitCondition|null;received_quantity:number|null;discrepancy_notes:string|null;notes:string|null;created_at:string}
export type TripPermitInsert = Omit<TripPermit,'id'|'permit_number'|'issued_at'|'issued_by_user_id'|'created_at'> & {id?:string;permit_number?:string}
export type TripCost = {id:string;trip_id:string;cost_category:TripCostCategory;description:string|null;amount:number;currency:string;vendor_name:string|null;receipt_url:string|null;cost_date:string;created_at:string}
export type TripCostInsert = Omit<TripCost,'id'|'created_at'> & {id?:string}
export type TripFuelLog = {id:string;trip_id:string;asset_id:string;liters:number;unit_price:number;total_cost:number;odometer_reading:number|null;fuel_station:string|null;filled_at:string;created_at:string}
export type TripFuelLogInsert = Omit<TripFuelLog,'id'|'total_cost'|'created_at'> & {id?:string}
export const TRIP_TYPE_LABELS:Record<TripType,string>={cargo:'بضائع',equipment:'معدات',internal:'نقل داخلي',return:'رحلة عودة'}
export const TRIP_STATUS_LABELS:Record<TripStatus,string>={draft:'مسودة',assigned:'مجدولة',dispatched:'انطلقت',in_transit:'في الطريق',delivered:'تم التسليم',received:'تم الاستلام',invoiced:'مفوترة',paid:'مدفوعة',cancelled:'ملغاة'}
export const RATE_TYPE_LABELS:Record<RateType,string>={per_trip:'بالرحلة',per_ton:'بالطن',per_km:'بالكيلومتر',per_m3:'بالمتر المكعب',fixed_monthly:'شهري ثابت'}
export const PERMIT_TYPE_LABELS:Record<PermitType,string>={delivery:'إذن تسليم',receipt:'إذن استلام'}
export const TRIP_COST_CATEGORY_LABELS:Record<TripCostCategory,string>={fuel:'وقود',driver_allowance:'بدلات السائق',tolls:'رسوم طرق',loading:'تحميل',unloading:'تفريغ',maintenance:'صيانة',permit_fees:'رسوم أذونات',overnight:'مبيت',other:'أخرى'}
export const TRIP_STATUS_TRANSITIONS:Record<TripStatus,TripStatus[]>={draft:['assigned','cancelled'],assigned:['dispatched','cancelled'],dispatched:['in_transit','cancelled'],in_transit:['delivered','cancelled'],delivered:['received'],received:['invoiced'],invoiced:['paid'],paid:[],cancelled:[]}
export function calculateTripCharge(rateType:RateType|null,rateAmount:number|null,quantity:number|null,distance:number|null):number {const rate=Math.max(0,rateAmount??0);switch(rateType){case 'per_trip':return rate;case 'per_ton':case 'per_m3':return rate*Math.max(0,quantity??0);case 'per_km':return rate*Math.max(0,distance??0);case 'fixed_monthly':return rate;default:return 0}}
