import { useMemo, useState } from 'react'
import { ClipboardPenLine, Download, Search, ShieldCheck } from 'lucide-react'
import type { Asset, Driver, Project, WorkOrder } from '../types/tfms'
import { ReferenceValue } from '../components/ReferenceValue'

type Props={records:Record<string,unknown>[];assets?:Asset[];projects?:Project[];drivers?:Driver[];workOrders?:WorkOrder[];moduleData?:Record<string,Record<string,unknown>[]>}
export function AuditPage({records,assets=[],projects=[],drivers=[],workOrders=[],moduleData={}}:Props){
 const [q,setQ]=useState('');const [action,setAction]=useState('');const [source,setSource]=useState('')
 const actions=useMemo(()=>Array.from(new Set(records.map(x=>String(x.action??'')).filter(Boolean))),[records]);const sources=useMemo(()=>Array.from(new Set(records.map(x=>String(x.source??'')).filter(Boolean))),[records]);
 const rows=useMemo(()=>records.filter(r=>(!action||String(r.action)===action)&&(!source||String(r.source)===source)&&(!q||Object.values(r).some(v=>String(v??'').toLowerCase().includes(q.toLowerCase())))),[records,q,action,source])
 function exportCsv(){const headers=['التاريخ والوقت','المستخدم','العملية','نوع السجل','المرجع','التفاصيل','المصدر'];const esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+[headers.map(esc).join(','),...rows.map(r=>[r.ts,r.user,r.action,r.entity,displayReference('ref',r.ref,{assets,projects,drivers,workOrders,records:moduleData}),r.details,r.source].map(esc).join(','))].join('\r\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`KEMEX-audit-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div><div className="page-head"><div><h1>سجل التدقيق</h1><p>جميع العمليات الحساسة: المستخدم، العملية، التفاصيل والمصدر — سجل قراءة محمي.</p></div><button className="secondary-button" onClick={exportCsv}><Download size={16}/> تصدير CSV</button></div><div className="metric-grid compact"><Metric icon={ShieldCheck} label="إجمالي الأحداث" value={records.length}/><Metric icon={ClipboardPenLine} label="الأحداث المعروضة" value={rows.length}/></div><section className="panel"><div className="toolbar"><div className="search-field"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث في المستخدم أو العملية أو المرجع..."/></div><select value={action} onChange={e=>setAction(e.target.value)}><option value="">كل العمليات</option>{actions.map(x=><option key={x}>{x}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option value="">كل المصادر</option>{sources.map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>التاريخ والوقت</th><th>المستخدم</th><th>العملية</th><th>نوع السجل</th><th>المرجع</th><th>التفاصيل</th><th>المصدر</th></tr></thead><tbody>{rows.map(r=><tr key={String(r.id)}><td>{formatDateTime(String(r.ts??''))}</td><td>{String(r.user??'—')}</td><td><span className={`badge ${/حذف|رفض/.test(String(r.action))?'red':/اعتماد/.test(String(r.action))?'green':'blue'}`}>{String(r.action??'—')}</span></td><td>{String(r.entity??'—')}</td><td><ReferenceValue field="ref" value={r.ref} lookups={{assets,projects,drivers,workOrders,records:moduleData}}/></td><td>{String(r.details??'—')}</td><td>{String(r.source??'—')}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد أحداث مطابقة.</div>}</div></section></div>
}
function formatDateTime(v:string){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(d)}
function Metric({icon:Icon,label,value}:{icon:typeof ClipboardPenLine;label:string;value:string|number}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
