import { useMemo, useState } from 'react'
import { Download, ChartColumn, CircleDollarSign, Gauge, Scale } from 'lucide-react'
import type { Asset, FuelOperation, Project, WorkOrder } from '../types/tfms'
import { calculateAssetCost } from './CostsPage'
import { sameReference } from '../utils/referenceLabels'

type Props={assets:Asset[];projects:Project[];moduleData:Record<string,Record<string,unknown>[]>;workOrders:WorkOrder[];fuelOps:FuelOperation[]}
type Rate={asset?:string;type?:string;cat?:string;unit:string;rate:number;min?:number}
const RATES:Rate[]=[
 {asset:'A15',unit:'ساعة',rate:120,min:300},{asset:'A16',unit:'ساعة',rate:200,min:400},{type:'حفار',unit:'ساعة',rate:350,min:160},{type:'لودر',unit:'ساعة',rate:250,min:160},{type:'بلدوزر',unit:'ساعة',rate:280,min:160},{type:'أوناش',unit:'ساعة',rate:300,min:150},{type:'معدات رصف',unit:'ساعة',rate:220,min:140},{type:'قلابية',unit:'يوم',rate:4500,min:22},{type:'شاحنة نقل',unit:'يوم',rate:3500,min:22},{type:'أتوبيس عمال',unit:'يوم',rate:1800,min:25},{type:'أتوبيس',unit:'يوم',rate:2800,min:22},{type:'سيارة خدمة',unit:'كم',rate:2.5},{type:'سيارة موقع',unit:'كم',rate:2.2},{type:'كمبروسر هواء',unit:'ساعة',rate:60,min:120},{type:'مضخة مياه',unit:'ساعة',rate:40,min:100}
]
export function ChargingPage({assets,projects,moduleData,workOrders,fuelOps}:Props){
 const current=new Date().toISOString().slice(0,7);const [month,setMonth]=useState(current);const [project,setProject]=useState('')
 const rows=useMemo(()=>assets.filter(a=>{const selected=projects.find(p=>sameReference(project,p));return !selected||sameReference(a.proj,selected)}).map(a=>{const rate=rateFor(a);const [from,to]=monthRange(month);const ops=(moduleData.operations??[]).filter(x=>(String(x.assetId??'')===a.id||String(x.assetId??'')===a.code)&&String(x.status??'')==='معتمد'&&String(x.date??'')>=from&&String(x.date??'')<=to);const qty=rate?.unit==='ساعة'?ops.reduce((s,x)=>s+Number(x.hours||0),0):rate?.unit==='كم'?ops.reduce((s,x)=>s+Number(x.km||0),0):ops.length;const billed=rate?rate.unit==='كم'?qty:Math.max(qty,(rate.min||0)*daysInMonth(month)/30.4):0;const amount=rate?billed*rate.rate:0;const cost=calculateAssetCost(a,from,to,workOrders,fuelOps,moduleData).total;return {a,rate,qty,billed,amount,cost,net:amount-cost}}).filter(x=>x.rate),[assets,moduleData,month,project])
 const total=rows.reduce((s,x)=>s+x.amount,0);const qty=rows.reduce((s,x)=>s+x.qty,0);const net=rows.reduce((s,x)=>s+x.net,0)
 function exportCsv(){const headers=['الأصل','المشروع','الوحدة','السعر','الاستخدام الفعلي','الكمية المفوترة','قيمة التحميل','الفارق عن التكلفة'];const esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+[headers.map(esc).join(','),...rows.map(x=>[x.a.name,projects.find(p=>sameReference(x.a.proj,p))?.name??'المقر',x.rate.unit,x.rate.rate,x.qty,x.billed,x.amount,x.net].map(esc).join(','))].join('\r\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`KEMEX-charging-${month}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div><div className="page-head"><div><h1>التحميل الداخلي على المشروعات</h1><p>الأسعار والحد الأدنى للفوترة — يفصل الاستخدام الفعلي عن أساس الاحتساب.</p></div><div className="page-actions"><button className="secondary-button" onClick={exportCsv}><Download size={16}/> تصدير CSV</button></div></div>
 <section className="panel"><div className="form-grid report-filter-grid"><label className="field"><span>شهر الفوترة</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="field"><span>المشروع</span><select value={project} onChange={e=>setProject(e.target.value)}><option value="">كل المشروعات</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div></section>
 <div className="metric-grid compact"><Metric icon={CircleDollarSign} label="إجمالي التحميل" value={`${fmt(total)} ج.م`}/><Metric icon={Gauge} label="الأصول المحملة" value={rows.length}/><Metric icon={ChartColumn} label="الاستخدام الفعلي" value={fmt(qty)}/><Metric icon={Scale} label="صافي الفرق عن التكلفة" value={`${fmt(net)} ج.م`}/></div>
 <section className="panel"><div className="section-title"><div className="section-title-icon"><ChartColumn size={16}/></div><div><strong>تفاصيل التحميل</strong><small>التحميل يحسب من البيانات التشغيلية المعتمدة.</small></div></div><div className="table-wrap"><table><thead><tr><th>الأصل</th><th>المشروع</th><th>الوحدة</th><th>السعر</th><th>الاستخدام الفعلي</th><th>المفوتر بحد أدنى</th><th>قيمة التحميل</th><th>الفارق عن التكلفة</th></tr></thead><tbody>{rows.map(x=><tr key={x.a.id}><td><ReferenceValue field="asset" value={x.a.id} lookups={{assets}}/></td><td><ReferenceValue field="proj" value={x.a.proj} lookups={{projects}}/></td><td>{x.rate.unit}</td><td>{fmt(x.rate.rate)}</td><td>{fmt(x.qty)}</td><td>{fmt(x.billed)}</td><td><strong>{fmt(x.amount)}</strong></td><td><strong>{fmt(x.net)}</strong></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد أصول لها تعريفة تحميل مطابقة.</div>}</div></section>
 <section className="panel"><div className="section-title"><div className="section-title-icon"><Scale size={16}/></div><div><strong>تعريفة التحميل الداخلي المرجعية</strong><small>القيم التالية من المرجع الأصلي ويمكن تطوير إدارتها لاحقًا.</small></div></div><div className="table-wrap"><table><thead><tr><th>النطاق</th><th>الوحدة</th><th>السعر</th><th>الحد الأدنى</th></tr></thead><tbody>{RATES.map((r,i)=><tr key={i}><td>{r.asset?<ReferenceValue field="asset" value={r.asset} lookups={{assets}}/>:r.type?`نوع: ${r.type}`:`فئة: ${r.cat}`}</td><td>{r.unit}</td><td>{fmt(r.rate)}</td><td>{r.min?`${fmt(r.min)} ${r.unit}`:'—'}</td></tr>)}</tbody></table></div></section>
 </div>
}
function rateFor(a:Asset){return RATES.find(r=>r.asset===a.id||r.asset===a.code)||RATES.find(r=>r.type===a.type)||RATES.find(r=>r.cat===a.cat)}
function monthRange(month:string){const [y,m]=month.split('-').map(Number);const last=new Date(y,m,0).getDate();return [`${month}-01`,`${month}-${String(last).padStart(2,'0')}`]}
function daysInMonth(month:string){const [y,m]=month.split('-').map(Number);return new Date(y,m,0).getDate()}
function fmt(n:number){return new Intl.NumberFormat('ar-EG',{maximumFractionDigits:1}).format(Number(n||0))}
function Metric({icon:Icon,label,value}:{icon:typeof ChartColumn;label:string;value:string|number}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
