import { useMemo, useState, type ReactNode } from 'react'
import { Building2, FileText, Pencil, Plus, ReceiptText, X } from 'lucide-react'
import type { Customer } from '../types/tfms'

type Props={customers:Record<string,unknown>[];invoices:Record<string,unknown>[];canEdit:boolean;onSave:(record:Record<string,unknown>)=>Promise<void>|void}
export function CustomersPage({customers,invoices,canEdit,onSave}:Props){
 const [editing,setEditing]=useState<Record<string,unknown>|null>(null);const [busy,setBusy]=useState(false)
 const rows=useMemo(()=>customers.map(c=>{const inv=invoices.filter(i=>String(i.party??'')===String(c.name??''));const revenue=inv.filter(i=>['معتمدة','مرحلة','مدفوعة','محصلة'].includes(String(i.status??''))).reduce((s,i)=>s+Number(i.total||0),0);return {...c,invoiceCount:inv.length,revenue}}),[customers,invoices])
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);try{const fd=new FormData(e.currentTarget);await onSave({...editing,code:String(fd.get('code')||''),name:String(fd.get('name')||''),contact:String(fd.get('contact')||''),phone:String(fd.get('phone')||''),email:String(fd.get('email')||''),address:String(fd.get('address')||''),taxNo:String(fd.get('taxNo')||''),paymentTerms:String(fd.get('paymentTerms')||''),creditLimit:Number(fd.get('creditLimit')||0),salesRep:String(fd.get('salesRep')||''),kind:String(fd.get('kind')||''),status:String(fd.get('status')||'نشط'),notes:String(fd.get('notes')||'')});setEditing(null)}finally{setBusy(false)}}
 return <div><div className="page-head"><div><h1>العملاء والخدمات الخارجية</h1><p>فصل المعاملات الخارجية عن التحميل الداخلي، مع متابعة الفواتير والإيرادات المعتمدة.</p></div>{canEdit&&<button className="primary-button" onClick={()=>setEditing({id:`CU-${Date.now()}`,code:`CU-${customers.length+1}` ,name:'',contact:'',phone:'',email:'',address:'',taxNo:'',paymentTerms:'30 يوم',creditLimit:0,salesRep:'',kind:'عميل مشروعات أو خدمات خارجية',status:'نشط',notes:''})}><Plus size={16}/> عميل</button>}</div>
 <div className="metric-grid compact"><Metric icon={Building2} label="العملاء" value={rows.length}/><Metric icon={FileText} label="الفواتير" value={rows.reduce((s,x)=>s+Number(x.invoiceCount),0)}/><Metric icon={ReceiptText} label="الإيرادات المعتمدة" value={`${fmt(rows.reduce((s,x)=>s+Number(x.revenue),0))} ج.م`}/></div>
 <div className="g2">{rows.map(c=><section className="panel" key={String(c.id)}><div className="section-title"><div className="section-title-icon"><Building2 size={16}/></div><div><strong>{String(c.name||'—')}</strong><small>{String(c.kind||'—')}</small></div>{canEdit&&<button className="icon-button" title="تعديل" onClick={()=>setEditing({...c})}><Pencil size={15}/></button>}</div><div className="detail-grid"><div className="detail-item"><span>جهة الاتصال</span><strong>{String(c.contact||'—')}</strong></div><div className="detail-item"><span>الهاتف</span><strong>{String(c.phone||'—')}</strong></div><div className="detail-item"><span>الفواتير</span><strong>{String(c.invoiceCount)}</strong></div><div className="detail-item"><span>الإيرادات المعتمدة</span><strong>{fmt(Number(c.revenue))} ج.م</strong></div><div className="detail-item" style={{gridColumn:'1 / -1'}}><span>ملاحظات</span><strong>{String(c.notes||'—')}</strong></div></div></section>)}</div>
 {editing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setEditing(null)}><form className="modal-card wide form-modal-premium" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{customers.some(c=>c.id===editing.id)?'تعديل عميل':'عميل جديد'}</h2><p>بيانات العميل والخدمات الخارجية</p></div><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-sections"><FormBlock title="هوية العميل" hint="بيانات التعريف والتصنيف"><Field name="code" label="كود العميل" value={String(editing.code||'')} /><Field name="name" label="اسم العميل / الجهة" value={String(editing.name||'')} required/><Field name="kind" label="التصنيف" value={String(editing.kind||'')} /><Select name="status" label="الحالة" value={String(editing.status||'نشط')} options={['نشط','موقوف','غير نشط']}/></FormBlock><FormBlock title="التواصل والعنوان" hint="بيانات الاتصال بالموقع أو الجهة"><Field name="contact" label="جهة الاتصال" value={String(editing.contact||'')}/><Field name="phone" label="الهاتف" value={String(editing.phone||'')}/><Field name="email" label="البريد الإلكتروني" value={String(editing.email||'')}/><Field name="address" label="العنوان" value={String(editing.address||'')}/></FormBlock><FormBlock title="البيانات التجارية" hint="الضرائب وشروط التعامل والحد الائتماني"><Field name="taxNo" label="الرقم الضريبي" value={String(editing.taxNo||'')}/><Field name="paymentTerms" label="شروط السداد" value={String(editing.paymentTerms||'')}/><Field name="creditLimit" label="الحد الائتماني ج.م" value={String(editing.creditLimit||0)} type="number"/><Field name="salesRep" label="مسؤول الحساب" value={String(editing.salesRep||'')}/></FormBlock><label className="field field-full"><span>ملاحظات العميل</span><textarea name="notes" defaultValue={String(editing.notes||'')} rows={4} placeholder="نطاق الخدمات، العناوين، المستندات، شروط التوريد أو أي معلومات تجارية مهمة..."/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ العميل'}</button></div></form></div>}
 </div>
}
function FormBlock({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>{hint}</span></div><div className="form-grid">{children}</div></section>}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:string[]}){return <label className="field"><span>{label}</span><select name={name} defaultValue={value}>{options.map(v=><option key={v}>{v}</option>)}</select></label>}
function Field({name,label,value,required,type='text'}:{name:string;label:string;value:string;required?:boolean;type?:string}){return <label className="field"><span>{label}{required?' *':''}</span><input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined} step={type==='number'?'any':undefined}/></label>}
function fmt(n:number){return new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(n||0)}
function Metric({icon:Icon,label,value}:{icon:typeof Building2;label:string;value:string|number}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
