import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Building2, FileText, Pencil, Plus, ReceiptText, X } from 'lucide-react'
import type { Customer } from '../types/tfms'
import { Button, CardGrid, EmptyState, PageHeader, StatusBadge } from '../components/ui'
import { useCurrency } from '../features/settings'

type Props={customers:Customer[];invoices:Record<string,unknown>[];canEdit:boolean;onSave:(record:Customer)=>Promise<void>}

/** Client registry backed by the dedicated public.clients table. */
export function CustomersPage({customers,invoices,canEdit,onSave}:Props){
 const [editing,setEditing]=useState<Customer|null>(null);const [busy,setBusy]=useState(false)
 const {formatMoney}=useCurrency()
 type Row=Customer & {invoiceCount:number;revenue:number}
 const rows=useMemo<Row[]>(()=>customers.map(c=>{const inv=invoices.filter(i=>String(i.party??'')===String(c.name??''));const revenue=inv.filter(i=>['معتمدة','مرحلة','مدفوعة','محصلة'].includes(String(i.status??''))).reduce((s,i)=>s+Number(i.total||0),0);return {...c,invoiceCount:inv.length,revenue}}),[customers,invoices])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const fd=new FormData(e.currentTarget);const next:Customer={...editing,code:String(fd.get('code')||''),name:String(fd.get('name')||''),contact:String(fd.get('contact')||''),phone:String(fd.get('phone')||''),email:String(fd.get('email')||''),address:String(fd.get('address')||''),taxNo:String(fd.get('taxNo')||''),paymentTerms:String(fd.get('paymentTerms')||''),creditLimit:Number(fd.get('creditLimit')||0),salesRep:String(fd.get('salesRep')||''),kind:String(fd.get('kind')||''),status:String(fd.get('status')||'نشط'),notes:String(fd.get('notes')||'')};if(!next.code||!next.name)return;setBusy(true);try{await onSave(next);setEditing(null)}finally{setBusy(false)}}
 return <div className="space-y-6"><PageHeader title="العملاء والخدمات الخارجية" description="قاعدة العملاء المرتبطة بالمشروعات والفواتير والخدمات الخارجية." action={canEdit?<Button onClick={()=>setEditing({id:`CU-${Date.now()}`,code:'',name:'',kind:'',status:'نشط'})}><Plus size={16}/> عميل جديد</Button>:undefined}/>
 <div className="metric-grid compact"><Metric icon={Building2} label="العملاء" value={rows.length}/><Metric icon={FileText} label="الفواتير" value={rows.reduce((s,x)=>s+x.invoiceCount,0)}/><Metric icon={ReceiptText} label="الإيرادات المعتمدة" value={formatMoney(rows.reduce((s,x)=>s+x.revenue,0))}/></div>
 {rows.length?<CardGrid items={rows} getKey={row=>row.id} minColumnWidth={320} renderCard={c=><article className="panel"><div className="section-title"><div className="section-title-icon"><Building2 size={16}/></div><div><strong>{c.name}</strong><small>{c.kind||'عميل'}</small></div><StatusBadge>{c.status||'نشط'}</StatusBadge>{canEdit&&<button className="icon-button" title="تعديل" onClick={()=>setEditing({...c})}><Pencil size={15}/></button>}</div><div className="detail-grid"><div className="detail-item"><span>جهة الاتصال</span><strong>{c.contact||'—'}</strong></div><div className="detail-item"><span>الهاتف</span><strong>{c.phone||'—'}</strong></div><div className="detail-item"><span>الفواتير</span><strong>{c.invoiceCount}</strong></div><div className="detail-item"><span>الإيرادات المعتمدة</span><strong>{formatMoney(c.revenue)}</strong></div><div className="detail-item"><span>حد ائتماني</span><strong>{c.creditLimit?formatMoney(c.creditLimit):'غير محدد'}</strong></div><div className="detail-item"><span>مسؤول الحساب</span><strong>{c.salesRep||'—'}</strong></div><div className="detail-item field-full"><span>العنوان / ملاحظات</span><strong>{c.address||c.notes||'—'}</strong></div></div></article>}/>:<EmptyState title="لا توجد عملاء" description="لم تتم إضافة عملاء فعليين إلى سجل العملاء بعد." action={canEdit?<Button variant="secondary" onClick={()=>setEditing({id:`CU-${Date.now()}`,code:'',name:'',kind:'',status:'نشط'})}>إضافة أول عميل</Button>:undefined}/>} 
 {editing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setEditing(null)}><form className="modal-card wide form-modal-premium" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{customers.some(c=>c.id===editing.id)?'تعديل عميل':'إضافة عميل'}</h2><p>السجل الرئيسي للعميل — بدون تخزين بيانات تشغيلية مكررة.</p></div><button type="button" className="icon-button" onClick={()=>!busy&&setEditing(null)}><X size={18}/></button></div><div className="form-sections"><FormBlock title="هوية العميل" hint="التعريف والتصنيف"><Field name="code" label="كود العميل" value={editing.code||''} required/><Field name="name" label="اسم العميل / الجهة" value={editing.name||''} required/><Field name="kind" label="التصنيف" value={editing.kind||''}/><Select name="status" label="الحالة" value={editing.status||'نشط'} options={['نشط','موقوف','غير نشط']}/></FormBlock><FormBlock title="التواصل والعنوان" hint="بيانات الاتصال المعتمدة"><Field name="contact" label="جهة الاتصال" value={editing.contact||''}/><Field name="phone" label="الهاتف" value={editing.phone||''}/><Field name="email" label="البريد الإلكتروني" value={editing.email||''}/><Field name="address" label="العنوان" value={editing.address||''}/></FormBlock><FormBlock title="البيانات التجارية" hint="شروط التعامل والمتابعة"><Field name="taxNo" label="الرقم الضريبي" value={editing.taxNo||''}/><Field name="paymentTerms" label="شروط السداد" value={editing.paymentTerms||''}/><Field name="creditLimit" label="الحد الائتماني" type="number" value={String(editing.creditLimit||0)}/><Field name="salesRep" label="مسؤول الحساب" value={editing.salesRep||''}/></FormBlock><label className="field field-full"><span>ملاحظات العميل</span><textarea name="notes" defaultValue={editing.notes||''} rows={4}/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>!busy&&setEditing(null)}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ العميل'}</button></div></form></div>}</div>
}
function FormBlock({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>{hint}</span></div><div className="form-grid">{children}</div></section>}
function Field({name,label,value,required,type='text'}:{name:string;label:string;value:string;required?:boolean;type?:string}){return <label className="field"><span>{label}{required&&' *'}</span><input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined}/></label>}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:string[]}){return <label className="field"><span>{label}</span><select name={name} defaultValue={value}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Metric({icon:Icon,label,value}:{icon:typeof Building2;label:string;value:string|number}){return <article className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></article>}
