import { Fuel, Plus, Search, TrendingUp, X, type LucideIcon } from 'lucide-react'
import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import type { Asset, FuelOperation, Project } from '../types/tfms'
import { ReferenceValue } from '../components/ReferenceValue'
import { sameReference } from '../utils/referenceLabels'
import { StatusBadge } from '../components/StatusBadge'

export function FuelPage({fuelOps,assets,projects,onSave,defaultPrices={diesel:0,petrol:0}}:{fuelOps:FuelOperation[];assets:Asset[];projects:Project[];onSave?:(x:FuelOperation)=>Promise<void>|void;defaultPrices?:{diesel:number;petrol:number}}) {
  const [query,setQuery]=useState(''); const [editing,setEditing]=useState<FuelOperation|null>(null); const [busy,setBusy]=useState(false)
  const rows=useMemo(()=>fuelOps.filter(x=>{const a=assets.find(a=>sameReference(x.assetId,a));const p=projects.find(p=>sameReference(x.proj,p));const q=query.trim().toLowerCase();return !q||[a?.name,a?.code,p?.name,p?.code,x.station,x.type,x.notes].filter(Boolean).join(' ').toLowerCase().includes(q)}),[fuelOps,assets,projects,query])
  const issued=fuelOps.filter(x=>x.type==='صرف'); const liters=issued.reduce((s,x)=>s+Number(x.qty||0),0); const total=issued.reduce((s,x)=>s+Number(x.total||0),0); const avg=liters?total/liters:0
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing||!onSave)return;setBusy(true);try{const fd=new FormData(e.currentTarget);const qty=Number(fd.get('qty')||0);const price=Number(fd.get('price')||0);await onSave({...editing,type:String(fd.get('type')||'صرف'),assetId:String(fd.get('assetId')||''),proj:String(fd.get('proj')||''),date:String(fd.get('date')||''),qty,price,total:qty*price,status:String(fd.get('status')||'مسجلة'),station:String(fd.get('station')||''),tank:String(fd.get('tank')||''),meter:Number(fd.get('meter')||0),sup:String(fd.get('sup')||''),inv:String(fd.get('inv')||''),notes:String(fd.get('notes')||'')});setEditing(null)}finally{setBusy(false)}}
  return <div><div className="page-head"><div><h1>إدارة الوقود</h1><p>الصرف والتعبئة وتحليل التكلفة والاستهلاك حسب الأصل والمشروع.</p></div><div className="head-actions"><div className="read-only-pill"><TrendingUp size={15}/> متوسط اللتر {fmt(avg)} ج.م</div>{onSave&&<button className="primary-button" onClick={()=>setEditing({id:`F-${Date.now()}`,type:'صرف',assetId:assets[0]?.id,proj:projects[0]?.id,tank:'',date:new Date().toISOString().slice(0,10),qty:0,price:defaultPrices.diesel||defaultPrices.petrol,total:0,status:'مسجلة',station:'',sup:'',inv:'',meter:assets[0]?.meter??0,notes:''})}><Plus size={16}/> حركة وقود</button>}</div></div>
    <div className="metric-grid compact"><Metric label="إجمالي اللترات المصروفة" value={`${fmt(liters)} لتر`} icon={Fuel}/><Metric label="قيمة الصرف" value={`${fmt(total)} ج.م`} icon={TrendingUp}/><Metric label="متوسط سعر اللتر" value={`${fmt(avg)} ج.م`} icon={Fuel}/><Metric label="حركات الصرف" value={issued.length} icon={Search}/></div>
    <section className="panel"><div className="toolbar"><div className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث في حركات الوقود..."/></div><span className="toolbar-count">{rows.length} حركة</span></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>الأصل</th><th>المشروع</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{rows.slice(0,200).map(x=><tr key={x.id}><td>{fmtDate(x.date)}</td><td>{x.type}</td><td><ReferenceValue field="assetId" value={x.assetId} lookups={{assets,projects}}/></td><td><ReferenceValue field="proj" value={x.proj} lookups={{projects}}/></td><td>{fmt(x.qty)} لتر</td><td>{fmt(x.price)} ج.م</td><td><strong>{fmt(x.total)} ج.م</strong></td><td><StatusBadge>{x.status}</StatusBadge></td></tr>)}</tbody></table></div></section>
    {editing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setEditing(null)}><form className="modal-card wide form-modal-premium" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="form-kicker">حركة مستندية</div><h2>تسجيل حركة وقود</h2><p>الحساب الإجمالي يتم من الكمية × سعر الوحدة مع تسجيل المصدر والعداد والمرجع.</p></div><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-sections"><FormBlock title="نوع الحركة والربط"><Select name="type" label="نوع الحركة" value={editing.type} options={['صرف','استلام','تسوية'].map(v=>({v,l:v}))}/><Select name="assetId" label="الأصل" value={editing.assetId??''} options={[{v:'',l:'— بدون أصل —'},...assets.map(x=>({v:x.id,l:`${x.name} — ${x.code}`}))]}/><Select name="proj" label="المشروع" value={editing.proj??''} options={[{v:'',l:'المقر / بدون مشروع'},...projects.map(x=>({v:x.id,l:`${x.name} — ${x.code}`}))]}/><Select name="tank" label="الخزان" value={editing.tank??''} options={[{v:'',l:'— بدون خزان —'}]}/></FormBlock><FormBlock title="الكمية والتكلفة"><Field name="date" label="التاريخ" value={editing.date} type="date"/><Field name="qty" label="الكمية لتر" value={String(editing.qty)} type="number"/><Field name="price" label="سعر اللتر" value={String(editing.price)} type="number"/><Field name="total" label="الإجمالي" value={String(editing.total)} type="number"/><Field name="meter" label="عداد الأصل وقت الحركة" value={String(editing.meter??0)} type="number"/></FormBlock><FormBlock title="المصدر والمستند"><Field name="station" label="المحطة / المورد" value={editing.station??''}/><Field name="sup" label="المورد" value={editing.sup??''}/><Field name="inv" label="رقم الفاتورة / الإيصال" value={editing.inv??''}/><Select name="status" label="الحالة" value={editing.status} options={['مسجلة','معتمدة','مرفوضة'].map(v=>({v,l:v}))}/></FormBlock><label className="field field-full"><span>ملاحظات الحركة</span><textarea name="notes" defaultValue={editing.notes??''} rows={4} placeholder="سبب الحركة، موقع التعبئة، ملاحظة فرق الكمية أو أي بيان مستندي..."/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ الحركة'}</button></div></form></div>}
  </div>
}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:{v:string;l:string}[]}){return <label className="field"><span>{label}</span><select name={name} defaultValue={value}>{options.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select></label>}
function Field({name,label,value,type='text'}:{name:string;label:string;value:string;type?:string}){return <label className="field"><span>{label}</span><input name={name} type={type} defaultValue={value}/></label>}
function FormBlock({title,children}:{title:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>بيانات متعلقة بحركة الوقود</span></div><div className="form-grid">{children}</div></section>}
function Metric({label,value,icon:Icon}:{label:string;value:string|number;icon:LucideIcon}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
const fmt=(n:number)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:1}).format(n)
const fmtDate=(v:string)=>v?new Intl.DateTimeFormat('ar-EG',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v)):'—'
