import { useMemo, useState, type ReactNode } from 'react'
import { Check, CircleDollarSign, FileCheck2, Link2, Pencil, Plus, ReceiptText, RotateCcw, X } from 'lucide-react'
import type { Asset, Driver, Project, WorkOrder, User } from '../types/tfms'
import { ReferenceValue } from '../components/ReferenceValue'
import { Button, DataTable, PageHeader, StatusBadge } from '../components/ui'
import { ConfirmModal } from '../shared/ui'
import { PrintRecordButton } from '../shared/printing'
import { useCurrency } from '../features/settings'

import { APP_LOCALE } from '../shared/formatters/locale'
type Props={records:Record<string,unknown>[];user:User;canEdit:boolean;vatRate:number;onSave:(record:Record<string,unknown>)=>Promise<void>|void;assets?:Asset[];projects?:Project[];drivers?:Driver[];workOrders?:WorkOrder[];moduleData?:Record<string,Record<string,unknown>[]>}
const supplierFlow=['مسجلة','بانتظار مراجعة','معتمدة','مرحلة','مدفوعة'];const customerFlow=['مسجلة','بانتظار مراجعة','معتمدة','محصلة']
export function InvoicesPage({records,user,canEdit,vatRate,onSave,assets=[],projects=[],drivers=[],workOrders=[],moduleData={}}:Props){
  const {formatMoney}=useCurrency()
 const [editing,setEditing]=useState<Record<string,unknown>|null>(null);const [settling,setSettling]=useState<Record<string,unknown>|null>(null);const [pendingTransition,setPendingTransition]=useState<{record:Record<string,unknown>;next:string}|null>(null);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('all');const [error,setError]=useState('')
 const rows=useMemo(()=>records.filter(r=>filter==='all'||String(r.status||'')===filter),[records,filter]);const pending=records.filter(r=>['مسجلة','بانتظار مراجعة','معتمدة'].includes(String(r.status))).length;const due=records.filter(r=>['معتمدة','مرحلة'].includes(String(r.status))).reduce((s,r)=>s+Number(r.total||0),0);const paid=records.filter(r=>['مدفوعة','محصلة'].includes(String(r.status))).reduce((s,r)=>s+Number(r.total||0),0)
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing||busy)return;setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);const number=String(fd.get('number')||'').trim();const party=String(fd.get('party')||'').trim();const date=String(fd.get('date')||'');const dueDate=String(fd.get('dueDate')||'');const sub=Number(fd.get('sub')||0);const enteredVat=String(fd.get('vat')||'').trim();const discount=Number(fd.get('discount')||0);const vat=enteredVat===''?Math.round(sub*vatRate/100):Number(enteredVat);const total=Math.max(0,sub+vat-discount);const paidAmount=Number(fd.get('paid')||0);if(!number||!party||!date)throw new Error('رقم الفاتورة والجهة وتاريخ الفاتورة حقول مطلوبة.');if(dueDate&&dueDate<date)throw new Error('تاريخ الاستحقاق لا يمكن أن يسبق تاريخ الفاتورة.');if([sub,vat,discount,paidAmount].some(v=>!Number.isFinite(v)||v<0))throw new Error('قيم الفاتورة يجب أن تكون أرقامًا غير سالبة.');if(paidAmount>total)throw new Error('المبلغ المدفوع لا يمكن أن يتجاوز إجمالي الفاتورة.');await onSave({...editing,number,kind:String(fd.get('kind')||'مورد'),party,link:String(fd.get('link')||''),date,dueDate,description:String(fd.get('description')||''),sub,vat,discount,total,paid:paidAmount,remaining:Math.max(0,total-paidAmount),paymentMethod:String(fd.get('paymentMethod')||''),account:String(fd.get('account')||''),status:String(editing.status||'مسجلة'),notes:String(fd.get('notes')||'')});setEditing(null)}catch(err){setError(err instanceof Error?err.message:'تعذر حفظ الفاتورة.')}finally{setBusy(false)}}
 async function applyTransition(record:Record<string,unknown>,nextStatus:string){if(!canEdit||busy)return;setBusy(true);setError('');try{const trail=Array.isArray(record.apprs)?record.apprs:[];await onSave({...record,status:nextStatus,apprs:[...trail,{by:user.name,act:nextStatus}]});setPendingTransition(null)}catch(err){setError(err instanceof Error?err.message:'تعذر تنفيذ دورة الفاتورة.')}finally{setBusy(false)}}
 function next(record:Record<string,unknown>){if(!canEdit||busy)return;const flow=String(record.kind)==='مورد'?supplierFlow:customerFlow;const i=flow.indexOf(String(record.status));if(i<0||i===flow.length-1)return;const nextStatus=flow[i+1];if(nextStatus==='مدفوعة'||nextStatus==='محصلة'){setSettling(record);return}setPendingTransition({record,next:nextStatus})}
 async function settle(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!settling||busy)return;setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);const total=Number(settling.total||0);const currentPaid=Number(settling.paid||0);const remaining=Math.max(0,total-currentPaid);const amount=Number(fd.get('amount')||0);const paymentDate=String(fd.get('paymentDate')||new Date().toISOString().slice(0,10));const method=String(fd.get('method')||'').trim();const notes=String(fd.get('notes')||'').trim();if(!Number.isFinite(amount)||amount<=0)throw new Error('أدخل قيمة سداد أو تحصيل أكبر من صفر.');if(amount>remaining)throw new Error('مبلغ الحركة لا يمكن أن يتجاوز الرصيد المتبقي.');const newPaid=currentPaid+amount;const finalRemaining=Math.max(0,total-newPaid);const supplier=String(settling.kind)==='مورد';const finalStatus=supplier?'مدفوعة':'محصلة';const trail=Array.isArray(settling.apprs)?settling.apprs:[];await onSave({...settling,paid:newPaid,remaining:finalRemaining,status:finalRemaining===0?finalStatus:String(settling.status||'مرحلة'),paymentMethod:method||settling.paymentMethod||'',lastPaymentDate:paymentDate,apprs:[...trail,{by:user.name,act:supplier?'تسجيل سداد':'تسجيل تحصيل',amount,date:paymentDate}],notes:notes||settling.notes||''});setSettling(null)}catch(err){setError(err instanceof Error?err.message:'تعذر تسجيل السداد أو التحصيل.')}finally{setBusy(false)}}
 return <div className="space-y-6"><PageHeader title="الفواتير والمستحقات" description="تسجيل ثم مراجعة ومطابقة بالعقد أو المشروع ثم اعتماد ثم ترحيل ثم سداد." action={canEdit&&<Button icon={<Plus size={16}/>} onClick={()=>setEditing({id:`IV-${Date.now()}`,number:`INV-${new Date().getFullYear()}-${String(records.length+1).padStart(2,'0')}`,kind:'مورد',party:'',link:'',date:new Date().toISOString().slice(0,10),sub:0,vat:0,total:0,status:'مسجلة',notes:''})}>فاتورة</Button>} />
 {error&&<div className="global-error" role="alert">{error}</div>}
 <div className="metric-grid compact"><Metric icon={ReceiptText} label="إجمالي الفواتير" value={records.length}/><Metric icon={FileCheck2} label="قيد الدورة" value={pending}/><Metric icon={CircleDollarSign} label="مستحق مرحل" value={formatMoney(due)}/><Metric icon={Check} label="مسدد/محصل" value={formatMoney(paid)}/></div>
 <section className="space-y-4"><div className="flex flex-wrap gap-2">{['all','مسجلة','بانتظار مراجعة','معتمدة','مرحلة','مدفوعة','محصلة','مرفوضة'].map(s=><button key={s} type="button" className={`rounded-full border px-3 py-2 text-sm font-semibold transition ${filter===s?'border-primary-600 bg-primary-700 text-white':'border-gray-200 bg-white text-gray-600 hover:bg-gray-50'}`} onClick={()=>setFilter(s)}>{s==='all'?'الكل':s}</button>)}</div>
 <DataTable
   rows={rows}
   columns={[
     { id:'number', header:'رقم الفاتورة', render:r=><strong>{String(r.number||'—')}</strong>, sortValue:r=>String(r.number||'') },
     { id:'kind', header:'النوع', render:r=>String(r.kind||'—'), sortValue:r=>String(r.kind||'') },
     { id:'party', header:'الجهة', render:r=>String(r.party||'—'), sortValue:r=>String(r.party||'') },
     { id:'link', header:'المرتبط بها', render:r=><ReferenceValue field="link" value={r.link} lookups={{assets,projects,drivers,workOrders,records:moduleData}} /> },
     { id:'date', header:'التاريخ', render:r=>String(r.date||'—'), sortValue:r=>String(r.date||'') },
     { id:'sub', header:'الصافي', render:r=>fmt(Number(r.sub)), sortValue:r=>Number(r.sub||0) },
     { id:'vat', header:'ض.ق.م', render:r=>fmt(Number(r.vat)), sortValue:r=>Number(r.vat||0) },
     { id:'total', header:'الإجمالي', render:r=><strong>{fmt(Number(r.total))}</strong>, sortValue:r=>Number(r.total||0) },
     { id:'status', header:'الحالة', render:r=><StatusBadge tone={String(r.status)==='مرفوضة'?'red':String(r.status)==='مدفوعة'||String(r.status)==='محصلة'?'emerald':String(r.status)==='بانتظار مراجعة'?'amber':'blue'}>{String(r.status||'—')}</StatusBadge>, sortValue:r=>String(r.status||'') },
     { id:'action', header:'إجراء', render:r=>{const flow=String(r.kind)==='مورد'?supplierFlow:customerFlow;const i=flow.indexOf(String(r.status));return <div className="flex flex-wrap gap-2"><PrintRecordButton documentTitle={String(r.kind)==='مورد'?'فاتورة مورد':'فاتورة عميل'} documentNumber={String(r.number||'')} documentDate={String(r.date||'')} documentStatus={String(r.status||'')} reference={String(r.link||'')} meta={[{label:'الجهة',value:String(r.party||'—')},{label:'المرتبط بها',value:<ReferenceValue field="link" value={r.link} lookups={{assets,projects,drivers,workOrders,records:moduleData}} />},{label:'تاريخ الاستحقاق',value:String(r.dueDate||'—')},{label:'طريقة السداد',value:String(r.paymentMethod||'—')},{label:'الحساب / مركز التكلفة',value:String(r.account||'—')}]} signatures={[{label:'المحاسب'},{label:'المراجع المالي'},{label:'المعتمد'},{label:'المستلم'}]} footerNote="فاتورة صادرة من نظام KEMEX لإدارة النقل والأسطول والتكاليف."><div className="print-section-title">تفاصيل القيمة</div><table><tbody><tr><th>البند</th><th>القيمة</th></tr><tr><td>الوصف</td><td>{String(r.description||'—')}</td></tr><tr><td>الصافي قبل الضريبة</td><td>{formatMoney(Number(r.sub||0))}</td></tr><tr><td>ضريبة القيمة المضافة</td><td>{formatMoney(Number(r.vat||0))}</td></tr><tr><td>الخصم</td><td>{formatMoney(Number(r.discount||0))}</td></tr><tr><td><strong>الإجمالي</strong></td><td><strong>{formatMoney(Number(r.total||0))}</strong></td></tr><tr><td>المدفوع / المحصل</td><td>{formatMoney(Number(r.paid||0))}</td></tr><tr><td>المتبقي</td><td>{formatMoney(Number(r.remaining||0))}</td></tr><tr><td>ملاحظات</td><td>{String(r.notes||'—')}</td></tr></tbody></table></PrintRecordButton>{canEdit&&i>=0&&i<flow.length-1?<Button size="sm" disabled={busy} onClick={()=>void next(r)}>{flow[i+1]==='مدفوعة'?'تسجيل السداد':flow[i+1]}</Button>:canEdit?<Button variant="ghost" size="sm" icon={<Pencil size={14}/>} onClick={()=>setEditing({...r})}>تعديل</Button>:null}</div>} },
   ]}
   rowKey={r=>String(r.id)}
   searchableText={r=>[r.number,r.kind,r.party,r.link,r.date,r.status].map(v=>String(v??'')).join(' ')}
   emptyState={<div className="px-6 py-16 text-center text-sm font-medium text-gray-500">لا توجد فواتير بهذه الحالة.</div>}
   mobilePresentation="cards"
   enableColumnVisibility
   columnVisibilityStorageKey="kemex.invoices.columns.v1"
   exportable
   exportFileName="KEMEX-invoices"
   printTitle="سجل الفواتير والمستحقات"
 />
 </section>
 <ConfirmModal open={Boolean(pendingTransition)} title="تأكيد انتقال الفاتورة" description={pendingTransition?("سيتم نقل الفاتورة "+String(pendingTransition.record.number||pendingTransition.record.id||"")+" إلى حالة «"+pendingTransition.next+"» وتسجيل الإجراء باسم "+user.name+"."):""} confirmLabel={pendingTransition?.next==="مرحلة"?"ترحيل الفاتورة":"تأكيد الإجراء"} cancelLabel="إلغاء" busy={busy} onCancel={()=>!busy&&setPendingTransition(null)} onConfirm={()=>pendingTransition?void applyTransition(pendingTransition.record,pendingTransition.next):undefined}/>
 {settling&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setSettling(null)}><form className="modal-card wide form-modal-premium" onSubmit={settle} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{String(settling.kind)==="مورد"?"تسجيل سداد":"تسجيل تحصيل"}</h2><p>{String(settling.number||settling.id||"")} · المتبقي {formatMoney(Math.max(0,Number(settling.total||0)-Number(settling.paid||0)))}</p></div><button type="button" className="icon-button" onClick={()=>!busy&&setSettling(null)} aria-label="إغلاق"><X size={18}/></button></div><div className="form-sections"><FormBlock title="المبلغ والحركة" hint="يمكن تسجيل حركة جزئية ثم استكمال الرصيد لاحقًا"><Field name="amount" label="المبلغ" value={String(Math.max(0,Number(settling.total||0)-Number(settling.paid||0)))} type="number" required/><Field name="paymentDate" label="تاريخ السداد / التحصيل" value={new Date().toISOString().slice(0,10)} type="date" required/><Field name="method" label="طريقة السداد" value={String(settling.paymentMethod||"")}/></FormBlock><label className="field field-full"><span>ملاحظات الحركة</span><textarea name="notes" rows={3}/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setSettling(null)} disabled={busy}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?"جارٍ التسجيل...":"حفظ الحركة"}</button></div></form></div>}
 {editing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setEditing(null)}><form className="modal-card wide form-modal-premium" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>فاتورة جديدة</h2><p>تسجيل الفاتورة واحتساب الضريبة وفق إعداد المؤسسة ({vatRate}%).</p></div><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-sections"><FormBlock title="هوية الفاتورة" hint="رقم الفاتورة والجهة ونوع المعاملة"><Field name="number" label="رقم الفاتورة" value={String(editing.number||'')} required/><label className="field"><span>النوع</span><select name="kind" defaultValue={String(editing.kind||'مورد')}><option>مورد</option><option>عميل</option></select></label><Field name="party" label="الجهة" value={String(editing.party||'')} required/><ReferenceSelect name="link" label="المرتبط بها" value={String(editing.link||'')} assets={assets} projects={projects} moduleData={moduleData}/></FormBlock><FormBlock title="الفترة والمستند" hint="تاريخ الاستحقاق ووصف المعاملة"><Field name="date" label="تاريخ الفاتورة" value={String(editing.date||'')} type="date" required/><Field name="dueDate" label="تاريخ الاستحقاق" value={String(editing.dueDate||'')} type="date"/><Field name="description" label="وصف المعاملة" value={String(editing.description||'')} /><Field name="account" label="الحساب / مركز التكلفة" value={String(editing.account||'')} /></FormBlock><FormBlock title="القيمة والضريبة" hint={`ضريبة المؤسسة الحالية ${vatRate}%`}><Field name="sub" label="الصافي قبل الضريبة" value={String(editing.sub||0)} type="number" required/><Field name="vat" label="ضريبة القيمة المضافة" value={String(editing.vat??'')} type="number"/><Field name="discount" label="الخصم" value={String(editing.discount||0)} type="number"/><Field name="paid" label="المدفوع / المحصل" value={String(editing.paid||0)} type="number"/></FormBlock><FormBlock title="السداد والمتابعة" hint="يُحتسب المتبقي آليًا عند الحفظ"><Field name="paymentMethod" label="طريقة السداد" value={String(editing.paymentMethod||'')} /><div className="read-only-pill">الإجمالي المحسوب: {formatMoney(Math.max(0,Number(editing.sub||0)+Number(editing.vat||0)-Number(editing.discount||0)))}</div><div className="read-only-pill">المتبقي الحالي: {formatMoney(Math.max(0,Number(editing.total||0)-Number(editing.paid||0)))}</div></FormBlock><label className="field field-full"><span>ملاحظات المطابقة</span><textarea name="notes" defaultValue={String(editing.notes||'')} rows={4} placeholder="مرجع العقد، رقم المستند، بيانات التسوية أو أي ملاحظة مالية..."/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}><RotateCcw size={15}/> إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'تسجيل الفاتورة'}</button></div></form></div>}
 </div>
}

function ReferenceSelect({name,label,value,assets,projects,moduleData}:{name:string;label:string;value:string;assets:Asset[];projects:Project[];moduleData:Record<string,Record<string,unknown>[]>}){
 const customers=moduleData.customers??[]; const contracts=moduleData.contracts??[];
 return <label className="field"><span><Link2 size={13}/> {label}</span><select name={name} defaultValue={value}><option value="">بدون ارتباط</option><optgroup label="الأصول">{assets.map(a=><option key={`a-${a.id}`} value={a.id}>{a.name} — {a.code}</option>)}</optgroup><optgroup label="المشروعات">{projects.map(p=><option key={`p-${p.id}`} value={p.id}>{p.name} — {p.code}</option>)}</optgroup><optgroup label="العقود">{contracts.map(c=><option key={`c-${String(c.id)}`} value={String(c.id)}>{String(c.lessor??'عقد')} — {String(c.number??c.id)}</option>)}</optgroup><optgroup label="العملاء">{customers.map(c=><option key={`cu-${String(c.id)}`} value={String(c.id)}>{String(c.name??c.code??c.id)}</option>)}</optgroup></select></label>
}

function Field({name,label,value,type='text',required}:{name:string;label:string;value:string;type?:string;required?:boolean}){return <label className="field"><span>{label}{required?' *':''}</span><input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined}/></label>}
function fmt(n:number){return new Intl.NumberFormat(APP_LOCALE,{maximumFractionDigits:0}).format(n||0)}
function FormBlock({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>{hint}</span></div><div className="form-grid">{children}</div></section>}

function Metric({icon:Icon,label,value}:{icon:typeof ReceiptText;label:string;value:string|number}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
