import { useMemo, useState, type ReactNode } from 'react'
import { Check, CircleDollarSign, FileCheck2, Link2, Pencil, Plus, ReceiptText, RotateCcw, X } from 'lucide-react'
import type { Asset, Driver, Project, WorkOrder, User } from '../types/tfms'
import { ReferenceValue } from '../components/ReferenceValue'

type Props={records:Record<string,unknown>[];user:User;canEdit:boolean;vatRate:number;onSave:(record:Record<string,unknown>)=>Promise<void>|void;assets?:Asset[];projects?:Project[];drivers?:Driver[];workOrders?:WorkOrder[];moduleData?:Record<string,Record<string,unknown>[]>}
const supplierFlow=['مسجلة','بانتظار مراجعة','معتمدة','مرحلة','مدفوعة'];const customerFlow=['مسجلة','بانتظار مراجعة','معتمدة','محصلة']
export function InvoicesPage({records,user,canEdit,vatRate,onSave,assets=[],projects=[],drivers=[],workOrders=[],moduleData={}}:Props){
 const [editing,setEditing]=useState<Record<string,unknown>|null>(null);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('all')
 const rows=useMemo(()=>records.filter(r=>filter==='all'||String(r.status||'')===filter),[records,filter]);const pending=records.filter(r=>['مسجلة','بانتظار مراجعة','معتمدة'].includes(String(r.status))).length;const due=records.filter(r=>['معتمدة','مرحلة'].includes(String(r.status))).reduce((s,r)=>s+Number(r.total||0),0);const paid=records.filter(r=>['مدفوعة','محصلة'].includes(String(r.status))).reduce((s,r)=>s+Number(r.total||0),0)
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);try{const fd=new FormData(e.currentTarget);const sub=Number(fd.get('sub')||0);const enteredVat=String(fd.get('vat')||'');const discount=Number(fd.get('discount')||0);const vat=enteredVat===''?Math.round(sub*vatRate/100):Number(enteredVat);const total=Math.max(0,sub+vat-discount);const paid=Number(fd.get('paid')||0);await onSave({...editing,number:String(fd.get('number')||''),kind:String(fd.get('kind')||'مورد'),party:String(fd.get('party')||''),link:String(fd.get('link')||''),date:String(fd.get('date')||''),dueDate:String(fd.get('dueDate')||''),description:String(fd.get('description')||''),sub,vat,discount,total,paid,remaining:Math.max(0,total-paid),paymentMethod:String(fd.get('paymentMethod')||''),account:String(fd.get('account')||''),status:String(editing.status||'مسجلة'),notes:String(fd.get('notes')||'')});setEditing(null)}finally{setBusy(false)}}
 async function next(record:Record<string,unknown>){const flow=String(record.kind)==='مورد'?supplierFlow:customerFlow;const i=flow.indexOf(String(record.status));if(i<0||i===flow.length-1)return;await onSave({...record,status:flow[i+1],apprs:[...(Array.isArray(record.apprs)?record.apprs:[]),{by:user.name,act:flow[i+1]}]})}
 return <div><div className="page-head"><div><h1>الفواتير والمستحقات</h1><p>تسجيل ثم مراجعة ومطابقة بالعقد أو المشروع ثم اعتماد ثم ترحيل ثم سداد.</p></div>{canEdit&&<button className="primary-button" onClick={()=>setEditing({id:`IV-${Date.now()}`,number:`INV-${new Date().getFullYear()}-${String(records.length+1).padStart(2,'0')}`,kind:'مورد',party:'',link:'',date:new Date().toISOString().slice(0,10),sub:0,vat:0,total:0,status:'مسجلة',notes:''})}><Plus size={16}/> فاتورة</button>}</div>
 <div className="metric-grid compact"><Metric icon={ReceiptText} label="إجمالي الفواتير" value={records.length}/><Metric icon={FileCheck2} label="قيد الدورة" value={pending}/><Metric icon={CircleDollarSign} label="مستحق مرحل" value={`${fmt(due)} ج.م`}/><Metric icon={Check} label="مسدد/محصل" value={`${fmt(paid)} ج.م`}/></div>
 <section className="panel"><div className="toolbar"><div className="filter-pills">{['all','مسجلة','بانتظار مراجعة','معتمدة','مرحلة','مدفوعة','محصلة','مرفوضة'].map(s=><button key={s} type="button" className={`filter-pill ${filter===s?'active':''}`} onClick={()=>setFilter(s)}>{s==='all'?'الكل':s}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>رقم الفاتورة</th><th>النوع</th><th>الجهة</th><th>المرتبط بها</th><th>التاريخ</th><th>الصافي</th><th>ض.ق.م</th><th>الإجمالي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{rows.map(r=>{const flow=String(r.kind)==='مورد'?supplierFlow:customerFlow;const i=flow.indexOf(String(r.status));return <tr key={String(r.id)}><td><strong>{String(r.number||'—')}</strong></td><td>{String(r.kind||'—')}</td><td>{String(r.party||'—')}</td><td><ReferenceValue field="link" value={r.link} lookups={{assets,projects,drivers,workOrders,records:moduleData}}/></td><td>{String(r.date||'—')}</td><td>{fmt(Number(r.sub))}</td><td>{fmt(Number(r.vat))}</td><td><strong>{fmt(Number(r.total))}</strong></td><td><span className="badge blue">{String(r.status||'—')}</span></td><td>{canEdit&&i>=0&&i<flow.length-1?<button className="workflow-button primary" disabled={busy} onClick={()=>next(r)}>{flow[i+1]==='مدفوعة'?'تسجيل السداد':flow[i+1]}</button>:canEdit&&<button className="icon-button" title="تعديل" aria-label="تعديل" onClick={()=>setEditing({...r})}><Pencil size={14}/></button>}</td></tr>})}</tbody></table>{!rows.length&&<div className="empty">لا توجد فواتير بهذه الحالة.</div>}</div></section>
 {editing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setEditing(null)}><form className="modal-card wide form-modal-premium" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>فاتورة جديدة</h2><p>تسجيل الفاتورة واحتساب الضريبة وفق إعداد المؤسسة ({vatRate}%).</p></div><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-sections"><FormBlock title="هوية الفاتورة" hint="رقم الفاتورة والجهة ونوع المعاملة"><Field name="number" label="رقم الفاتورة" value={String(editing.number||'')} required/><label className="field"><span>النوع</span><select name="kind" defaultValue={String(editing.kind||'مورد')}><option>مورد</option><option>عميل</option></select></label><Field name="party" label="الجهة" value={String(editing.party||'')} required/><ReferenceSelect name="link" label="المرتبط بها" value={String(editing.link||'')} assets={assets} projects={projects} moduleData={moduleData}/></FormBlock><FormBlock title="الفترة والمستند" hint="تاريخ الاستحقاق ووصف المعاملة"><Field name="date" label="تاريخ الفاتورة" value={String(editing.date||'')} type="date" required/><Field name="dueDate" label="تاريخ الاستحقاق" value={String(editing.dueDate||'')} type="date"/><Field name="description" label="وصف المعاملة" value={String(editing.description||'')} /><Field name="account" label="الحساب / مركز التكلفة" value={String(editing.account||'')} /></FormBlock><FormBlock title="القيمة والضريبة" hint={`ضريبة المؤسسة الحالية ${vatRate}%`}><Field name="sub" label="الصافي قبل الضريبة" value={String(editing.sub||0)} type="number" required/><Field name="vat" label="ضريبة القيمة المضافة" value={String(editing.vat??'')} type="number"/><Field name="discount" label="الخصم" value={String(editing.discount||0)} type="number"/><Field name="paid" label="المدفوع / المحصل" value={String(editing.paid||0)} type="number"/></FormBlock><FormBlock title="السداد والمتابعة" hint="يُحتسب المتبقي آليًا عند الحفظ"><Field name="paymentMethod" label="طريقة السداد" value={String(editing.paymentMethod||'')} /><div className="read-only-pill">الإجمالي المحسوب: {fmt(Math.max(0,Number(editing.sub||0)+Number(editing.vat||0)-Number(editing.discount||0)))} ج.م</div><div className="read-only-pill">المتبقي الحالي: {fmt(Math.max(0,Number(editing.total||0)-Number(editing.paid||0)))} ج.م</div></FormBlock><label className="field field-full"><span>ملاحظات المطابقة</span><textarea name="notes" defaultValue={String(editing.notes||'')} rows={4} placeholder="مرجع العقد، رقم المستند، بيانات التسوية أو أي ملاحظة مالية..."/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}><RotateCcw size={15}/> إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'تسجيل الفاتورة'}</button></div></form></div>}
 </div>
}

function ReferenceSelect({name,label,value,assets,projects,moduleData}:{name:string;label:string;value:string;assets:Asset[];projects:Project[];moduleData:Record<string,Record<string,unknown>[]>}){
 const customers=moduleData.customers??[]; const contracts=moduleData.contracts??[];
 return <label className="field"><span><Link2 size={13}/> {label}</span><select name={name} defaultValue={value}><option value="">بدون ارتباط</option><optgroup label="الأصول">{assets.map(a=><option key={`a-${a.id}`} value={a.id}>{a.name} — {a.code}</option>)}</optgroup><optgroup label="المشروعات">{projects.map(p=><option key={`p-${p.id}`} value={p.id}>{p.name} — {p.code}</option>)}</optgroup><optgroup label="العقود">{contracts.map(c=><option key={`c-${String(c.id)}`} value={String(c.id)}>{String(c.lessor??'عقد')} — {String(c.number??c.id)}</option>)}</optgroup><optgroup label="العملاء">{customers.map(c=><option key={`cu-${String(c.id)}`} value={String(c.id)}>{String(c.name??c.code??c.id)}</option>)}</optgroup></select></label>
}

function Field({name,label,value,type='text',required}:{name:string;label:string;value:string;type?:string;required?:boolean}){return <label className="field"><span>{label}{required?' *':''}</span><input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined}/></label>}
function fmt(n:number){return new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(n||0)}
function FormBlock({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>{hint}</span></div><div className="form-grid">{children}</div></section>}

function Metric({icon:Icon,label,value}:{icon:typeof ReceiptText;label:string;value:string|number}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
