import { AlertCircle, CheckCircle2, Clock3, Pencil, Plus, Search, Wrench, X, type LucideIcon } from 'lucide-react'
import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import type { Asset, Project, WorkOrder } from '../types/tfms'
import { ReferenceValue } from '../components/ReferenceValue'
import { StatusBadge } from '../components/StatusBadge'

export function MaintenancePage({workOrders,assets,projects,onSave}:{workOrders:WorkOrder[];assets:Asset[];projects:Project[];onSave?:(w:WorkOrder)=>Promise<void>|void}) {
  const [query,setQuery]=useState(''); const [editing,setEditing]=useState<WorkOrder|null>(null); const [completing,setCompleting]=useState<WorkOrder|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const rows=useMemo(()=>workOrders.filter(w=>{const a=assets.find(x=>x.id===w.asset);const q=query.toLowerCase();return !q||[a?.code,a?.name,w.desc,w.type,w.status].join(' ').toLowerCase().includes(q)}),[workOrders,assets,query])
  const open=workOrders.filter(w=>!['مكتمل','ملغى'].includes(w.status)).length
  const waiting=workOrders.filter(w=>['بانتظار الاعتماد','بانتظار قطع غيار'].includes(w.status)).length
  const completed=workOrders.filter(w=>w.status==='مكتمل').length
  const high=workOrders.filter(w=>['عالية','عاجلة','حرجة'].includes(w.prio)&&!['مكتمل','ملغى'].includes(w.status)).length
  async function saveEdit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing||!onSave||busy)return;setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);await onSave({...editing,asset:String(fd.get('asset')||''),proj:String(fd.get('proj')||''),type:String(fd.get('type')||''),desc:String(fd.get('desc')||''),opened:String(fd.get('opened')||''),prio:String(fd.get('prio')||'عادية'),vendor:String(fd.get('vendor')||''),techs:String(fd.get('techs')||''),planId:String(fd.get('planId')||''),estimatedCost:Number(fd.get('estimatedCost')||0),cause:String(fd.get('cause')||''),materials:String(fd.get('materials')||''),warranty:String(fd.get('warranty')||''),approvalNotes:String(fd.get('approvalNotes')||'')});setEditing(null)}catch(err){setError(err instanceof Error?err.message:'تعذر حفظ أمر العمل.')}finally{setBusy(false)}}
  async function transition(w:WorkOrder,to:string){if(!onSave||busy)return;if(to==='مكتمل'){setCompleting(w);return}if(to==='مرفوض'&&!window.confirm('هل تريد رفض أمر العمل؟'))return;setBusy(true);setError('');try{await onSave({...w,status:to})}catch(err){setError(err instanceof Error?err.message:'تعذر تحديث حالة أمر العمل.')}finally{setBusy(false)}}
  async function markParts(w:WorkOrder){if(!onSave||busy)return;setBusy(true);setError('');try{await onSave({...w,status:'بانتظار قطع غيار'})}catch(err){setError(err instanceof Error?err.message:'تعذر تحديث حالة أمر العمل.')}finally{setBusy(false)}}
  async function complete(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!completing||!onSave||busy)return;setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);const labor=Number(fd.get('laborCost')||0),parts=Number(fd.get('partsCost')||0),vendor=Number(fd.get('vendorCost')||0),down=Number(fd.get('downHrs')||0);if([labor,parts,vendor,down].some(n=>!Number.isFinite(n)||n<0))throw new Error('التكاليف ومدة التوقف يجب أن تكون أرقامًا غير سالبة.');await onSave({...completing,laborCost:labor,partsCost:parts,vendorCost:vendor,downHrs:down,completed:String(fd.get('completed')||new Date().toISOString().slice(0,10)),results:String(fd.get('results')||''),status:'مكتمل'});setCompleting(null)}catch(err){setError(err instanceof Error?err.message:'تعذر إنجاز أمر العمل.')}finally{setBusy(false)}}
  return <div><div className="page-head"><div><h1>أوامر العمل والصيانة</h1><p>الدورة: اعتماد الفتح ← بدء التنفيذ ← بانتظار قطع الغيار عند الحاجة ← الإنجاز والتكلفة.</p></div>{onSave&&<button className="primary-button" onClick={()=>setEditing({id:`WO-${Date.now()}`,asset:assets[0]?.id??'',proj:projects[0]?.id??'',type:'صيانة دورية',desc:'',opened:new Date().toISOString().slice(0,10),prio:'عادية',status:'مفتوح',laborCost:0,partsCost:0,vendorCost:0,estimatedCost:0,planId:'',cause:'',materials:'',warranty:'',approvalNotes:''})}><Plus size={16}/> أمر عمل جديد</button>}</div>{error&&<div className="global-error" role="alert">{error}</div>}
    <div className="metric-grid compact"><Stat icon={Wrench} label="أوامر مفتوحة" value={open}/><Stat icon={Clock3} label="بانتظار إجراء" value={waiting}/><Stat icon={CheckCircle2} label="مكتملة" value={completed}/><Stat icon={AlertCircle} label="أولوية عالية" value={high}/></div>
    <section className="panel"><div className="toolbar"><div className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث في أوامر العمل..."/></div><span className="toolbar-count">{rows.length} أمر</span></div><div className="table-wrap"><table><thead><tr><th>الأصل</th><th>نوع العمل</th><th>الوصف</th><th>المشروع</th><th>الأولوية</th><th>الحالة</th><th>التاريخ</th><th>التكلفة</th><th>إجراءات</th></tr></thead><tbody>{rows.map(w=><tr key={w.id}><td><ReferenceValue field="asset" value={w.asset} lookups={{assets,projects}}/></td><td>{w.type}</td><td>{w.desc||'—'}</td><td><ReferenceValue field="proj" value={w.proj} lookups={{projects}}/></td><td>{w.prio}</td><td><StatusBadge>{w.status}</StatusBadge></td><td>{fmtDate(w.opened)}</td><td>{fmt(Number(w.laborCost||0)+Number(w.partsCost||0)+Number(w.vendorCost||0))} ج.م</td><td><div className="row-actions">{w.status==='بانتظار الاعتماد'&&<button type="button" className="workflow-button primary" onClick={()=>transition(w,'مفتوح')} disabled={busy}><CheckCircle2 size={13}/> اعتماد</button>}{w.status==='مفتوح'&&<button type="button" className="workflow-button primary" onClick={()=>transition(w,'قيد التنفيذ')} disabled={busy}><Wrench size={13}/> بدء التنفيذ</button>}{(w.status==='قيد التنفيذ'||w.status==='بانتظار قطع غيار')&&<><button type="button" className="workflow-button secondary" onClick={()=>markParts(w)} disabled={busy}>قطع غيار</button><button type="button" className="workflow-button primary" onClick={()=>transition(w,'مكتمل')} disabled={busy}><CheckCircle2 size={13}/> إنجاز</button></>}{(w.status==='مفتوح'||w.status==='بانتظار الاعتماد')&&<button type="button" className="icon-button" title="تعديل أمر العمل" onClick={()=>setEditing({...w})} aria-label="تعديل أمر العمل"><Pencil size={14}/></button>}</div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد أوامر عمل مطابقة.</div>}</div></section>
    {editing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setEditing(null)}><form className="modal-card wide form-modal-premium" onSubmit={saveEdit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{workOrders.some(w=>w.id===editing.id)?'تعديل أمر العمل':'أمر عمل جديد'}</h2><div className="entity-subtitle"><span>{String(editing.desc??'أمر عمل')}</span>{editing.id&&<b className="entity-code">{editing.id}</b>}</div><p>الحالة تُدار من دورة الاعتماد وليس من الحقل.</p></div><button type="button" className="icon-button" onClick={()=>setEditing(null)} aria-label="إغلاق"><X size={18}/></button></div><div className="form-sections"><FormBlock title="فتح أمر العمل"><Select name="asset" label="الأصل" value={editing.asset} options={assets.map(x=>({v:x.id,l:`${x.name} — ${x.code}`}))}/><Select name="proj" label="المشروع" value={editing.proj??''} options={[{v:'',l:'المقر / بدون مشروع'},...projects.map(x=>({v:x.id,l:`${x.name} — ${x.code}`}))]}/><Input name="type" label="نوع العمل" value={editing.type}/><Input name="opened" label="تاريخ الفتح" type="date" value={editing.opened}/><Select name="prio" label="الأولوية" value={editing.prio} options={['عادية','متوسطة','عالية','عاجلة','حرجة'].map(v=>({v,l:v}))}/><Input name="estimatedCost" label="التكلفة التقديرية" type="number" value={String(editing.estimatedCost??0)}/></FormBlock><FormBlock title="التنفيذ"><Input name="vendor" label="المورد / الورشة" value={editing.vendor??''}/><Input name="techs" label="الفنيون / الطاقم" value={editing.techs??''}/><Input name="planId" label="مرجع خطة الصيانة" value={editing.planId??''}/><Input name="warranty" label="الضمان / شروط ما بعد الإصلاح" value={editing.warranty??''}/><label className="field field-full"><span>وصف العمل</span><textarea name="desc" defaultValue={editing.desc} rows={4} placeholder="وصف العطل أو العمل المطلوب والخطوات الأساسية..."/></label></FormBlock><FormBlock title="التشخيص والمواد"><label className="field field-full"><span>سبب العطل / التشخيص</span><textarea name="cause" defaultValue={editing.cause??''} rows={3}/></label><label className="field field-full"><span>المواد وقطع الغيار المتوقعة</span><textarea name="materials" defaultValue={editing.materials??''} rows={3}/></label><label className="field field-full"><span>ملاحظات الاعتماد</span><textarea name="approvalNotes" defaultValue={editing.approvalNotes??''} rows={3}/></label></FormBlock></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ الأمر'}</button></div></form></div>}
    {completing&&<div className="modal-backdrop" onMouseDown={()=>!busy&&setCompleting(null)}><form className="modal-card wide form-modal-premium" onSubmit={complete} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>إنجاز أمر العمل</h2><p className="modal-reference"><span>الأصل:</span> <strong>{assetName(assets,String(completing.asset))}</strong> <b className="entity-code">{completing.id}</b></p><p>تسجيل التكلفة ومدة التوقف ونتائج الفحص قبل الإغلاق.</p></div><button type="button" className="icon-button" onClick={()=>setCompleting(null)} aria-label="إغلاق"><X size={18}/></button></div><div className="form-grid"><Input name="laborCost" label="تكلفة العمالة ج.م" type="number" value={String(completing.laborCost??0)}/><Input name="partsCost" label="قطع الغيار ج.م" type="number" value={String(completing.partsCost??0)}/><Input name="vendorCost" label="المورد الخارجي ج.م" type="number" value={String(completing.vendorCost??0)}/><Input name="downHrs" label="مدة التوقف ساعة" type="number" value={String(completing.downHrs??0)}/><Input name="completed" label="تاريخ الإنجاز" type="date" value={completing.completed??new Date().toISOString().slice(0,10)}/><label className="field"><span>نتائج الفحص والاختبار</span><textarea name="results" defaultValue={completing.results??''} rows={4}/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setCompleting(null)}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الإغلاق...':'إنجاز واعتماد التكاليف'}</button></div></form></div>}
  </div>
}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:{v:string;l:string}[]}){return <label className="field"><span>{label}</span><select name={name} defaultValue={value}>{options.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select></label>}
function Input({name,label,value,type='text'}:{name:string;label:string;value:string;type?:string}){return <label className="field"><span>{label}</span><input name={name} type={type} defaultValue={value} min={type==='number'?0:undefined} step={type==='number'?'any':undefined}/></label>}
function FormBlock({title,children}:{title:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>بيانات مطلوبة لمتابعة أمر العمل</span></div><div className="form-grid">{children}</div></section>}
function Stat({icon:Icon,label,value}:{icon:LucideIcon;label:string;value:number}){return <div className="metric-card"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong></div></div>}
const assetCode=(assets:Asset[],id:string)=>assets.find(a=>a.id===id)?.code??id
const assetName=(assets:Asset[],id:string)=>assets.find(a=>a.id===id)?.name??'—'
const fmt=(n:number|undefined)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:1}).format(Number(n||0))
const fmtDate=(v?:string)=>v?new Intl.DateTimeFormat('ar-EG',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v)):'—'
