import { useEffect, useState, type ReactNode } from 'react'
import { Save, Settings2 } from 'lucide-react'
import type { Repository } from '../core/repository/types'
import type { User } from '../types/tfms'
import { CURRENCY_OPTIONS, normalizeCurrencyCode } from '../features/settings'
import { Button, Card, PageHeader } from '../components/ui'

type Settings={company_name:string;group_name:string;currency_code:string;vat:number;diesel:number;petrol:number;alert_days:number;alert_km:number;alert_hours:number}
const empty:Settings={company_name:'',group_name:'',currency_code:'EGP',vat:0,diesel:0,petrol:0,alert_days:30,alert_km:1500,alert_hours:80}

/** Organization settings editor. Currency is persisted centrally and defaults to EGP. */
export function SettingsPage({user,repository,onSaved}:{user:User;repository:Repository;onSaved?:(settings:Settings)=>void}){
 const [s,setS]=useState<Settings>(empty);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const [loadError,setLoadError]=useState('');const [loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;setLoading(true);setLoadError('');repository.getSettings().then(v=>{if(active)setS({...empty,...v,currency_code:normalizeCurrencyCode(String(v.currency_code??'EGP'))})}).catch(e=>{if(active)setLoadError(e instanceof Error?e.message:'تعذر تحميل الإعدادات. حاول تحديث الصفحة.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[repository])
 const can=user.role==='admin'
 async function save(){if(!can||busy)return;setMsg('');const numeric:[keyof Settings,string][]=[['vat','ضريبة القيمة المضافة'],['diesel','سعر الديزل'],['petrol','سعر البنزين'],['alert_days','مدة التنبيه بالأيام'],['alert_km','مسافة التنبيه'],['alert_hours','ساعات التنبيه']];for(const [key,label] of numeric){const n=s[key];if(typeof n!=='number'||!Number.isFinite(n)||n<0){setMsg(`تحقق من قيمة ${label}؛ يجب أن تكون رقمًا غير سالب.`);return}}setBusy(true);try{await repository.saveSettings({...s,currency_code:normalizeCurrencyCode(s.currency_code)});onSaved?.(s);setMsg('تم حفظ الإعدادات بنجاح.')}catch(e){setMsg(e instanceof Error?e.message:'تعذر حفظ الإعدادات. حاول مرة أخرى.')}finally{setBusy(false)}}
 const update=(k:keyof Settings,v:string)=>setS({...s,[k]:['vat','diesel','petrol','alert_days','alert_km','alert_hours'].includes(k)?Number(v):k==='currency_code'?normalizeCurrencyCode(v):v})
 return <div className="space-y-6"><PageHeader title="الإعدادات العامة" description="بيانات المؤسسة والعملة والأسعار وقواعد التنبيه الافتراضية للنظام." />{loading&&<div className="global-error" role="status">جارٍ تحميل الإعدادات...</div>}{loadError&&<div className="global-error" role="alert">{loadError}</div>}<Card><div className="section-title"><div className="section-title-icon"><Settings2 size={16}/></div><div><strong>إعدادات التشغيل</strong><small>{can?'يمكنك تعديل القيم ثم حفظها.':'للقراءة فقط — يلزم مدير النظام للتعديل.'}</small></div></div><div className="form-sections"><FormBlock title="هوية المؤسسة" hint="البيانات التي تظهر في التقارير والمستندات"><Field label="اسم الشركة" value={s.company_name} onChange={v=>update('company_name',v)} disabled={!can}/><Field label="المجموعة" value={s.group_name} onChange={v=>update('group_name',v)} disabled={!can}/></FormBlock><FormBlock title="العملة والبيانات المالية" hint="العملة الافتراضية لكل القيم المالية المعروضة في النظام"><label className="field"><span>العملة الافتراضية</span><select disabled={!can} value={s.currency_code} onChange={e=>update('currency_code',e.target.value)}>{CURRENCY_OPTIONS.map(option=><option key={option.code} value={option.code}>{option.label}</option>)}</select></label><Field label="ضريبة القيمة المضافة %" type="number" value={String(s.vat)} onChange={v=>update('vat',v)} disabled={!can}/><Field label="سعر الديزل" type="number" value={String(s.diesel)} onChange={v=>update('diesel',v)} disabled={!can}/><Field label="سعر البنزين" type="number" value={String(s.petrol)} onChange={v=>update('petrol',v)} disabled={!can}/></FormBlock><FormBlock title="قواعد التنبيه" hint="تستخدم لإظهار الاستحقاقات قبل موعدها"><Field label="التنبيه قبل الانتهاء (يوم)" type="number" value={String(s.alert_days)} onChange={v=>update('alert_days',v)} disabled={!can}/><Field label="تنبيه العداد (كم)" type="number" value={String(s.alert_km)} onChange={v=>update('alert_km',v)} disabled={!can}/><Field label="تنبيه ساعات التشغيل" type="number" value={String(s.alert_hours)} onChange={v=>update('alert_hours',v)} disabled={!can}/></FormBlock></div><div className="modal-actions">{msg&&<span className="form-success">{msg}</span>} {can&&<Button icon={<Save size={15}/>} disabled={busy||loading||!!loadError} loading={busy} onClick={save}>{busy?'جارٍ الحفظ...':'حفظ الإعدادات'}</Button>}</div></Card></div>
}
function FormBlock({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>{hint}</span></div><div className="form-grid">{children}</div></section>}
function Field({label,value,onChange,type='text',disabled}:{label:string;value:string;onChange:(v:string)=>void;type?:string;disabled:boolean}){return <label className="field"><span>{label}</span><input disabled={disabled} type={type} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export type { Settings }
