import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { ArrowRight, Check, FileText, PenLine, RefreshCw, Upload, X } from 'lucide-react'
import { Button } from '../components/ui/Button'
import { WorkflowActionCard, WorkflowTimeline } from '../shared/ui'
import { Card } from '../components/ui/Card'
import { PageHeader } from '../components/ui/PageHeader'
import { StatusBadge } from '../components/ui/StatusBadge'
import { tripCostsService, tripPermitsService, tripsService } from '../features/trips/service'
import { PERMIT_TYPE_LABELS, TRIP_STATUS_LABELS, TRIP_TYPE_LABELS, TRIP_STATUS_TRANSITIONS, type Trip, type TripPermit, type TripCost } from '../features/trips/types'
import { requireSupabase } from '../services/supabase'
import { TRANSPORTATION_WORKFLOW, transportationStageForStatus } from '../shared/workflows/workflowDefinitions'
import type { Asset, Driver, Project } from '../types/tfms'

import { APP_LOCALE } from '../shared/formatters/locale'
export function TripDetailPage({id,assets,drivers,projects,onBack,currencyCode='EGP'}:{id:string;assets:Asset[];drivers:Driver[];projects:Project[];onBack:()=>void;currencyCode?:string}){
 const [trip,setTrip]=useState<Trip|null>(null),[permits,setPermits]=useState<TripPermit[]>([]),[costs,setCosts]=useState<TripCost[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[signing,setSigning]=useState<TripPermit|null>(null),[invoiceId,setInvoiceId]=useState('')
 const money=(v:number)=>new Intl.NumberFormat(APP_LOCALE,{style:'currency',currency:currencyCode,maximumFractionDigits:2}).format(v)
 const load=async()=>{try{const [t,p,c]=await Promise.all([tripsService.getById(id),tripPermitsService.listByTrip(id),tripCostsService.listByTrip(id)]);setTrip(t);setPermits(p);setCosts(c);setInvoiceId(t.invoice_id??'');setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل تفاصيل عملية النقل.')}}
 useEffect(()=>{void load()},[id])
 const transition=async(next:Trip['status'])=>{setBusy(true);try{await tripsService.updateStatus(id,next);await load()}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث الحالة.')}finally{setBusy(false)}}
 const issuePermit=async(type:'delivery'|'receipt')=>{setBusy(true);try{await tripPermitsService.create({trip_id:id,permit_type:type,signed_at:null,signed_by_name:null,signed_by_role:null,signature_url:null,attachment_urls:[],receipt_condition:null,received_quantity:null,discrepancy_notes:null,notes:null});await load()}catch(e){setError(e instanceof Error?e.message:'تعذر إصدار الإذن.')}finally{setBusy(false)}}
 const linkInvoice=async()=>{if(!invoiceId.trim())return;setBusy(true);try{await tripsService.update(id,{invoice_id:invoiceId.trim(),status:'invoiced'});await load()}catch(e){setError(e instanceof Error?e.message:'تعذر ربط الفاتورة.')}finally{setBusy(false)}}
 const signPermit=async(args:{name:string;role:string;signatureBlob:Blob;attachment?:File;condition?:TripPermit['receipt_condition'];quantity?:number;notes?:string})=>{if(!signing)return;setBusy(true);try{const db=requireSupabase();const signaturePath=`${trip?.id}/${signing.id}/signature-${Date.now()}.png`;const {error:uploadError}=await db.storage.from('trip-permits').upload(signaturePath,args.signatureBlob,{contentType:'image/png',upsert:true});if(uploadError)throw uploadError;let attachmentUrls=signing.attachment_urls??[];if(args.attachment){const path=`${trip?.id}/${signing.id}/${Date.now()}-${args.attachment.name.replace(/[^\w.\-\u0600-\u06ff]/g,'_')}`;const {error:fileError}=await db.storage.from('trip-permits').upload(path,args.attachment,{upsert:true});if(fileError)throw fileError;attachmentUrls=[...attachmentUrls,path]}await tripPermitsService.sign(signing.id,{signed_by_name:args.name.trim(),signed_by_role:args.role.trim(),signature_url:signaturePath,receipt_condition:args.condition,received_quantity:args.quantity??null,discrepancy_notes:null});if(attachmentUrls.length!==signing.attachment_urls.length)await db.from('trip_permits').update({attachment_urls:attachmentUrls,notes:args.notes?.trim()||signing.notes}).eq('id',signing.id);setSigning(null);await load()}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ توقيع الإذن والمرفقات.')}finally{setBusy(false)}}
 if(!trip)return <div className="space-y-4" dir="rtl"><Button variant="secondary" onClick={onBack}><ArrowRight size={16}/> رجوع للنقل</Button>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<Card>{error?'تعذر عرض العملية.':'جارٍ تحميل بيانات النقل…'}</Card></div>
 const next=TRIP_STATUS_TRANSITIONS[trip.status][0]
 const label=(value:string|null,items:{id:string;name:string}[])=>items.find(x=>x.id===value)?.name??value??'—'
 const totalCost=costs.reduce((sum,c)=>sum+Number(c.amount),0),charge=Number(trip.total_charge??0)
 return <div className="space-y-6" dir="rtl"><PageHeader title={trip.trip_number} description={`${TRIP_TYPE_LABELS[trip.trip_type]} • ${trip.cargo_description}`} action={<div className="flex gap-2"><Button variant="secondary" onClick={onBack}><ArrowRight size={16}/> رجوع</Button><Button variant="secondary" onClick={()=>void load()}><RefreshCw size={16}/> تحديث</Button></div>}/>{error&&<div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</div>}
 <WorkflowTimeline
   label={TRANSPORTATION_WORKFLOW.label}
   stages={TRANSPORTATION_WORKFLOW.stages}
   currentStageId={transportationStageForStatus(trip.status)}
   currentStatus={TRIP_STATUS_LABELS[trip.status]}
   cancelled={trip.status==='cancelled'}
   busy={busy}
   nextActions={next ? [{label:`تقدم إلى ${TRIP_STATUS_LABELS[next]}`,onClick:()=>void transition(next),tone:'primary' as const}] : []}
  />
  <WorkflowActionCard
   title={trip.status==='received' && trip.is_billable && !trip.invoice_id ? 'اربط الفاتورة الفعلية' : trip.status==='paid' ? 'الرحلة مكتملة ماليًا' : 'الإجراء التالي في الرحلة'}
   description={trip.status==='received' && trip.is_billable && !trip.invoice_id ? 'تم الاستلام؛ اربط رقم الفاتورة المسجلة فعليًا قبل نقل الرحلة إلى مرحلة الفوترة.' : trip.status==='paid' ? 'تم الاستلام والفوترة والسداد؛ حافظ على سجل المستندات والتكاليف كمرجع تاريخي.' : 'نفّذ الإجراء الظاهر مع إبقاء المستندات والتسليم والتكاليف داخل نفس بطاقة الرحلة.'}
   status={<StatusBadge tone={trip.status==='cancelled'?'red':trip.status==='paid'?'emerald':'blue'}>{TRIP_STATUS_LABELS[trip.status]}</StatusBadge>}
   action={next ? <Button loading={busy} onClick={()=>void transition(next)}>تغيير الحالة إلى: {TRIP_STATUS_LABELS[next]}</Button> : undefined}
   secondary={trip.status==='received' && trip.is_billable && !trip.invoice_id ? <button type="button" className="secondary-button" onClick={()=>document.querySelector<HTMLInputElement>('input[placeholder^="أدخل رقم الفاتورة"]')?.focus()}>الانتقال للفوترة</button> : undefined}
  />
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['الشاحنة',label(trip.truck_asset_id,assets)],['السائق',label(trip.driver_id,drivers)],['مشروع المصدر',label(trip.from_project_id,projects)],['مشروع الاستقبال',label(trip.to_project_id,projects)],['المسار',`${trip.from_location||'—'} ← ${trip.to_location||'—'}`],['الحمولة',`${trip.cargo_description}${trip.cargo_quantity!=null?` (${trip.cargo_quantity} ${trip.cargo_unit??''})`:''}`],['قيمة النقل',money(charge)],['التكاليف المسجلة',money(totalCost)]].map(([k,v])=><Card key={String(k)}><p className="text-sm text-slate-500">{k}</p><p className="mt-2 break-words text-base font-semibold text-slate-900">{v}</p></Card>)}</div>
 <Card><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">أذونات التسليم والاستلام</h2><p className="text-sm text-slate-500">إصدار الإذن ثم تسجيل التوقيع والمرفقات من نفس بطاقة النقل.</p></div><FileText size={20} className="text-slate-400"/></div><div className="grid gap-3 md:grid-cols-2">{(['delivery','receipt'] as const).map(type=>{const permit=permits.find(p=>p.permit_type===type);return <div key={type} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{PERMIT_TYPE_LABELS[type]}</h3>{permit&&<StatusBadge tone={permit.signed_at?'emerald':'amber'}>{permit.signed_at?'موقّع':'بانتظار التوقيع'}</StatusBadge>}</div>{permit?<div className="mt-3 space-y-2 text-sm"><p>رقم الإذن: <strong>{permit.permit_number}</strong></p>{permit.signed_by_name&&<p>الموقّع: <strong>{permit.signed_by_name}</strong> — {permit.signed_by_role}</p>}{permit.received_quantity!=null&&<p>الكمية المستلمة: <strong>{permit.received_quantity}</strong></p>}{permit.attachment_urls?.length>0&&<p className="text-emerald-700">تم إرفاق {permit.attachment_urls.length} مستند.</p>} {!permit.signed_at&&<Button size="sm" variant="secondary" icon={<PenLine size={15}/>} onClick={()=>setSigning(permit)} disabled={busy}>توقيع واستكمال الإذن</Button>}</div>:<div className="mt-3"><p className="mb-3 text-sm text-slate-500">لم يصدر الإذن بعد.</p><Button size="sm" variant="secondary" icon={<FileText size={15}/>} disabled={busy||['invoiced','paid','cancelled'].includes(trip.status)} onClick={()=>void issuePermit(type)}>إصدار الإذن</Button></div>}</div>})}</div></Card>
 <Card><div className="mb-4 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 className="text-lg font-bold">الفوترة وربط المستند المالي</h2><p className="text-sm text-slate-500">بعد الاستلام، اربط رقم الفاتورة الفعلية ليتم نقل العملية إلى «مفوترة».</p></div>{trip.invoice_id&&<StatusBadge tone="blue">فاتورة: {trip.invoice_id}</StatusBadge>}</div>{trip.status==='received'&&trip.is_billable&&!trip.invoice_id&&<div className="flex flex-col gap-3 sm:flex-row"><label className="field flex-1"><span>رقم الفاتورة</span><input value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} placeholder="أدخل رقم الفاتورة الموجودة في النظام"/></label><Button onClick={()=>void linkInvoice()} disabled={!invoiceId.trim()||busy} icon={<Check size={15}/>}>ربط الفاتورة واعتماد الفوترة</Button></div>}</Card>
 <Card><h2 className="mb-4 text-lg font-bold">تفاصيل التكاليف</h2>{costs.length?<div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead className="bg-slate-50 text-slate-700"><tr><th className="p-3">التاريخ</th><th className="p-3">الفئة</th><th className="p-3">الوصف</th><th className="p-3">المبلغ</th></tr></thead><tbody className="divide-y divide-slate-100">{costs.map(c=><tr key={c.id}><td className="p-3">{c.cost_date}</td><td className="p-3">{c.cost_category}</td><td className="p-3">{c.description||'—'}</td><td className="p-3">{money(Number(c.amount))}</td></tr>)}</tbody></table></div>:<p className="text-sm text-slate-500">لا توجد تكاليف مسجلة لهذه العملية.</p>}<div className="mt-4 flex justify-between border-t border-slate-100 pt-4 font-semibold"><span>هامش تقديري (قيمة النقل − التكاليف)</span><span>{money(charge-totalCost)}</span></div></Card>
 {signing&&<SignatureModal permit={signing} busy={busy} onClose={()=>!busy&&setSigning(null)} onSave={signPermit}/>}</div>
}

function SignatureModal({permit,busy,onClose,onSave}:{permit:TripPermit;busy:boolean;onClose:()=>void;onSave:(args:{name:string;role:string;signatureBlob:Blob;attachment?:File;condition?:TripPermit['receipt_condition'];quantity?:number;notes?:string})=>Promise<void>}){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),[name,setName]=useState(''),[role,setRole]=useState(''),[condition,setCondition]=useState<TripPermit['receipt_condition']>(permit.receipt_condition),[quantity,setQuantity]=useState(permit.received_quantity?.toString()??''),[file,setFile]=useState<File>(),[drawing,setDrawing]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;canvas.width=760;canvas.height=220;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.lineWidth=2.5;ctx.lineCap='round';ctx.strokeStyle='#0f172a'},[])
 const point=(e:PointerEvent<HTMLCanvasElement>)=>{const canvas=canvasRef.current;if(!canvas)return;const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
 const start=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);if(!p)return;setDrawing(true);canvasRef.current?.setPointerCapture(e.pointerId);const ctx=canvasRef.current?.getContext('2d');ctx?.beginPath();ctx?.moveTo(p.x,p.y)}
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{if(!drawing)return;const p=point(e);if(!p)return;const ctx=canvasRef.current?.getContext('2d');ctx?.lineTo(p.x,p.y);ctx?.stroke()}
 const clear=()=>{const c=canvasRef.current;if(!c)return;c.getContext('2d')?.clearRect(0,0,c.width,c.height)}
 const submit=async()=>{setError('');if(name.trim().length<2)return setError('اسم الموقّع مطلوب.');if(role.trim().length<2)return setError('صفة الموقّع مطلوبة.');const c=canvasRef.current;if(!c)return;const blob=await new Promise<Blob|null>(resolve=>c.toBlob(resolve,'image/png'));if(!blob)return setError('تعذر تجهيز التوقيع.');await onSave({name,role,signatureBlob:blob,attachment:file,condition,quantity:quantity?Number(quantity):undefined})}
 return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal-card wide form-modal-premium" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>استكمال {PERMIT_TYPE_LABELS[permit.permit_type]}</h2><p>توقيع يدوي ومرفق اختياري.</p></div><button className="icon-button" onClick={onClose} type="button" aria-label="إغلاق"><X size={18}/></button></div><div className="modal-scroll-body"><div className="form-grid"><label className="field"><span>اسم الموقّع *</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>صفة الموقّع *</span><input value={role} onChange={e=>setRole(e.target.value)}/></label>{permit.permit_type==='receipt'&&<><label className="field"><span>الحالة</span><select value={condition??''} onChange={e=>setCondition((e.target.value||null) as TripPermit['receipt_condition'])}><option value="">غير محدد</option><option value="سليم">سليم</option><option value="تالف">تالف</option><option value="ناقص">ناقص</option></select></label><label className="field"><span>الكمية المستلمة</span><input type="number" min="0" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></>}</div><div className="mt-4"><div className="mb-2 flex items-center justify-between"><strong>منطقة التوقيع</strong><button type="button" className="secondary-button" onClick={clear}>مسح</button></div><canvas ref={canvasRef} className="w-full touch-none rounded-xl border border-dashed border-slate-300 bg-white" onPointerDown={start} onPointerMove={move} onPointerUp={()=>setDrawing(false)} onPointerLeave={()=>setDrawing(false)}/></div><label className="mt-4 flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm"><Upload size={16}/><span className="flex-1">إرفاق صورة / مستند</span><input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0])}/></label>{file&&<p className="mt-2 text-xs text-slate-500">{file.name}</p>}{error&&<div className="form-error mt-3">{error}</div>}</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose} disabled={busy}>إلغاء</button><button type="button" className="primary-button" onClick={()=>void submit()} disabled={busy}><PenLine size={15}/>{busy?'جارٍ الحفظ...':'حفظ التوقيع والإذن'}</button></div></div></div>
}
