import { useEffect, useState, type ReactNode } from 'react'
import { Pencil, ShieldCheck, UserRound, X } from 'lucide-react'
import { ROLE_LABELS } from '../config/app'
import type { Role, User } from '../types/tfms'
import type { TfmsRepository } from '../services/repository'

export function UsersPage({user,repository}:{user:User;repository:TfmsRepository}){
  const [users,setUsers]=useState<User[]>([]);const [editing,setEditing]=useState<User|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('')
  const canView=user.role==='admin'||user.role==='mgmt'; const can=user.role==='admin'
  useEffect(()=>{if(canView){repository.listUsers().then(rows=>{setUsers(rows);setError('')}).catch(e=>{setUsers(repository.getDemoDb().users);setError(e instanceof Error?`تعذر تحميل المستخدمين من قاعدة البيانات: ${e.message}`:'تعذر تحميل المستخدمين؛ يتم عرض بيانات العرض المحلية.')})}},[repository,canView])
  if(!canView) return <div className="placeholder-panel panel"><div className="placeholder-icon"><ShieldCheck size={24}/></div><h2>الوصول إلى المستخدمين مقيد</h2><p>إدارة المستخدمين والصلاحيات متاحة لمدير النظام، مع عرض المستخدمين للإدارة العليا.</p></div>
  async function save(){if(!editing||!can)return;setBusy(true);setError('');setNotice('');try{const saved=await repository.updateUserProfile(editing.id,{full_name:editing.name.trim(),role:editing.role,active:editing.active!==false});const next=users.map(x=>x.id===saved.id?saved:x);setUsers(next);setEditing(null);setNotice('تم تحديث بيانات المستخدم وصلاحياته بنجاح.')}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ التعديلات. حاول مرة أخرى.')}finally{setBusy(false)}}
  return <div><div className="page-head"><div><h1>المستخدمون والصلاحيات</h1><p>إدارة أدوار المستخدمين وحالة الحسابات. إنشاء حساب المصادقة يتم من لوحة مزود الهوية.</p></div></div>
    {error&&<div className="global-error" role="alert">{error}</div>}{notice&&<div className="form-success" role="status">{notice}</div>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>المستخدم</th><th>الدور</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><div className="table-main"><span className="asset-chip"><UserRound size={15}/></span><div><strong>{x.name}</strong><small>{x.username}</small></div></div></td><td><span className="badge blue">{ROLE_LABELS[x.role as Role]}</span></td><td><span className={`badge ${x.active===false?'gray':'green'}`}>{x.active===false?'موقوف':'نشط'}</span></td><td>{can&&<button className="icon-button" title="تعديل" onClick={()=>setEditing({...x})}><Pencil size={15}/></button>}</td></tr>)}</tbody></table></div></section>
    {editing&&<div className="modal-backdrop" onMouseDown={()=>setEditing(null)}><div className="modal-card wide form-modal-premium" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>تعديل صلاحية المستخدم</h2><p>{editing.username}</p></div><button className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-sections"><FormBlock title="بيانات المستخدم" hint="معلومات الحساب والصلاحية"><label className="field"><span>اسم المستخدم</span><input value={editing.username} readOnly/></label><label className="field"><span>الاسم الظاهر</span><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="field"><span>الدور</span><select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value as Role})}>{Object.entries(ROLE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>حالة الحساب</span><select value={editing.active===false?'false':'true'} onChange={e=>setEditing({...editing,active:e.target.value==='true'})}><option value="true">نشط</option><option value="false">موقوف</option></select></label></FormBlock></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setEditing(null)}>إلغاء</button><button className="primary-button" disabled={busy||!editing.name.trim()} onClick={save}><ShieldCheck size={15}/>{busy?'جارٍ الحفظ...':'حفظ الصلاحية'}</button></div></div></div>}
  </div>
}

function FormBlock({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="form-section"><div className="form-section-head"><strong>{title}</strong><span>{hint}</span></div><div className="form-grid">{children}</div></section>}
