export type FieldType = 'text' | 'date' | 'number' | 'textarea' | 'select'
export type ModuleField = {
  key:string; label:string; type?:FieldType; options?:string[]; required?:boolean
  section?:string; help?:string; placeholder?:string; full?:boolean
}
export type WorkflowAction = {
  key:string; label:string; from:string[]; to:string; roles:string[]
  tone?:'primary'|'secondary'|'danger'; kind?:'status'|'navigate'; route?:string
}
export type ModuleWorkflow = { statusField?:string; createStatus?:string; actions:WorkflowAction[] }
export type ModuleConfig = { title:string; description:string; formIntro?:string; fields:ModuleField[]; display?:string[]; readOnly?:boolean; workflow?:ModuleWorkflow }

const base = (key:string,label:string,extra:Partial<ModuleField>={}) => ({key,label,...extra})
const commonStatus = ['مسودة','مقدمة','معتمد','مرفوض','قيد التنفيذ','مكتمل','ملغى','نشط','غير نشط']

export const MODULE_CONFIG: Record<string, ModuleConfig> = {
  requests:{title:'طلبات المعدات',description:'الدورة: طلب الموقع ← اعتماد مدير المشروع ← مراجعة إدارة النقل ← التخصيص ← التشغيل.',formIntro:'سجل الاحتياج التشغيلي كاملًا حتى تستطيع الإدارة مراجعة الطلب قبل التخصيص.',workflow:{createStatus:'مسودة',actions:[
    {key:'submit',label:'تقديم',from:['مسودة','معاد للتعديل'],to:'بانتظار اعتماد مدير المشروع',roles:['admin','fleet','pm','eng'],tone:'primary'},
    {key:'approve',label:'اعتماد المشروع',from:['بانتظار اعتماد مدير المشروع'],to:'معتمد من مدير المشروع',roles:['admin','fleet','pm'],tone:'primary'},
    {key:'return',label:'إعادة للتعديل',from:['بانتظار اعتماد مدير المشروع'],to:'معاد للتعديل',roles:['admin','fleet','pm'],tone:'secondary'},
    {key:'reject',label:'رفض',from:['بانتظار اعتماد مدير المشروع'],to:'مرفوض',roles:['admin','fleet','pm'],tone:'danger'},
    {key:'assign',label:'تخصيص أصل',from:['معتمد من مدير المشروع'],to:'معتمد من مدير المشروع',roles:['admin','fleet'],tone:'primary',kind:'navigate',route:'assignments/new'},
    {key:'close',label:'إنهاء الطلب',from:['قيد التنفيذ'],to:'مكتمل',roles:['admin','fleet','pm'],tone:'secondary'},
  ]},fields:[
    base('number','رقم الطلب',{required:true,section:'البيانات الأساسية',help:'رقم مستندي فريد للطلب.'}),base('date','تاريخ الطلب',{type:'date',required:true,section:'البيانات الأساسية'}),base('req','الجهة الطالبة',{required:true,section:'البيانات الأساسية'}),base('proj','المشروع',{section:'الربط والتشغيل'}),
    base('cat','فئة المعدة',{required:true,section:'تفاصيل الاحتياج'}),base('type','نوع المعدة',{required:true,section:'تفاصيل الاحتياج'}),base('qty','الكمية المطلوبة',{type:'number',required:true,section:'تفاصيل الاحتياج',help:'عدد الوحدات المطلوبة.'}),base('months','مدة التعاقد / الاستخدام (شهور)',{type:'number',section:'تفاصيل الاحتياج'}),base('need','تاريخ الاحتياج',{type:'date',required:true,section:'تفاصيل الاحتياج'}),
    base('location','موقع الاستخدام',{section:'الربط والتشغيل'}),base('work','طبيعة العمل / المهمة',{section:'تفاصيل الاحتياج'}),base('hours','الساعات المتوقعة',{type:'number',section:'تفاصيل الاحتياج'}),base('shifts','عدد الورديات',{type:'number',section:'تفاصيل الاحتياج'}),base('prio','الأولوية',{type:'select',options:['عادية','متوسطة','عالية','عاجلة'],required:true,section:'الاعتماد'}),base('status','الحالة',{type:'select',options:['مسودة','بانتظار اعتماد مدير المشروع','معاد للتعديل','معتمد من مدير المشروع','مرفوض','قيد التنفيذ','مكتمل'],section:'الاعتماد'}),
    base('reason','سبب الرفض / الإعادة',{type:'textarea',section:'الاعتماد',full:true}),base('notes','ملاحظات وتعليمات الموقع',{type:'textarea',section:'ملاحظات',full:true}),
  ]},
  assignments:{title:'تخصيصات الأصول',description:'سجل التسليم والاستلام وقراءات العدادات.',formIntro:'وثّق عملية تخصيص الأصل للمشروع أو العميل وبيانات التسليم والتحميل.',workflow:{createStatus:'ساري',actions:[{key:'end',label:'إنهاء التخصيص',from:['ساري'],to:'منتهي',roles:['admin','fleet'],tone:'danger'}]},fields:[
    base('number','رقم التخصيص',{required:true,section:'البيانات الأساسية'}),base('asset','الأصل',{required:true,section:'الربط'}),base('proj','المشروع',{required:true,section:'الربط'}),base('cust','العميل',{section:'الربط'}),base('req','رقم طلب المعدات',{section:'الربط'}),
    base('from','بداية التخصيص',{type:'date',required:true,section:'الفترة'}),base('toP','النهاية المخططة',{type:'date',section:'الفترة'}),base('toA','النهاية الفعلية',{type:'date',section:'الفترة'}),base('meterStart','عداد البداية',{type:'number',section:'العداد والتحميل'}),base('meterEnd','عداد النهاية',{type:'number',section:'العداد والتحميل'}),base('rate','سعر التحميل',{type:'number',section:'العداد والتحميل'}),base('unit','وحدة التحميل',{type:'select',options:['ساعة','يوم','كم','شهر'],section:'العداد والتحميل'}),
    base('deliveryBy','مسلم الأصل',{section:'التسليم والاستلام'}),base('receiveBy','مستلم الأصل',{section:'التسليم والاستلام'}),base('conditionStart','حالة الأصل عند التسليم',{type:'textarea',section:'التسليم والاستلام',full:true}),base('conditionEnd','حالة الأصل عند الاستلام',{type:'textarea',section:'التسليم والاستلام',full:true}),base('status','الحالة',{type:'select',options:['ساري','منتهي','ملغى'],section:'الاعتماد'}),base('notes','ملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  operations:{title:'التشغيل اليومي',description:'ساعات التشغيل والورديات وقراءات العدادات — تُستخدم القيم المعتمدة في التحميل والتقارير.',formIntro:'سجل يوم التشغيل بالتفصيل بما يتيح مراجعة العداد والإنتاج والتوقف قبل الاعتماد.',workflow:{createStatus:'مقدمة',actions:[{key:'submit',label:'تقديم',from:['مسودة','معادة'],to:'مقدمة',roles:['admin','fleet','pm','eng'],tone:'primary'},{key:'approve',label:'اعتماد',from:['مقدمة'],to:'معتمد',roles:['admin','fleet','pm'],tone:'primary'},{key:'return',label:'إعادة',from:['مقدمة'],to:'معادة',roles:['admin','fleet','pm'],tone:'secondary'}]},fields:[
    base('assetId','الأصل',{required:true,section:'البيانات الأساسية'}),base('proj','المشروع',{required:true,section:'البيانات الأساسية'}),base('date','التاريخ',{type:'date',required:true,section:'البيانات الأساسية'}),base('drv','السائق / المشغل',{section:'البيانات الأساسية'}),base('shifts','الورديات',{type:'number',section:'التشغيل'}),base('hours','ساعات التشغيل',{type:'number',section:'التشغيل'}),base('meter','قراءة العداد',{type:'number',required:true,section:'التشغيل'}),base('workType','نوع العمل',{section:'التشغيل'}),base('task','الأعمال المنفذة',{type:'textarea',section:'التشغيل',full:true}),base('down','ساعات التوقف',{type:'number',section:'التوقف'}),base('downR','سبب التوقف',{type:'textarea',section:'التوقف',full:true}),base('ap','المعتمد',{section:'الاعتماد'}),base('src','مصدر السجل',{section:'الاعتماد'}),base('status','الحالة',{type:'select',options:['مسودة','مقدمة','معتمد','معادة'],section:'الاعتماد'}),base('notes','ملاحظات التشغيل',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  trips:{title:'رحلات النقل',description:'المركبة والسائق والمسافة — تربط تكلفتها بالمشروع أو العميل.',formIntro:'سجل الرحلة بمعلومات المسار والحمولة والاستهلاك لتكون قابلة للمراجعة والتكلفة.',workflow:{createStatus:'بانتظار الاعتماد',actions:[{key:'approve',label:'اعتماد الرحلة',from:['بانتظار الاعتماد'],to:'مكتملة',roles:['admin','fleet','pm'],tone:'primary'}]},fields:[
    base('number','رقم الرحلة',{required:true,section:'البيانات الأساسية'}),base('date','التاريخ',{type:'date',required:true,section:'البيانات الأساسية'}),base('veh','المركبة',{required:true,section:'الطاقم والربط'}),base('drv','السائق',{required:true,section:'الطاقم والربط'}),base('proj','المشروع',{section:'الطاقم والربط'}),base('customer','العميل',{section:'الطاقم والربط'}),base('from','نقطة الانطلاق',{required:true,section:'المسار'}),base('to','نقطة الوصول',{required:true,section:'المسار'}),base('km','المسافة كم',{type:'number',required:true,section:'المسار'}),base('departure','وقت الانطلاق',{type:'text',section:'المسار'}),base('arrival','وقت الوصول',{type:'text',section:'المسار'}),base('load','الحمولة',{section:'الحمولة'}),base('loadQty','كمية الحمولة',{type:'number',section:'الحمولة'}),base('purpose','الغرض من الرحلة',{section:'الحمولة'}),base('status','الحالة',{type:'select',options:['مخططة','بانتظار الاعتماد','جارية','مكتملة','ملغاة'],section:'الاعتماد'}),base('notes','ملاحظات الرحلة',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  drivers:{title:'السائقون والمشغلون',description:'بيانات السائقين والمشغلين والرخص والتكليف الحالي.',formIntro:'ملف تشغيلي للسائق والمشغل مع بيانات التواصل والرخص والتكليف.',fields:[
    base('code','الكود',{required:true,section:'البيانات الأساسية'}),base('name','الاسم',{required:true,section:'البيانات الأساسية'}),base('phone','الهاتف',{section:'بيانات الاتصال'}),base('kind','التخصص',{section:'بيانات العمل'}),base('employeeNo','رقم الموظف',{section:'بيانات العمل'}),base('shift','الوردية',{section:'بيانات العمل'}),base('licNo','رقم الرخصة',{required:true,section:'الرخصة'}),base('licType','نوع الرخصة',{section:'الرخصة'}),base('licExp','انتهاء الرخصة',{type:'date',section:'الرخصة'}),base('medicalExp','انتهاء الكشف الطبي',{type:'date',section:'الرخصة'}),base('cur','التكليف الحالي',{section:'التكليف'}),base('joinDate','تاريخ بدء العمل',{type:'date',section:'التكليف'}),base('status','الحالة',{type:'select',options:['نشط','غير نشط','إجازة','موقوف'],section:'التكليف'})
  ]},
  contracts:{title:'عقود الإيجار',description:'العقود المربوطة بالأصول المؤجرة وشروط التشغيل والصيانة.',formIntro:'سجل الشروط التجارية والتشغيلية والمالية للعقد وليس مجرد بيانات الأطراف والتواريخ.',fields:[
    base('number','رقم العقد',{required:true,section:'بيانات العقد'}),base('contractType','نوع العقد',{section:'بيانات العقد'}),base('lessor','المؤجر',{required:true,section:'الطرف المتعاقد'}),base('phone','الهاتف',{section:'الطرف المتعاقد'}),base('address','عنوان المؤجر',{section:'الطرف المتعاقد'}),base('assets','الأصول المرتبطة',{required:true,section:'الربط'}),base('start','تاريخ البداية',{type:'date',required:true,section:'الفترة'}),base('end','تاريخ النهاية',{type:'date',required:true,section:'الفترة'}),base('renewal','تاريخ التذكير بالتجديد',{type:'date',section:'الفترة'}),base('rate','السعر',{type:'number',required:true,section:'الأسعار'}),base('unit','الوحدة',{type:'select',options:['ساعة','يوم','شهر','رحلة'],section:'الأسعار'}),base('minimum','الحد الأدنى',{type:'number',section:'الأسعار'}),base('deposit','التأمين / الضمان',{type:'number',section:'الأسعار'}),base('payment','شروط الدفع',{section:'الأسعار'}),base('fuelT','شرط الوقود',{type:'textarea',section:'الشروط',full:true}),base('operT','شرط التشغيل',{type:'textarea',section:'الشروط',full:true}),base('maintT','شرط الصيانة',{type:'textarea',section:'الشروط',full:true}),base('insurance','التأمين والمسؤوليات',{type:'textarea',section:'الشروط',full:true}),base('status','الحالة',{type:'select',options:['ساري','منتهي','قيد التجديد','ملغى'],section:'الاعتماد'}),base('notes','ملاحظات العقد',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  plans:{title:'خطط الصيانة الوقائية',description:'خطط الصيانة المبنية على الوقت أو الكيلومتر أو ساعات التشغيل.',formIntro:'عرّف معيار الاستحقاق والمهام والتكلفة والمسؤولية في خطة واحدة.',fields:[
    base('name','اسم الخطة',{required:true,section:'بيانات الخطة'}),base('asset','الأصل',{required:true,section:'بيانات الخطة'}),base('type','نوع الصيانة',{type:'select',options:['وقائية','دورية','فحص','تشغيلية'],section:'بيانات الخطة'}),base('priority','أهمية الخطة',{type:'select',options:['عادية','عالية','حرجة'],section:'بيانات الخطة'}),
    base('everyHours','كل ساعات تشغيل',{type:'number',section:'الاستحقاق'}),base('everyKm','كل كم',{type:'number',section:'الاستحقاق'}),base('everyDays','كل أيام',{type:'number',section:'الاستحقاق'}),base('lastMeter','آخر عداد',{type:'number',section:'آخر تنفيذ'}),base('lastDate','آخر تنفيذ',{type:'date',section:'آخر تنفيذ'}),base('est','التكلفة التقديرية',{type:'number',section:'التخطيط'}),base('downHrs','التوقف المتوقع بالساعات',{type:'number',section:'التخطيط'}),base('resp','المسؤول',{section:'التخطيط'}),base('spares','قطع الغيار / المواد المطلوبة',{type:'textarea',section:'التخطيط',full:true}),base('tasks','المهام وتعليمات السلامة',{type:'textarea',section:'التنفيذ',full:true}),base('notes','ملاحظات إضافية',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  oils:{title:'الزيوت والفلاتر',description:'خطط تغيير الزيوت والفلاتر وسجلات التنفيذ والتكلفة.',formIntro:'سجل المادة، الدورية، القراءة، الكميات والتكلفة، وليس مجرد اسم الزيت.',fields:[
    base('asset','الأصل',{required:true,section:'الربط'}),base('item','الصنف / المادة',{required:true,section:'المادة'}),base('oilType','نوع الزيت',{required:true,section:'المادة'}),base('unit','الوحدة',{type:'select',options:['لتر','قطعة','عبوة'],section:'المادة'}),base('qty','الكمية',{type:'number',required:true,section:'المادة'}),base('supplier','المورد',{section:'المادة'}),base('everyHours','كل ساعات',{type:'number',section:'الاستحقاق'}),base('everyKm','كل كم',{type:'number',section:'الاستحقاق'}),base('everyDays','كل أيام',{type:'number',section:'الاستحقاق'}),base('lastMeter','آخر عداد',{type:'number',section:'آخر تنفيذ'}),base('lastDate','آخر تغيير',{type:'date',section:'آخر تنفيذ'}),base('matCost','تكلفة المواد',{type:'number',section:'التكلفة'}),base('labCost','تكلفة العمالة',{type:'number',section:'التكلفة'}),base('wo','أمر العمل',{section:'الربط'}),base('by','المنفذ',{section:'التنفيذ'}),base('notes','ملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  tires:{title:'إدارة الإطارات',description:'سجل الإطارات والحالات والتركيب والحركة.',formIntro:'الملف الكامل للإطار يبدأ من الشراء ويمر بالتركيب والموضع والعداد وحالة الإطار.',fields:[
    base('code','كود الإطار',{required:true,section:'بيانات الإطار'}),base('brand','العلامة',{required:true,section:'بيانات الإطار'}),base('size','المقاس',{required:true,section:'بيانات الإطار'}),base('serial','الرقم التسلسلي',{section:'بيانات الإطار'}),base('cost','التكلفة',{type:'number',section:'الشراء'}),base('buy','تاريخ الشراء',{type:'date',section:'الشراء'}),base('supplier','المورد',{section:'الشراء'}),base('install','تاريخ التركيب',{type:'date',section:'التركيب'}),base('asset','الأصل',{section:'التركيب'}),base('position','الموضع',{section:'التركيب'}),base('meterAt','العداد عند التركيب',{type:'number',section:'التركيب'}),base('status','الحالة',{type:'select',options:['مخزن','بالخدمة','يحتاج فحص','تالف','مستبعد'],section:'الحالة'}),base('reason','سبب الفك / الاستبعاد',{type:'textarea',section:'الحالة',full:true}),base('pressure','ضغط التشغيل الموصى به',{type:'number',section:'المتابعة'}),base('tread','عمق النقشة',{type:'number',section:'المتابعة'}),base('notes','ملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  inventory:{title:'المخازن وقطع الغيار',description:'أرصدة الأصناف والحد الأدنى والتكلفة.',formIntro:'بطاقة صنف مخزني كاملة تساعدك على الشراء والجرد والصرف وإدارة الرصيد.',fields:[
    base('code','الكود',{required:true,section:'بيانات الصنف'}),base('name','اسم الصنف',{required:true,section:'بيانات الصنف'}),base('cat','الفئة',{required:true,section:'بيانات الصنف'}),base('brand','العلامة / الشركة',{section:'بيانات الصنف'}),base('barcode','الباركود',{section:'بيانات الصنف'}),base('unit','الوحدة',{required:true,section:'بيانات الصنف'}),base('warehouse','المخزن',{required:true,section:'التخزين'}),base('location','موقع الرف / الخانة',{section:'التخزين'}),base('min','الحد الأدنى',{type:'number',section:'الحدود'}),base('max','الحد الأعلى',{type:'number',section:'الحدود'}),base('reorder','كمية إعادة الطلب',{type:'number',section:'الحدود'}),base('lead','مهلة التوريد بالأيام',{type:'number',section:'الحدود'}),base('cost','التكلفة',{type:'number',section:'التكلفة'}),base('lastCost','آخر تكلفة شراء',{type:'number',section:'التكلفة'}),base('qty','الرصيد الحالي',{type:'number',section:'الرصيد'}),base('opening','الرصيد الافتتاحي',{type:'number',section:'الرصيد'}),base('supplier','المورد المفضل',{section:'التوريد'}),base('notes','ملاحظات الصنف',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  movements:{title:'حركة المخزون',description:'حركات الدخول والخروج والارتباط بأمر العمل والأصل.',formIntro:'سجل المصدر والوجهة والسبب والقيمة والمرجع المستندي لكل حركة مخزون.',fields:[
    base('number','رقم الحركة',{required:true,section:'المستند'}),base('item','الصنف',{required:true,section:'المستند'}),base('type','نوع الحركة',{type:'select',options:['دخول','خروج','تسوية','مرتجع'],required:true,section:'المستند'}),base('date','التاريخ',{type:'date',required:true,section:'المستند'}),base('warehouse','المخزن',{required:true,section:'المخزن'}),base('fromWarehouse','من مخزن',{section:'المخزن'}),base('toWarehouse','إلى مخزن',{section:'المخزن'}),base('qty','الكمية',{type:'number',required:true,section:'الكميات'}),base('unitCost','تكلفة الوحدة',{type:'number',section:'الكميات'}),base('total','الإجمالي',{type:'number',section:'الكميات'}),base('asset','الأصل',{section:'الربط'}),base('wo','أمر العمل',{section:'الربط'}),base('proj','المشروع',{section:'الربط'}),base('requester','طالب الصرف',{section:'الربط'}),base('reference','المرجع المستندي',{section:'المستند'}),base('status','الحالة',{type:'select',options:['مسجلة','معتمدة','مرفوضة'],section:'الاعتماد'}),base('notes','سبب الحركة / الملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  purchases:{title:'المشتريات',description:'الموقع يطلب ولا يشتري مباشرة: طلب ثم مراجعة المخزون ثم الاعتماد ثم أمر الشراء.',formIntro:'طلب شراء كامل يوضح الاحتياج والكميات والمشروع والميزانية والمورد المتوقع.',workflow:{createStatus:'قيد الاعتماد',actions:[{key:'approve',label:'اعتماد',from:['قيد الاعتماد'],to:'معتمد',roles:['admin','fleet','maint'],tone:'primary'},{key:'reject',label:'رفض',from:['قيد الاعتماد'],to:'مرفوض',roles:['admin','fleet','maint'],tone:'danger'},{key:'po',label:'إصدار أمر شراء',from:['معتمد'],to:'أمر شراء',roles:['admin','fleet','maint'],tone:'primary'}]},fields:[
    base('number','رقم الطلب',{required:true,section:'المستند'}),base('date','التاريخ',{type:'date',required:true,section:'المستند'}),base('req','طالب الشراء',{required:true,section:'المستند'}),base('desc','وصف المادة أو الخدمة',{required:true,section:'المحتوى',full:true}),base('category','الفئة',{section:'المحتوى'}),base('qty','الكمية',{type:'number',required:true,section:'المحتوى'}),base('unit','الوحدة',{type:'select',options:['قطعة','طقم','لتر','عبوة','متر','خدمة'],required:true,section:'المحتوى'}),base('requiredDate','تاريخ الاحتياج',{type:'date',section:'المحتوى'}),base('proj','المشروع',{section:'الربط'}),base('warehouse','المخزن المطلوب',{section:'الربط'}),base('reason','سبب الشراء',{type:'textarea',section:'الربط',full:true}),base('est','التكلفة التقديرية',{type:'number',required:true,section:'الميزانية'}),base('budget','بند / ميزانية',{section:'الميزانية'}),base('quotationCount','عدد عروض الأسعار',{type:'number',section:'التوريد'}),base('supplier','المورد المقترح',{section:'التوريد'}),base('paymentTerms','شروط الدفع المقترحة',{section:'التوريد'}),base('status','الحالة',{type:'select',options:['مسودة','قيد الاعتماد','معتمد','مرفوض','أمر شراء'],section:'الاعتماد'}),base('po','أمر الشراء',{section:'الاعتماد'}),base('notes','ملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  costs:{title:'التكاليف والإهلاك',description:'تحليل تكلفة الأصل المباشرة والإهلاك.',formIntro:'سجل بند التكلفة مع مصدره وربطه بالأصل والمشروع والفاتورة عند الحاجة.',fields:[
    base('number','رقم المستند',{section:'المستند'}),base('date','التاريخ',{type:'date',required:true,section:'المستند'}),base('asset','الأصل',{required:true,section:'الربط'}),base('proj','المشروع',{section:'الربط'}),base('kind','نوع التكلفة',{required:true,section:'التكلفة'}),base('category','الفئة',{section:'التكلفة'}),base('qty','الكمية',{type:'number',section:'التكلفة'}),base('unit','الوحدة',{section:'التكلفة'}),base('value','القيمة',{type:'number',required:true,section:'التكلفة'}),base('vendor','المورد / مقدم الخدمة',{section:'المصدر'}),base('invoice','رقم الفاتورة',{section:'المصدر'}),base('costCenter','مركز التكلفة',{section:'الربط'}),base('reference','المرجع المستندي',{section:'المصدر'}),base('notes','ملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  charging:{title:'التحميل الداخلي',description:'تحميل تكلفة تشغيل الأصل على المشروع أو مركز التكلفة.',formIntro:'حدد فترة الاستخدام وأساس التسعير وقيمة التحميل حتى يكون القيد قابلًا للمراجعة.',fields:[
    base('number','رقم التحميل',{section:'المستند'}),base('asset','الأصل',{required:true,section:'الربط'}),base('proj','المشروع',{required:true,section:'الربط'}),base('costCenter','مركز التكلفة',{section:'الربط'}),base('date','التاريخ',{type:'date',required:true,section:'الفترة'}),base('periodFrom','من',{type:'date',section:'الفترة'}),base('periodTo','إلى',{type:'date',section:'الفترة'}),base('basis','أساس التحميل',{type:'select',options:['ساعات','كم','يوم','رحلة','شهر'],section:'التسعير'}),base('hours','الساعات / الوحدات',{type:'number',section:'التسعير'}),base('rate','السعر',{type:'number',section:'التسعير'}),base('min','الحد الأدنى',{type:'number',section:'التسعير'}),base('amount','القيمة',{type:'number',required:true,section:'التسعير'}),base('status','الحالة',{type:'select',options:['مسودة','معتمد'],section:'الاعتماد'}),base('notes','ملاحظات',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  invoices:{title:'الفواتير والمستحقات',description:'الدورة المستندية للفواتير وربطها بالعقود والمشروعات.',formIntro:'سجل الفاتورة بالكامل من الأطراف والمرجع وحتى الاستحقاق والسداد.',fields:[
    base('number','رقم الفاتورة',{required:true,section:'بيانات الفاتورة'}),base('kind','النوع',{type:'select',options:['مورد','عميل'],required:true,section:'بيانات الفاتورة'}),base('party','الجهة',{required:true,section:'الجهة'}),base('partyRef','كود / مرجع الجهة',{section:'الجهة'}),base('link','المرتبط بها',{section:'الربط'}),base('date','التاريخ',{type:'date',required:true,section:'التواريخ'}),base('dueDate','تاريخ الاستحقاق',{type:'date',section:'التواريخ'}),base('description','وصف الفاتورة',{type:'textarea',section:'بيانات الفاتورة',full:true}),base('sub','قبل الضريبة',{type:'number',required:true,section:'القيمة'}),base('vat','الضريبة',{type:'number',section:'القيمة'}),base('discount','الخصم',{type:'number',section:'القيمة'}),base('total','الإجمالي',{type:'number',section:'القيمة'}),base('paid','المسدد',{type:'number',section:'السداد'}),base('remaining','المتبقي',{type:'number',section:'السداد'}),base('paymentMethod','طريقة السداد',{type:'select',options:['تحويل بنكي','شيك','نقدي','آجل'],section:'السداد'}),base('account','الحساب / مركز التكلفة',{section:'السداد'}),base('status','الحالة',{type:'select',options:['مسجلة','بانتظار مراجعة','معتمدة','مرحلة','مدفوعة','محصلة','مرفوضة'],section:'الاعتماد'}),base('notes','ملاحظات المطابقة',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  customers:{title:'العملاء',description:'بيانات العملاء والخدمات الخارجية وربطها بالأصول أو الفواتير.',formIntro:'ملف العميل التجاري والتشغيلي الكامل بدل اسم ورقم هاتف فقط.',fields:[
    base('code','كود العميل',{section:'البيانات الأساسية'}),base('name','اسم العميل',{required:true,section:'البيانات الأساسية'}),base('kind','التصنيف',{required:true,section:'البيانات الأساسية'}),base('contact','جهة الاتصال',{section:'بيانات الاتصال'}),base('phone','الهاتف',{section:'بيانات الاتصال'}),base('email','البريد الإلكتروني',{section:'بيانات الاتصال'}),base('address','العنوان',{section:'بيانات الاتصال',full:true}),base('taxNo','الرقم الضريبي',{section:'البيانات المالية'}),base('paymentTerms','شروط السداد',{section:'البيانات المالية'}),base('creditLimit','الحد الائتماني',{type:'number',section:'البيانات المالية'}),base('salesRep','مسؤول الحساب',{section:'المتابعة'}),base('status','الحالة',{type:'select',options:['نشط','غير نشط','موقوف'],section:'المتابعة'}),base('notes','ملاحظات العميل',{type:'textarea',section:'ملاحظات',full:true})
  ]},
  audit:{title:'سجل التدقيق',description:'سجل العمليات الحساسة التي حدثت داخل النظام.',readOnly:true,fields:[base('ts','الوقت',{section:'السجل'}),base('user','المستخدم',{section:'السجل'}),base('action','الإجراء',{section:'السجل'}),base('entity','الوحدة',{section:'السجل'}),base('ref','المرجع',{section:'السجل'}),base('details','التفاصيل',{type:'textarea',section:'السجل',full:true}),base('source','المصدر',{section:'السجل'})]}
}

export const GENERIC_MODULES = Object.keys(MODULE_CONFIG)
export const MODULE_ROLES: Record<string,string[]> = {
  requests:['admin','fleet','pm','eng'], assignments:['admin','fleet'], operations:['admin','fleet','pm','eng'], trips:['admin','fleet'],
  drivers:['admin','fleet'], contracts:['admin','fleet'], plans:['admin','maint'], oils:['admin','maint'], tires:['admin','maint'],
  inventory:['admin','maint'], movements:['admin','maint'], purchases:['admin','maint','fleet'], costs:[], charging:['admin','acct','fleet'],
  invoices:['admin','acct'], customers:['admin','acct'], audit:[],
}
export function canWriteModule(module:string,role:string){return (MODULE_ROLES[module]??[]).includes(role)}
