-- KEMEX — RBAC / audit hardening
-- Phase: Enterprise Security
-- Goal: make role vocabulary explicit and make audit_log append-only from the Data API.

-- 1) Protect the role vocabulary at database level.
alter table public.profiles
  drop constraint if exists profiles_role_domain_ck;
alter table public.profiles
  add constraint profiles_role_domain_ck check (
    role in ('admin','mgmt','fleet','pm','eng','maint','acct')
  ) not valid;

-- 2) Audit is generated by trusted database triggers/functions only.
-- Clients must never be able to forge, edit, or delete audit records.
drop policy if exists audit_insert on public.audit_log;
revoke insert, update, delete on public.audit_log from authenticated;
revoke insert, update, delete on public.audit_log from anon;
grant select on public.audit_log to authenticated;

drop policy if exists audit_update on public.audit_log;
drop policy if exists audit_delete on public.audit_log;

-- 3) Prevent direct role escalation through profile updates.
-- Admins remain the only role allowed to modify profiles through RLS.
drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles
for all to authenticated
using (private.has_role(array['admin']))
with check (private.has_role(array['admin']));

-- 4) Explicit grants: profile management is intentionally not exposed to normal users.
revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant insert, update, delete on public.profiles to authenticated;

-- 5) Audit indexes for enterprise investigation workloads.
create index if not exists audit_log_user_time_idx
  on public.audit_log(user_id, occurred_at desc);
create index if not exists audit_log_action_time_idx
  on public.audit_log(action, occurred_at desc);
create index if not exists profiles_role_active_idx
  on public.profiles(role, active);

-- NOTE:
-- RLS remains authoritative. The client-side permission matrix only controls UX visibility.
-- Any future action-level permission changes must be mirrored in database policies/RPCs.
