-- 032_multi_tenant_foundation.sql
-- Introduces multi-company (multi-tenant) isolation. This migration is
-- purely additive and safe to run on the existing production database:
-- it creates the tenant registry, backfills ALL existing data under one
-- "default" tenant (the company currently using the system), and adds the
-- helper function every later policy will rely on.
--
-- 033_multi_tenant_retrofit.sql (generated by
-- scripts/generate-tenant-migration.mjs) must run immediately after this
-- one — it adds tenant_id to every other business table and rewrites RLS.

create table if not exists public.tenants (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  plan text not null default 'trial' check (plan in ('trial','standard','enterprise')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Seed the default tenant that all pre-existing data belongs to, named
-- after whatever is already in organization_settings today.
insert into public.tenants (slug, name, plan)
select 'default', coalesce(nullif(trim(s.company_name), ''), 'الشركة الافتراضية'), 'enterprise'
from public.organization_settings s
where s.id = true
on conflict (slug) do nothing;

-- Safety net: if organization_settings was somehow empty, still guarantee a
-- default tenant exists so the backfill below never has nothing to point at.
insert into public.tenants (slug, name, plan)
select 'default', 'الشركة الافتراضية', 'enterprise'
where not exists (select 1 from public.tenants where slug = 'default');

alter table public.profiles add column if not exists tenant_id uuid references public.tenants(id);

update public.profiles
set tenant_id = (select id from public.tenants where slug = 'default')
where tenant_id is null;

alter table public.profiles alter column tenant_id set not null;

create index if not exists profiles_tenant_idx on public.profiles(tenant_id);

-- A user's tenant, looked up once per statement. SECURITY DEFINER so it can
-- read profiles regardless of the caller's own RLS visibility into that row.
-- Defined before anything below references it.
create or replace function private.current_tenant_id()
returns uuid
language sql
security definer
stable
set search_path = public, private
as $$
  select tenant_id from public.profiles where id = auth.uid()
$$;

grant execute on function private.current_tenant_id() to authenticated;
revoke execute on function private.current_tenant_id() from public;

grant select on public.tenants to authenticated;

alter table public.tenants enable row level security;

-- A user may only ever see their own tenant's row (never browse others).
drop policy if exists tenants_self_select on public.tenants;
create policy tenants_self_select on public.tenants for select to authenticated
using (id = private.current_tenant_id());

-- New users are provisioned into a specific tenant explicitly (the
-- admin-create-user edge function passes tenant_id in user_metadata).
-- Fall back to the creating actor's own tenant if it wasn't supplied, and
-- only fall back to "default" for the very first bootstrap admin.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
declare
  meta_tenant uuid := nullif(new.raw_user_meta_data->>'tenant_id','')::uuid;
begin
  insert into public.profiles(id, email, full_name, role, tenant_id)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    'eng',
    coalesce(meta_tenant, (select id from public.tenants where slug = 'default'))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- profiles RLS: a user always sees their own row; admins/mgmt see every
-- profile within their OWN tenant only (never across tenants).
drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select to authenticated
using (id = auth.uid() or (private.has_role(array['admin','mgmt']) and tenant_id = private.current_tenant_id()));

drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles for all to authenticated
using (private.has_role(array['admin']) and tenant_id = private.current_tenant_id())
with check (private.has_role(array['admin']) and tenant_id = private.current_tenant_id());

-- organization_settings becomes one row per tenant instead of one row ever.
alter table public.organization_settings add column if not exists tenant_id uuid references public.tenants(id);
update public.organization_settings set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.organization_settings drop constraint if exists organization_settings_pkey;
alter table public.organization_settings alter column id drop default;
alter table public.organization_settings alter column id drop not null;
alter table public.organization_settings alter column tenant_id set not null;
alter table public.organization_settings alter column tenant_id set default private.current_tenant_id();
alter table public.organization_settings add primary key (tenant_id);
alter table public.organization_settings drop column if exists id;

drop policy if exists settings_read on public.organization_settings;
create policy settings_read on public.organization_settings for select to authenticated
using (tenant_id = private.current_tenant_id());

drop policy if exists settings_write on public.organization_settings;
create policy settings_write on public.organization_settings for all to authenticated
using (private.has_role(array['admin']) and tenant_id = private.current_tenant_id())
with check (private.has_role(array['admin']) and tenant_id = private.current_tenant_id());
