-- 033_multi_tenant_retrofit.sql
-- GENERATED by scripts/generate-tenant-migration.mjs — review before applying.
-- Adds tenant_id to every business table and rewrites every existing RLS
-- policy (as reconstructed from the full migration history) to require
-- tenant_id = private.current_tenant_id(). Existing rows are backfilled
-- into the default tenant created in 032_multi_tenant_foundation.sql.

do $$
begin
  if not exists (select 1 from public.tenants where slug = 'default') then
    raise exception 'Run 032_multi_tenant_foundation.sql first (no default tenant found).';
  end if;
end $$;

-- ---------- approval_events ----------
alter table public.approval_events add column if not exists tenant_id uuid references public.tenants(id);
update public.approval_events set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.approval_events alter column tenant_id set default private.current_tenant_id();
alter table public.approval_events alter column tenant_id set not null;
create index if not exists approval_events_tenant_idx on public.approval_events(tenant_id);
drop policy if exists approval_read on public.approval_events;
create policy approval_read on public.approval_events for select to authenticated using ((private.can_module(module_name,'read')) and tenant_id = private.current_tenant_id());

-- ---------- asset_categories ----------
alter table public.asset_categories add column if not exists tenant_id uuid references public.tenants(id);
update public.asset_categories set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.asset_categories alter column tenant_id set default private.current_tenant_id();
alter table public.asset_categories alter column tenant_id set not null;
create index if not exists asset_categories_tenant_idx on public.asset_categories(tenant_id);
drop policy if exists asset_categories_read on public.asset_categories;
create policy asset_categories_read on public.asset_categories for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists asset_categories_write on public.asset_categories;
create policy asset_categories_write on public.asset_categories for all to authenticated using ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id());

-- ---------- asset_documents ----------
alter table public.asset_documents add column if not exists tenant_id uuid references public.tenants(id);
update public.asset_documents set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.asset_documents alter column tenant_id set default private.current_tenant_id();
alter table public.asset_documents alter column tenant_id set not null;
create index if not exists asset_documents_tenant_idx on public.asset_documents(tenant_id);
drop policy if exists asset_documents_read on public.asset_documents;
create policy asset_documents_read on public.asset_documents for select to authenticated using ((private.can_module('assets','read')) and tenant_id = private.current_tenant_id());
drop policy if exists asset_documents_write on public.asset_documents;
create policy asset_documents_write on public.asset_documents for all to authenticated using ((private.can_module('assets','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('assets','write')) and tenant_id = private.current_tenant_id());

-- ---------- asset_types ----------
alter table public.asset_types add column if not exists tenant_id uuid references public.tenants(id);
update public.asset_types set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.asset_types alter column tenant_id set default private.current_tenant_id();
alter table public.asset_types alter column tenant_id set not null;
create index if not exists asset_types_tenant_idx on public.asset_types(tenant_id);
drop policy if exists asset_types_read on public.asset_types;
create policy asset_types_read on public.asset_types for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists asset_types_write on public.asset_types;
create policy asset_types_write on public.asset_types for all to authenticated using ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id());

-- ---------- assets ----------
alter table public.assets add column if not exists tenant_id uuid references public.tenants(id);
update public.assets set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.assets alter column tenant_id set default private.current_tenant_id();
alter table public.assets alter column tenant_id set not null;
create index if not exists assets_tenant_idx on public.assets(tenant_id);
drop policy if exists assets_read on public.assets;
create policy assets_read on public.assets for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists assets_delete on public.assets;
create policy assets_delete on public.assets for delete to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists assets_write on public.assets;
create policy assets_write on public.assets for insert to authenticated with check ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id());
drop policy if exists assets_update on public.assets;
create policy assets_update on public.assets for update to authenticated using ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id());

-- ---------- assignments ----------
alter table public.assignments add column if not exists tenant_id uuid references public.tenants(id);
update public.assignments set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.assignments alter column tenant_id set default private.current_tenant_id();
alter table public.assignments alter column tenant_id set not null;
create index if not exists assignments_tenant_idx on public.assignments(tenant_id);
drop policy if exists assignments_read on public.assignments;
create policy assignments_read on public.assignments for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists assignments_write on public.assignments;
create policy assignments_write on public.assignments for insert to authenticated with check ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id());
drop policy if exists assignments_update on public.assignments;
create policy assignments_update on public.assignments for update to authenticated using ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id());
drop policy if exists assignments_delete on public.assignments;
create policy assignments_delete on public.assignments for delete to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());

-- ---------- attachment_metadata ----------
alter table public.attachment_metadata add column if not exists tenant_id uuid references public.tenants(id);
update public.attachment_metadata set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.attachment_metadata alter column tenant_id set default private.current_tenant_id();
alter table public.attachment_metadata alter column tenant_id set not null;
create index if not exists attachment_metadata_tenant_idx on public.attachment_metadata(tenant_id);
drop policy if exists attachment_metadata_delete on public.attachment_metadata;
create policy attachment_metadata_delete on public.attachment_metadata for update to authenticated using ((uploaded_by = auth.uid()::uuid OR private.has_role(array['admin'])) and tenant_id = private.current_tenant_id()) with check ((uploaded_by = auth.uid()::uuid OR private.has_role(array['admin'])) and tenant_id = private.current_tenant_id());
drop policy if exists attachment_metadata_read on public.attachment_metadata;
create policy attachment_metadata_read on public.attachment_metadata for select to authenticated using ((private.current_role() <> 'driver'
  OR (
    entity_type IN (
      'trip_receipt',
      'trip_exception'
    )
    AND entity_id IN (
      SELECT t.id::text
      FROM public.trips t
      JOIN public.profiles p
        ON p.driver_id=t.driver_id
      WHERE p.id=auth.uid()
        AND p.active=true
    )
  )) and tenant_id = private.current_tenant_id());
drop policy if exists attachment_metadata_write on public.attachment_metadata;
create policy attachment_metadata_write on public.attachment_metadata for insert to authenticated with check ((uploaded_by = auth.uid()
  AND (
    private.can_action('attachments','write')
    OR (
      private.current_role()='driver'
      AND entity_type IN (
        'trip_receipt',
        'trip_exception'
      )
      AND entity_id IN (
        SELECT t.id::text
        FROM public.trips t
        JOIN public.profiles p
          ON p.driver_id=t.driver_id
        WHERE p.id=auth.uid()
          AND p.active=true
      )
    )
  )) and tenant_id = private.current_tenant_id());

-- ---------- attachments ----------
alter table public.attachments add column if not exists tenant_id uuid references public.tenants(id);
update public.attachments set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.attachments alter column tenant_id set default private.current_tenant_id();
alter table public.attachments alter column tenant_id set not null;
create index if not exists attachments_tenant_idx on public.attachments(tenant_id);
drop policy if exists attachments_read on public.attachments;
create policy attachments_read on public.attachments for select to authenticated using ((private.can_module(module_name,'read')) and tenant_id = private.current_tenant_id());
drop policy if exists attachments_insert on public.attachments;
create policy attachments_insert on public.attachments for insert to authenticated with check ((private.can_module(module_name,'write') and uploaded_by = (select auth.uid())) and tenant_id = private.current_tenant_id());
drop policy if exists attachments_delete on public.attachments;
create policy attachments_delete on public.attachments for delete to authenticated using ((private.can_module(module_name,'write') and uploaded_by = (select auth.uid())) and tenant_id = private.current_tenant_id());

-- ---------- audit_log ----------
alter table public.audit_log add column if not exists tenant_id uuid references public.tenants(id);
update public.audit_log set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.audit_log alter column tenant_id set default private.current_tenant_id();
alter table public.audit_log alter column tenant_id set not null;
create index if not exists audit_log_tenant_idx on public.audit_log(tenant_id);
drop policy if exists audit_read on public.audit_log;
create policy audit_read on public.audit_log for select to authenticated using ((private.has_role(array['admin','mgmt','fleet','maint','acct'])) and tenant_id = private.current_tenant_id());

-- ---------- backup_registry ----------
alter table public.backup_registry add column if not exists tenant_id uuid references public.tenants(id);
update public.backup_registry set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.backup_registry alter column tenant_id set default private.current_tenant_id();
alter table public.backup_registry alter column tenant_id set not null;
create index if not exists backup_registry_tenant_idx on public.backup_registry(tenant_id);
drop policy if exists backup_registry_admin_read on public.backup_registry;
create policy backup_registry_admin_read on public.backup_registry for select to authenticated using ((private.has_role(array['admin','mgmt'])) and tenant_id = private.current_tenant_id());

-- ---------- breakdown_events ----------
alter table public.breakdown_events add column if not exists tenant_id uuid references public.tenants(id);
update public.breakdown_events set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.breakdown_events alter column tenant_id set default private.current_tenant_id();
alter table public.breakdown_events alter column tenant_id set not null;
create index if not exists breakdown_events_tenant_idx on public.breakdown_events(tenant_id);
drop policy if exists breakdown_events_read on public.breakdown_events;
create policy breakdown_events_read on public.breakdown_events for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists breakdown_events_write on public.breakdown_events;
create policy breakdown_events_write on public.breakdown_events for insert to authenticated with check ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists breakdown_events_update on public.breakdown_events;
create policy breakdown_events_update on public.breakdown_events for update to authenticated using ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists breakdown_events_delete on public.breakdown_events;
create policy breakdown_events_delete on public.breakdown_events for delete to authenticated using ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());

-- ---------- charging_rates ----------
alter table public.charging_rates add column if not exists tenant_id uuid references public.tenants(id);
update public.charging_rates set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.charging_rates alter column tenant_id set default private.current_tenant_id();
alter table public.charging_rates alter column tenant_id set not null;
create index if not exists charging_rates_tenant_idx on public.charging_rates(tenant_id);
drop policy if exists charging_rates_read on public.charging_rates;
create policy charging_rates_read on public.charging_rates for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists charging_rates_write on public.charging_rates;
create policy charging_rates_write on public.charging_rates for all to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());

-- ---------- client_error_events ----------
alter table public.client_error_events add column if not exists tenant_id uuid references public.tenants(id);
update public.client_error_events set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.client_error_events alter column tenant_id set default private.current_tenant_id();
alter table public.client_error_events alter column tenant_id set not null;
create index if not exists client_error_events_tenant_idx on public.client_error_events(tenant_id);
drop policy if exists client_error_events_insert on public.client_error_events;
create policy client_error_events_insert on public.client_error_events for insert to authenticated with check ((actor_id = auth.uid()::uuid) and tenant_id = private.current_tenant_id());
drop policy if exists client_error_events_admin_read on public.client_error_events;
create policy client_error_events_admin_read on public.client_error_events for select to authenticated using ((private.has_role(array['admin','mgmt'])) and tenant_id = private.current_tenant_id());

-- ---------- clients ----------
alter table public.clients add column if not exists tenant_id uuid references public.tenants(id);
update public.clients set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.clients alter column tenant_id set default private.current_tenant_id();
alter table public.clients alter column tenant_id set not null;
create index if not exists clients_tenant_idx on public.clients(tenant_id);
drop policy if exists clients_read on public.clients;
create policy clients_read on public.clients for select to authenticated using ((private.can_module('customers','read')) and tenant_id = private.current_tenant_id());
drop policy if exists clients_write on public.clients;
create policy clients_write on public.clients for all to authenticated using ((private.can_module('customers','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('customers','write')) and tenant_id = private.current_tenant_id());

-- ---------- contracts ----------
alter table public.contracts add column if not exists tenant_id uuid references public.tenants(id);
update public.contracts set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.contracts alter column tenant_id set default private.current_tenant_id();
alter table public.contracts alter column tenant_id set not null;
create index if not exists contracts_tenant_idx on public.contracts(tenant_id);
drop policy if exists contracts_read on public.contracts;
create policy contracts_read on public.contracts for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists contracts_delete on public.contracts;
create policy contracts_delete on public.contracts for delete to authenticated using ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id());
drop policy if exists contracts_write on public.contracts;
create policy contracts_write on public.contracts for insert to authenticated with check ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists contracts_update on public.contracts;
create policy contracts_update on public.contracts for update to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());

-- ---------- cost_centers ----------
alter table public.cost_centers add column if not exists tenant_id uuid references public.tenants(id);
update public.cost_centers set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.cost_centers alter column tenant_id set default private.current_tenant_id();
alter table public.cost_centers alter column tenant_id set not null;
create index if not exists cost_centers_tenant_idx on public.cost_centers(tenant_id);
drop policy if exists cost_centers_read on public.cost_centers;
create policy cost_centers_read on public.cost_centers for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists cost_centers_write on public.cost_centers;
create policy cost_centers_write on public.cost_centers for all to authenticated using ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id());

-- ---------- cost_entries ----------
alter table public.cost_entries add column if not exists tenant_id uuid references public.tenants(id);
update public.cost_entries set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.cost_entries alter column tenant_id set default private.current_tenant_id();
alter table public.cost_entries alter column tenant_id set not null;
create index if not exists cost_entries_tenant_idx on public.cost_entries(tenant_id);
drop policy if exists cost_entries_read on public.cost_entries;
create policy cost_entries_read on public.cost_entries for select to authenticated using ((private.can_module('costs','read')) and tenant_id = private.current_tenant_id());
drop policy if exists cost_entries_write on public.cost_entries;
create policy cost_entries_write on public.cost_entries for all to authenticated using ((private.can_module('costs','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('costs','write')) and tenant_id = private.current_tenant_id());

-- ---------- downtime_tracking ----------
alter table public.downtime_tracking add column if not exists tenant_id uuid references public.tenants(id);
update public.downtime_tracking set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.downtime_tracking alter column tenant_id set default private.current_tenant_id();
alter table public.downtime_tracking alter column tenant_id set not null;
create index if not exists downtime_tracking_tenant_idx on public.downtime_tracking(tenant_id);
drop policy if exists downtime_tracking_read on public.downtime_tracking;
create policy downtime_tracking_read on public.downtime_tracking for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists downtime_tracking_write on public.downtime_tracking;
create policy downtime_tracking_write on public.downtime_tracking for insert to authenticated with check ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists downtime_tracking_update on public.downtime_tracking;
create policy downtime_tracking_update on public.downtime_tracking for update to authenticated using ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists downtime_tracking_delete on public.downtime_tracking;
create policy downtime_tracking_delete on public.downtime_tracking for delete to authenticated using ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());

-- ---------- drivers ----------
alter table public.drivers add column if not exists tenant_id uuid references public.tenants(id);
update public.drivers set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.drivers alter column tenant_id set default private.current_tenant_id();
alter table public.drivers alter column tenant_id set not null;
create index if not exists drivers_tenant_idx on public.drivers(tenant_id);
drop policy if exists drivers_delete on public.drivers;
create policy drivers_delete on public.drivers for delete to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists drivers_update on public.drivers;
create policy drivers_update on public.drivers for update to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists drivers_read on public.drivers;
create policy drivers_read on public.drivers for select to authenticated using ((private.can_module('drivers','read')
  OR (
    private.current_role()='driver'
    AND id = (
      SELECT p.driver_id
      FROM public.profiles p
      WHERE p.id=auth.uid()
        AND p.active=true
    )
  )) and tenant_id = private.current_tenant_id());
drop policy if exists drivers_write on public.drivers;
create policy drivers_write on public.drivers for all to authenticated using ((private.can_module('drivers','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('drivers','write')) and tenant_id = private.current_tenant_id());

-- ---------- fuel_operations ----------
alter table public.fuel_operations add column if not exists tenant_id uuid references public.tenants(id);
update public.fuel_operations set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.fuel_operations alter column tenant_id set default private.current_tenant_id();
alter table public.fuel_operations alter column tenant_id set not null;
create index if not exists fuel_operations_tenant_idx on public.fuel_operations(tenant_id);
drop policy if exists fuel_read on public.fuel_operations;
create policy fuel_read on public.fuel_operations for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists fuel_delete on public.fuel_operations;
create policy fuel_delete on public.fuel_operations for delete to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists fuel_write on public.fuel_operations;
create policy fuel_write on public.fuel_operations for insert to authenticated with check ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists fuel_update on public.fuel_operations;
create policy fuel_update on public.fuel_operations for update to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());

-- ---------- inventory_items ----------
alter table public.inventory_items add column if not exists tenant_id uuid references public.tenants(id);
update public.inventory_items set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.inventory_items alter column tenant_id set default private.current_tenant_id();
alter table public.inventory_items alter column tenant_id set not null;
create index if not exists inventory_items_tenant_idx on public.inventory_items(tenant_id);
drop policy if exists inventory_items_read on public.inventory_items;
create policy inventory_items_read on public.inventory_items for select to authenticated using ((private.can_module('inventory','read')) and tenant_id = private.current_tenant_id());
drop policy if exists inventory_items_write on public.inventory_items;
create policy inventory_items_write on public.inventory_items for all to authenticated using ((private.can_module('inventory','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('inventory','write')) and tenant_id = private.current_tenant_id());

-- ---------- invoice_documents ----------
alter table public.invoice_documents add column if not exists tenant_id uuid references public.tenants(id);
update public.invoice_documents set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.invoice_documents alter column tenant_id set default private.current_tenant_id();
alter table public.invoice_documents alter column tenant_id set not null;
create index if not exists invoice_documents_tenant_idx on public.invoice_documents(tenant_id);
drop policy if exists invoice_documents_read on public.invoice_documents;
create policy invoice_documents_read on public.invoice_documents for select to authenticated using ((private.can_module('invoices','read')) and tenant_id = private.current_tenant_id());

-- ---------- maintenance_cost_items ----------
alter table public.maintenance_cost_items add column if not exists tenant_id uuid references public.tenants(id);
update public.maintenance_cost_items set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.maintenance_cost_items alter column tenant_id set default private.current_tenant_id();
alter table public.maintenance_cost_items alter column tenant_id set not null;
create index if not exists maintenance_cost_items_tenant_idx on public.maintenance_cost_items(tenant_id);
drop policy if exists maintenance_cost_items_read on public.maintenance_cost_items;
create policy maintenance_cost_items_read on public.maintenance_cost_items for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_cost_items_write on public.maintenance_cost_items;
create policy maintenance_cost_items_write on public.maintenance_cost_items for insert to authenticated with check ((private.has_role(array['admin','fleet','maint','eng','acct'])) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_cost_items_update on public.maintenance_cost_items;
create policy maintenance_cost_items_update on public.maintenance_cost_items for update to authenticated using ((private.has_role(array['admin','fleet','maint','eng','acct'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint','eng','acct'])) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_cost_items_delete on public.maintenance_cost_items;
create policy maintenance_cost_items_delete on public.maintenance_cost_items for delete to authenticated using ((private.has_role(array['admin','fleet','maint','acct'])) and tenant_id = private.current_tenant_id());

-- ---------- maintenance_parts ----------
alter table public.maintenance_parts add column if not exists tenant_id uuid references public.tenants(id);
update public.maintenance_parts set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.maintenance_parts alter column tenant_id set default private.current_tenant_id();
alter table public.maintenance_parts alter column tenant_id set not null;
create index if not exists maintenance_parts_tenant_idx on public.maintenance_parts(tenant_id);
drop policy if exists maintenance_parts_read on public.maintenance_parts;
create policy maintenance_parts_read on public.maintenance_parts for select to authenticated using ((private.can_module('maintenance','read')) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_parts_write on public.maintenance_parts;
create policy maintenance_parts_write on public.maintenance_parts for all to authenticated using ((private.can_module('maintenance','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('maintenance','write')) and tenant_id = private.current_tenant_id());

-- ---------- maintenance_technicians ----------
alter table public.maintenance_technicians add column if not exists tenant_id uuid references public.tenants(id);
update public.maintenance_technicians set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.maintenance_technicians alter column tenant_id set default private.current_tenant_id();
alter table public.maintenance_technicians alter column tenant_id set not null;
create index if not exists maintenance_technicians_tenant_idx on public.maintenance_technicians(tenant_id);
drop policy if exists maintenance_technicians_read on public.maintenance_technicians;
create policy maintenance_technicians_read on public.maintenance_technicians for select to authenticated using ((private.can_module('maintenance','read') or private.can_module('work_orders','read')) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_technicians_write on public.maintenance_technicians;
create policy maintenance_technicians_write on public.maintenance_technicians for all to authenticated using ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());

-- ---------- maintenance_transports ----------
alter table public.maintenance_transports add column if not exists tenant_id uuid references public.tenants(id);
update public.maintenance_transports set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.maintenance_transports alter column tenant_id set default private.current_tenant_id();
alter table public.maintenance_transports alter column tenant_id set not null;
create index if not exists maintenance_transports_tenant_idx on public.maintenance_transports(tenant_id);
drop policy if exists maintenance_transports_read on public.maintenance_transports;
create policy maintenance_transports_read on public.maintenance_transports for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_transports_write on public.maintenance_transports;
create policy maintenance_transports_write on public.maintenance_transports for insert to authenticated with check ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_transports_update on public.maintenance_transports;
create policy maintenance_transports_update on public.maintenance_transports for update to authenticated using ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists maintenance_transports_delete on public.maintenance_transports;
create policy maintenance_transports_delete on public.maintenance_transports for delete to authenticated using ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());

-- ---------- notification_outbox ----------
alter table public.notification_outbox add column if not exists tenant_id uuid references public.tenants(id);
update public.notification_outbox set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.notification_outbox alter column tenant_id set default private.current_tenant_id();
alter table public.notification_outbox alter column tenant_id set not null;
create index if not exists notification_outbox_tenant_idx on public.notification_outbox(tenant_id);
drop policy if exists notification_outbox_read on public.notification_outbox;
create policy notification_outbox_read on public.notification_outbox for select to authenticated using ((recipient_id = auth.uid()::uuid) and tenant_id = private.current_tenant_id());
drop policy if exists notification_outbox_update on public.notification_outbox;
create policy notification_outbox_update on public.notification_outbox for update to authenticated using ((recipient_id = auth.uid()::uuid) and tenant_id = private.current_tenant_id()) with check ((recipient_id = auth.uid()::uuid) and tenant_id = private.current_tenant_id());

-- ---------- operations ----------
alter table public.operations add column if not exists tenant_id uuid references public.tenants(id);
update public.operations set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.operations alter column tenant_id set default private.current_tenant_id();
alter table public.operations alter column tenant_id set not null;
create index if not exists operations_tenant_idx on public.operations(tenant_id);
drop policy if exists operations_read on public.operations;
create policy operations_read on public.operations for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists operations_write on public.operations;
create policy operations_write on public.operations for insert to authenticated with check ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists operations_update on public.operations;
create policy operations_update on public.operations for update to authenticated using ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists operations_delete on public.operations;
create policy operations_delete on public.operations for delete to authenticated using ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id());

-- ---------- project_memberships ----------
alter table public.project_memberships add column if not exists tenant_id uuid references public.tenants(id);
update public.project_memberships set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.project_memberships alter column tenant_id set default private.current_tenant_id();
alter table public.project_memberships alter column tenant_id set not null;
create index if not exists project_memberships_tenant_idx on public.project_memberships(tenant_id);
drop policy if exists project_memberships_read on public.project_memberships;
create policy project_memberships_read on public.project_memberships for select to authenticated using ((private.can_module('projects','read')) and tenant_id = private.current_tenant_id());
drop policy if exists project_memberships_write on public.project_memberships;
create policy project_memberships_write on public.project_memberships for all to authenticated using ((private.has_role(array['admin','pm'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','pm'])) and tenant_id = private.current_tenant_id());

-- ---------- projects ----------
alter table public.projects add column if not exists tenant_id uuid references public.tenants(id);
update public.projects set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.projects alter column tenant_id set default private.current_tenant_id();
alter table public.projects alter column tenant_id set not null;
create index if not exists projects_tenant_idx on public.projects(tenant_id);
drop policy if exists projects_read on public.projects;
create policy projects_read on public.projects for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists projects_delete on public.projects;
create policy projects_delete on public.projects for delete to authenticated using ((private.has_role(array['admin'])) and tenant_id = private.current_tenant_id());
drop policy if exists projects_write on public.projects;
create policy projects_write on public.projects for insert to authenticated with check ((private.has_role(array['admin','fleet','pm','acct'])) and tenant_id = private.current_tenant_id());
drop policy if exists projects_update on public.projects;
create policy projects_update on public.projects for update to authenticated using ((private.has_role(array['admin','fleet','pm','acct'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','pm','acct'])) and tenant_id = private.current_tenant_id());

-- ---------- purchase_orders ----------
alter table public.purchase_orders add column if not exists tenant_id uuid references public.tenants(id);
update public.purchase_orders set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.purchase_orders alter column tenant_id set default private.current_tenant_id();
alter table public.purchase_orders alter column tenant_id set not null;
create index if not exists purchase_orders_tenant_idx on public.purchase_orders(tenant_id);
drop policy if exists purchase_orders_read on public.purchase_orders;
create policy purchase_orders_read on public.purchase_orders for select to authenticated using ((private.can_module('purchases','read')) and tenant_id = private.current_tenant_id());

-- ---------- stock_movements ----------
alter table public.stock_movements add column if not exists tenant_id uuid references public.tenants(id);
update public.stock_movements set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.stock_movements alter column tenant_id set default private.current_tenant_id();
alter table public.stock_movements alter column tenant_id set not null;
create index if not exists stock_movements_tenant_idx on public.stock_movements(tenant_id);
drop policy if exists stock_movements_read on public.stock_movements;
create policy stock_movements_read on public.stock_movements for select to authenticated using ((private.can_module('movements','read')) and tenant_id = private.current_tenant_id());
drop policy if exists stock_movements_write on public.stock_movements;
create policy stock_movements_write on public.stock_movements for insert to authenticated with check ((private.can_module('movements','write')) and tenant_id = private.current_tenant_id());

-- ---------- tfms_module_records ----------
alter table public.tfms_module_records add column if not exists tenant_id uuid references public.tenants(id);
update public.tfms_module_records set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.tfms_module_records alter column tenant_id set default private.current_tenant_id();
alter table public.tfms_module_records alter column tenant_id set not null;
create index if not exists tfms_module_records_tenant_idx on public.tfms_module_records(tenant_id);
drop policy if exists module_records_read on public.tfms_module_records;
create policy module_records_read on public.tfms_module_records for select to authenticated using ((private.can_module(module_name,'read')) and tenant_id = private.current_tenant_id());
drop policy if exists module_records_insert on public.tfms_module_records;
create policy module_records_insert on public.tfms_module_records for insert to authenticated with check ((private.can_module(module_name,'write')) and tenant_id = private.current_tenant_id());
drop policy if exists module_records_update on public.tfms_module_records;
create policy module_records_update on public.tfms_module_records for update to authenticated using ((private.can_module(module_name,'write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module(module_name,'write')) and tenant_id = private.current_tenant_id());
drop policy if exists module_records_delete on public.tfms_module_records;
create policy module_records_delete on public.tfms_module_records for delete to authenticated using ((private.can_module(module_name,'write')) and tenant_id = private.current_tenant_id());

-- ---------- trip_costs ----------
alter table public.trip_costs add column if not exists tenant_id uuid references public.tenants(id);
update public.trip_costs set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.trip_costs alter column tenant_id set default private.current_tenant_id();
alter table public.trip_costs alter column tenant_id set not null;
create index if not exists trip_costs_tenant_idx on public.trip_costs(tenant_id);
drop policy if exists trip_costs_read on public.trip_costs;
create policy trip_costs_read on public.trip_costs for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists trip_costs_write on public.trip_costs;
create policy trip_costs_write on public.trip_costs for insert to authenticated with check ((private.has_role(array['admin','fleet','pm','acct'])) and tenant_id = private.current_tenant_id());
drop policy if exists trip_costs_update on public.trip_costs;
create policy trip_costs_update on public.trip_costs for update to authenticated using ((private.has_role(array['admin','fleet','pm','acct'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','pm','acct'])) and tenant_id = private.current_tenant_id());
drop policy if exists trip_costs_delete on public.trip_costs;
create policy trip_costs_delete on public.trip_costs for delete to authenticated using ((private.has_role(array['admin','fleet','acct'])) and tenant_id = private.current_tenant_id());

-- ---------- trip_exceptions ----------
alter table public.trip_exceptions add column if not exists tenant_id uuid references public.tenants(id);
update public.trip_exceptions set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.trip_exceptions alter column tenant_id set default private.current_tenant_id();
alter table public.trip_exceptions alter column tenant_id set not null;
create index if not exists trip_exceptions_tenant_idx on public.trip_exceptions(tenant_id);
drop policy if exists trip_exceptions_read on public.trip_exceptions;
create policy trip_exceptions_read on public.trip_exceptions for select to authenticated using ((private.can_module('trips','read')
  OR (
    private.current_role()='driver'
    AND trip_id IN (
      SELECT t.id
      FROM public.trips t
      JOIN public.profiles p
        ON p.driver_id=t.driver_id
      WHERE p.id=auth.uid()
        AND p.active=true
    )
  )) and tenant_id = private.current_tenant_id());
drop policy if exists trip_exceptions_insert on public.trip_exceptions;
create policy trip_exceptions_insert on public.trip_exceptions for insert to authenticated with check ((reported_by = auth.uid()
  AND private.can_action('trips','exception_report')
  AND private.current_role() <> 'driver') and tenant_id = private.current_tenant_id());
drop policy if exists trip_exceptions_update on public.trip_exceptions;
create policy trip_exceptions_update on public.trip_exceptions for update to authenticated using ((private.can_action('trips','exception_manage')) and tenant_id = private.current_tenant_id()) with check ((private.can_action('trips','exception_manage')) and tenant_id = private.current_tenant_id());

-- ---------- trip_execution_events ----------
alter table public.trip_execution_events add column if not exists tenant_id uuid references public.tenants(id);
update public.trip_execution_events set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.trip_execution_events alter column tenant_id set default private.current_tenant_id();
alter table public.trip_execution_events alter column tenant_id set not null;
create index if not exists trip_execution_events_tenant_idx on public.trip_execution_events(tenant_id);
drop policy if exists trip_execution_events_read on public.trip_execution_events;
create policy trip_execution_events_read on public.trip_execution_events for select to authenticated using ((private.can_module('trips','read')
  OR (
    private.current_role()='driver'
    AND trip_id IN (
      SELECT t.id
      FROM public.trips t
      JOIN public.profiles p
        ON p.driver_id=t.driver_id
      WHERE p.id=auth.uid()
        AND p.active=true
    )
  )) and tenant_id = private.current_tenant_id());

-- ---------- trip_permits ----------
alter table public.trip_permits add column if not exists tenant_id uuid references public.tenants(id);
update public.trip_permits set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.trip_permits alter column tenant_id set default private.current_tenant_id();
alter table public.trip_permits alter column tenant_id set not null;
create index if not exists trip_permits_tenant_idx on public.trip_permits(tenant_id);
drop policy if exists trip_permits_read on public.trip_permits;
create policy trip_permits_read on public.trip_permits for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists trip_permits_write on public.trip_permits;
create policy trip_permits_write on public.trip_permits for insert to authenticated with check ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists trip_permits_update on public.trip_permits;
create policy trip_permits_update on public.trip_permits for update to authenticated using ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists trip_permits_delete on public.trip_permits;
create policy trip_permits_delete on public.trip_permits for delete to authenticated using ((private.has_role(array['admin','fleet','pm'])) and tenant_id = private.current_tenant_id());

-- ---------- trip_receipts ----------
alter table public.trip_receipts add column if not exists tenant_id uuid references public.tenants(id);
update public.trip_receipts set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.trip_receipts alter column tenant_id set default private.current_tenant_id();
alter table public.trip_receipts alter column tenant_id set not null;
create index if not exists trip_receipts_tenant_idx on public.trip_receipts(tenant_id);
drop policy if exists trip_receipts_read on public.trip_receipts;
create policy trip_receipts_read on public.trip_receipts for select to authenticated using ((private.can_module('trips','read')
  OR (
    private.current_role()='driver'
    AND trip_id IN (
      SELECT t.id
      FROM public.trips t
      JOIN public.profiles p
        ON p.driver_id=t.driver_id
      WHERE p.id=auth.uid()
        AND p.active=true
    )
  )) and tenant_id = private.current_tenant_id());
drop policy if exists trip_receipts_insert on public.trip_receipts;
create policy trip_receipts_insert on public.trip_receipts for insert to authenticated with check ((uploaded_by = auth.uid()
  AND (
    private.can_action('attachments','write')
    OR (
      private.current_role()='driver'
      AND private.can_action('trips','driver_receipt')
      AND trip_id IN (
        SELECT t.id
        FROM public.trips t
        JOIN public.profiles p
          ON p.driver_id=t.driver_id
        WHERE p.id=auth.uid()
          AND p.active=true
      )
      AND EXISTS (
        SELECT 1
        FROM public.attachment_metadata am
        WHERE am.id = attachment_id
          AND am.entity_type = 'trip_receipt'
          AND am.entity_id = trip_id::text
          AND am.uploaded_by = auth.uid()
      )
    )
  )) and tenant_id = private.current_tenant_id());

-- ---------- trips ----------
alter table public.trips add column if not exists tenant_id uuid references public.tenants(id);
update public.trips set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.trips alter column tenant_id set default private.current_tenant_id();
alter table public.trips alter column tenant_id set not null;
create index if not exists trips_tenant_idx on public.trips(tenant_id);
drop policy if exists trips_write on public.trips;
create policy trips_write on public.trips for insert to authenticated with check ((private.has_role(array['admin','fleet','pm','eng'])) and tenant_id = private.current_tenant_id());
drop policy if exists trips_delete on public.trips;
create policy trips_delete on public.trips for delete to authenticated using ((private.has_role(array['admin','fleet'])) and tenant_id = private.current_tenant_id());
drop policy if exists trips_read on public.trips;
create policy trips_read on public.trips for select to authenticated using ((private.can_module('trips','read')
  OR (
    private.current_role()='driver'
    AND driver_id = (
      SELECT p.driver_id
      FROM public.profiles p
      WHERE p.id=auth.uid()
        AND p.active=true
    )
  )) and tenant_id = private.current_tenant_id());
drop policy if exists trips_update on public.trips;
create policy trips_update on public.trips for update to authenticated using ((private.can_module('trips','write')) and tenant_id = private.current_tenant_id()) with check ((private.can_module('trips','write')) and tenant_id = private.current_tenant_id());

-- ---------- user_notifications ----------
alter table public.user_notifications add column if not exists tenant_id uuid references public.tenants(id);
update public.user_notifications set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.user_notifications alter column tenant_id set default private.current_tenant_id();
alter table public.user_notifications alter column tenant_id set not null;
create index if not exists user_notifications_tenant_idx on public.user_notifications(tenant_id);
drop policy if exists notifications_select_own on public.user_notifications;
create policy notifications_select_own on public.user_notifications for select to authenticated using ((user_id = (select auth.uid())) and tenant_id = private.current_tenant_id());
drop policy if exists notifications_update_own on public.user_notifications;
create policy notifications_update_own on public.user_notifications for update to authenticated using ((user_id = (select auth.uid())) and tenant_id = private.current_tenant_id()) with check ((user_id = (select auth.uid())) and tenant_id = private.current_tenant_id());

-- ---------- vehicle_gps_devices ----------
alter table public.vehicle_gps_devices add column if not exists tenant_id uuid references public.tenants(id);
update public.vehicle_gps_devices set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.vehicle_gps_devices alter column tenant_id set default private.current_tenant_id();
alter table public.vehicle_gps_devices alter column tenant_id set not null;
create index if not exists vehicle_gps_devices_tenant_idx on public.vehicle_gps_devices(tenant_id);
drop policy if exists vehicle_gps_devices_read on public.vehicle_gps_devices;
create policy vehicle_gps_devices_read on public.vehicle_gps_devices for select to authenticated using ((private.can_action('trips','monitor')) and tenant_id = private.current_tenant_id());
drop policy if exists vehicle_gps_devices_insert on public.vehicle_gps_devices;
create policy vehicle_gps_devices_insert on public.vehicle_gps_devices for insert to authenticated with check ((private.current_role() IN ('admin','fleet')) and tenant_id = private.current_tenant_id());
drop policy if exists vehicle_gps_devices_update on public.vehicle_gps_devices;
create policy vehicle_gps_devices_update on public.vehicle_gps_devices for update to authenticated using ((private.current_role() IN ('admin','fleet')) and tenant_id = private.current_tenant_id()) with check ((private.current_role() IN ('admin','fleet')) and tenant_id = private.current_tenant_id());

-- ---------- vehicle_gps_positions ----------
alter table public.vehicle_gps_positions add column if not exists tenant_id uuid references public.tenants(id);
update public.vehicle_gps_positions set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.vehicle_gps_positions alter column tenant_id set default private.current_tenant_id();
alter table public.vehicle_gps_positions alter column tenant_id set not null;
create index if not exists vehicle_gps_positions_tenant_idx on public.vehicle_gps_positions(tenant_id);
drop policy if exists vehicle_gps_positions_read on public.vehicle_gps_positions;
create policy vehicle_gps_positions_read on public.vehicle_gps_positions for select to authenticated using ((private.can_action('trips','monitor')) and tenant_id = private.current_tenant_id());
drop policy if exists vehicle_gps_positions_insert on public.vehicle_gps_positions;
create policy vehicle_gps_positions_insert on public.vehicle_gps_positions for insert to authenticated with check ((false) and tenant_id = private.current_tenant_id());

-- ---------- warehouses ----------
alter table public.warehouses add column if not exists tenant_id uuid references public.tenants(id);
update public.warehouses set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.warehouses alter column tenant_id set default private.current_tenant_id();
alter table public.warehouses alter column tenant_id set not null;
create index if not exists warehouses_tenant_idx on public.warehouses(tenant_id);
drop policy if exists warehouses_read on public.warehouses;
create policy warehouses_read on public.warehouses for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists warehouses_write on public.warehouses;
create policy warehouses_write on public.warehouses for all to authenticated using ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());

-- ---------- work_orders ----------
alter table public.work_orders add column if not exists tenant_id uuid references public.tenants(id);
update public.work_orders set tenant_id = (select id from public.tenants where slug = 'default') where tenant_id is null;
alter table public.work_orders alter column tenant_id set default private.current_tenant_id();
alter table public.work_orders alter column tenant_id set not null;
create index if not exists work_orders_tenant_idx on public.work_orders(tenant_id);
drop policy if exists work_orders_read on public.work_orders;
create policy work_orders_read on public.work_orders for select to authenticated using ((true) and tenant_id = private.current_tenant_id());
drop policy if exists work_orders_delete on public.work_orders;
create policy work_orders_delete on public.work_orders for delete to authenticated using ((private.has_role(array['admin','maint'])) and tenant_id = private.current_tenant_id());
drop policy if exists work_orders_write on public.work_orders;
create policy work_orders_write on public.work_orders for insert to authenticated with check ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());
drop policy if exists work_orders_update on public.work_orders;
create policy work_orders_update on public.work_orders for update to authenticated using ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id()) with check ((private.has_role(array['admin','fleet','maint'])) and tenant_id = private.current_tenant_id());

